module Lithic
  module Models
    module CreditProducts
      type prime_rate_retrieve_params =
        { ending_before: Date, starting_after: Date }
        & Lithic::Internal::Type::request_parameters

      class PrimeRateRetrieveParams < Lithic::Internal::Type::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        attr_reader ending_before: Date?

        def ending_before=: (Date) -> Date

        attr_reader starting_after: Date?

        def starting_after=: (Date) -> Date

        def initialize: (
          ?ending_before: Date,
          ?starting_after: Date,
          ?request_options: Lithic::request_opts
        ) -> void
      end
    end
  end
end
