module Lithic
  module Models
    module Reports
      module Settlement
        type network_total_retrieve_params = {  } & Lithic::request_parameters

        class NetworkTotalRetrieveParams < Lithic::BaseModel
          extend Lithic::Type::RequestParameters::Converter
          include Lithic::RequestParameters

          def initialize: (?request_options: Lithic::request_opts) -> void

          def to_hash: -> Lithic::Models::Reports::Settlement::network_total_retrieve_params
        end
      end
    end
  end
end
