module Lithic
  module Models
    module FinancialAccounts
      class StatementLineItems = Statements::StatementLineItems

      module Statements
        type statement_line_items =
          {
            data: ::Array[Lithic::FinancialAccounts::Statements::StatementLineItems::Data],
            has_more: bool
          }

        class StatementLineItems < Lithic::Internal::Type::BaseModel
          attr_accessor data: ::Array[Lithic::FinancialAccounts::Statements::StatementLineItems::Data]

          attr_accessor has_more: bool

          def initialize: (
            data: ::Array[Lithic::FinancialAccounts::Statements::StatementLineItems::Data],
            has_more: bool
          ) -> void

          def to_hash: -> {
            data: ::Array[Lithic::FinancialAccounts::Statements::StatementLineItems::Data],
            has_more: bool
          }

          type data =
            {
              token: String,
              amount: Integer,
              category: Lithic::Models::FinancialAccounts::Statements::StatementLineItems::Data::category,
              created: Time,
              currency: String,
              effective_date: Date,
              event_type: Lithic::Models::FinancialAccounts::Statements::StatementLineItems::Data::event_type,
              financial_account_token: String,
              financial_transaction_event_token: String,
              financial_transaction_token: String,
              card_token: String,
              descriptor: String
            }

          class Data < Lithic::Internal::Type::BaseModel
            attr_accessor token: String

            attr_accessor amount: Integer

            attr_accessor category: Lithic::Models::FinancialAccounts::Statements::StatementLineItems::Data::category

            attr_accessor created: Time

            attr_accessor currency: String

            attr_accessor effective_date: Date

            attr_accessor event_type: Lithic::Models::FinancialAccounts::Statements::StatementLineItems::Data::event_type

            attr_accessor financial_account_token: String

            attr_accessor financial_transaction_event_token: String

            attr_accessor financial_transaction_token: String

            attr_reader card_token: String?

            def card_token=: (String) -> String

            attr_reader descriptor: String?

            def descriptor=: (String) -> String

            def initialize: (
              token: String,
              amount: Integer,
              category: Lithic::Models::FinancialAccounts::Statements::StatementLineItems::Data::category,
              created: Time,
              currency: String,
              effective_date: Date,
              event_type: Lithic::Models::FinancialAccounts::Statements::StatementLineItems::Data::event_type,
              financial_account_token: String,
              financial_transaction_event_token: String,
              financial_transaction_token: String,
              ?card_token: String,
              ?descriptor: String
            ) -> void

            def to_hash: -> {
              token: String,
              amount: Integer,
              category: Lithic::Models::FinancialAccounts::Statements::StatementLineItems::Data::category,
              created: Time,
              currency: String,
              effective_date: Date,
              event_type: Lithic::Models::FinancialAccounts::Statements::StatementLineItems::Data::event_type,
              financial_account_token: String,
              financial_transaction_event_token: String,
              financial_transaction_token: String,
              card_token: String,
              descriptor: String
            }

            type category =
              :ACH
              | :BALANCE_OR_FUNDING
              | :FEE
              | :REWARD
              | :ADJUSTMENT
              | :DERECOGNITION
              | :DISPUTE
              | :CARD
              | :EXTERNAL_ACH
              | :EXTERNAL_CHECK
              | :EXTERNAL_TRANSFER
              | :EXTERNAL_WIRE
              | :MANAGEMENT_ADJUSTMENT
              | :MANAGEMENT_DISPUTE
              | :MANAGEMENT_FEE
              | :MANAGEMENT_REWARD
              | :MANAGEMENT_DISBURSEMENT
              | :PROGRAM_FUNDING

            module Category
              extend Lithic::Internal::Type::Enum

              ACH: :ACH
              BALANCE_OR_FUNDING: :BALANCE_OR_FUNDING
              FEE: :FEE
              REWARD: :REWARD
              ADJUSTMENT: :ADJUSTMENT
              DERECOGNITION: :DERECOGNITION
              DISPUTE: :DISPUTE
              CARD: :CARD
              EXTERNAL_ACH: :EXTERNAL_ACH
              EXTERNAL_CHECK: :EXTERNAL_CHECK
              EXTERNAL_TRANSFER: :EXTERNAL_TRANSFER
              EXTERNAL_WIRE: :EXTERNAL_WIRE
              MANAGEMENT_ADJUSTMENT: :MANAGEMENT_ADJUSTMENT
              MANAGEMENT_DISPUTE: :MANAGEMENT_DISPUTE
              MANAGEMENT_FEE: :MANAGEMENT_FEE
              MANAGEMENT_REWARD: :MANAGEMENT_REWARD
              MANAGEMENT_DISBURSEMENT: :MANAGEMENT_DISBURSEMENT
              PROGRAM_FUNDING: :PROGRAM_FUNDING

              def self?.values: -> ::Array[Lithic::Models::FinancialAccounts::Statements::StatementLineItems::Data::category]
            end

            type event_type =
              :ACH_ORIGINATION_CANCELLED
              | :ACH_ORIGINATION_INITIATED
              | :ACH_ORIGINATION_PROCESSED
              | :ACH_ORIGINATION_RELEASED
              | :ACH_ORIGINATION_REJECTED
              | :ACH_ORIGINATION_REVIEWED
              | :ACH_ORIGINATION_SETTLED
              | :ACH_RECEIPT_PROCESSED
              | :ACH_RECEIPT_SETTLED
              | :ACH_RETURN_INITIATED
              | :ACH_RETURN_PROCESSED
              | :ACH_RETURN_REJECTED
              | :ACH_RETURN_SETTLED
              | :AUTHORIZATION
              | :AUTHORIZATION_ADVICE
              | :AUTHORIZATION_EXPIRY
              | :AUTHORIZATION_REVERSAL
              | :BALANCE_INQUIRY
              | :BILLING_ERROR
              | :BILLING_ERROR_REVERSAL
              | :CARD_TO_CARD
              | :CASH_BACK
              | :CASH_BACK_REVERSAL
              | :CLEARING
              | :COLLECTION
              | :CORRECTION_CREDIT
              | :CORRECTION_DEBIT
              | :CREDIT_AUTHORIZATION
              | :CREDIT_AUTHORIZATION_ADVICE
              | :CURRENCY_CONVERSION
              | :CURRENCY_CONVERSION_REVERSAL
              | :DISPUTE_WON
              | :EXTERNAL_ACH_CANCELED
              | :EXTERNAL_ACH_INITIATED
              | :EXTERNAL_ACH_RELEASED
              | :EXTERNAL_ACH_REVERSED
              | :EXTERNAL_ACH_SETTLED
              | :EXTERNAL_CHECK_CANCELED
              | :EXTERNAL_CHECK_INITIATED
              | :EXTERNAL_CHECK_RELEASED
              | :EXTERNAL_CHECK_REVERSED
              | :EXTERNAL_CHECK_SETTLED
              | :EXTERNAL_TRANSFER_CANCELED
              | :EXTERNAL_TRANSFER_INITIATED
              | :EXTERNAL_TRANSFER_RELEASED
              | :EXTERNAL_TRANSFER_REVERSED
              | :EXTERNAL_TRANSFER_SETTLED
              | :EXTERNAL_WIRE_CANCELED
              | :EXTERNAL_WIRE_INITIATED
              | :EXTERNAL_WIRE_RELEASED
              | :EXTERNAL_WIRE_REVERSED
              | :EXTERNAL_WIRE_SETTLED
              | :FINANCIAL_AUTHORIZATION
              | :FINANCIAL_CREDIT_AUTHORIZATION
              | :INTEREST
              | :INTEREST_REVERSAL
              | :INTERNAL_ADJUSTMENT
              | :LATE_PAYMENT
              | :LATE_PAYMENT_REVERSAL
              | :LOSS_WRITE_OFF
              | :PROVISIONAL_CREDIT
              | :PROVISIONAL_CREDIT_REVERSAL
              | :SERVICE
              | :RETURN
              | :RETURN_REVERSAL
              | :TRANSFER
              | :TRANSFER_INSUFFICIENT_FUNDS
              | :RETURNED_PAYMENT
              | :RETURNED_PAYMENT_REVERSAL
              | :LITHIC_NETWORK_PAYMENT

            module EventType
              extend Lithic::Internal::Type::Enum

              ACH_ORIGINATION_CANCELLED: :ACH_ORIGINATION_CANCELLED
              ACH_ORIGINATION_INITIATED: :ACH_ORIGINATION_INITIATED
              ACH_ORIGINATION_PROCESSED: :ACH_ORIGINATION_PROCESSED
              ACH_ORIGINATION_RELEASED: :ACH_ORIGINATION_RELEASED
              ACH_ORIGINATION_REJECTED: :ACH_ORIGINATION_REJECTED
              ACH_ORIGINATION_REVIEWED: :ACH_ORIGINATION_REVIEWED
              ACH_ORIGINATION_SETTLED: :ACH_ORIGINATION_SETTLED
              ACH_RECEIPT_PROCESSED: :ACH_RECEIPT_PROCESSED
              ACH_RECEIPT_SETTLED: :ACH_RECEIPT_SETTLED
              ACH_RETURN_INITIATED: :ACH_RETURN_INITIATED
              ACH_RETURN_PROCESSED: :ACH_RETURN_PROCESSED
              ACH_RETURN_REJECTED: :ACH_RETURN_REJECTED
              ACH_RETURN_SETTLED: :ACH_RETURN_SETTLED
              AUTHORIZATION: :AUTHORIZATION
              AUTHORIZATION_ADVICE: :AUTHORIZATION_ADVICE
              AUTHORIZATION_EXPIRY: :AUTHORIZATION_EXPIRY
              AUTHORIZATION_REVERSAL: :AUTHORIZATION_REVERSAL
              BALANCE_INQUIRY: :BALANCE_INQUIRY
              BILLING_ERROR: :BILLING_ERROR
              BILLING_ERROR_REVERSAL: :BILLING_ERROR_REVERSAL
              CARD_TO_CARD: :CARD_TO_CARD
              CASH_BACK: :CASH_BACK
              CASH_BACK_REVERSAL: :CASH_BACK_REVERSAL
              CLEARING: :CLEARING
              COLLECTION: :COLLECTION
              CORRECTION_CREDIT: :CORRECTION_CREDIT
              CORRECTION_DEBIT: :CORRECTION_DEBIT
              CREDIT_AUTHORIZATION: :CREDIT_AUTHORIZATION
              CREDIT_AUTHORIZATION_ADVICE: :CREDIT_AUTHORIZATION_ADVICE
              CURRENCY_CONVERSION: :CURRENCY_CONVERSION
              CURRENCY_CONVERSION_REVERSAL: :CURRENCY_CONVERSION_REVERSAL
              DISPUTE_WON: :DISPUTE_WON
              EXTERNAL_ACH_CANCELED: :EXTERNAL_ACH_CANCELED
              EXTERNAL_ACH_INITIATED: :EXTERNAL_ACH_INITIATED
              EXTERNAL_ACH_RELEASED: :EXTERNAL_ACH_RELEASED
              EXTERNAL_ACH_REVERSED: :EXTERNAL_ACH_REVERSED
              EXTERNAL_ACH_SETTLED: :EXTERNAL_ACH_SETTLED
              EXTERNAL_CHECK_CANCELED: :EXTERNAL_CHECK_CANCELED
              EXTERNAL_CHECK_INITIATED: :EXTERNAL_CHECK_INITIATED
              EXTERNAL_CHECK_RELEASED: :EXTERNAL_CHECK_RELEASED
              EXTERNAL_CHECK_REVERSED: :EXTERNAL_CHECK_REVERSED
              EXTERNAL_CHECK_SETTLED: :EXTERNAL_CHECK_SETTLED
              EXTERNAL_TRANSFER_CANCELED: :EXTERNAL_TRANSFER_CANCELED
              EXTERNAL_TRANSFER_INITIATED: :EXTERNAL_TRANSFER_INITIATED
              EXTERNAL_TRANSFER_RELEASED: :EXTERNAL_TRANSFER_RELEASED
              EXTERNAL_TRANSFER_REVERSED: :EXTERNAL_TRANSFER_REVERSED
              EXTERNAL_TRANSFER_SETTLED: :EXTERNAL_TRANSFER_SETTLED
              EXTERNAL_WIRE_CANCELED: :EXTERNAL_WIRE_CANCELED
              EXTERNAL_WIRE_INITIATED: :EXTERNAL_WIRE_INITIATED
              EXTERNAL_WIRE_RELEASED: :EXTERNAL_WIRE_RELEASED
              EXTERNAL_WIRE_REVERSED: :EXTERNAL_WIRE_REVERSED
              EXTERNAL_WIRE_SETTLED: :EXTERNAL_WIRE_SETTLED
              FINANCIAL_AUTHORIZATION: :FINANCIAL_AUTHORIZATION
              FINANCIAL_CREDIT_AUTHORIZATION: :FINANCIAL_CREDIT_AUTHORIZATION
              INTEREST: :INTEREST
              INTEREST_REVERSAL: :INTEREST_REVERSAL
              INTERNAL_ADJUSTMENT: :INTERNAL_ADJUSTMENT
              LATE_PAYMENT: :LATE_PAYMENT
              LATE_PAYMENT_REVERSAL: :LATE_PAYMENT_REVERSAL
              LOSS_WRITE_OFF: :LOSS_WRITE_OFF
              PROVISIONAL_CREDIT: :PROVISIONAL_CREDIT
              PROVISIONAL_CREDIT_REVERSAL: :PROVISIONAL_CREDIT_REVERSAL
              SERVICE: :SERVICE
              RETURN: :RETURN
              RETURN_REVERSAL: :RETURN_REVERSAL
              TRANSFER: :TRANSFER
              TRANSFER_INSUFFICIENT_FUNDS: :TRANSFER_INSUFFICIENT_FUNDS
              RETURNED_PAYMENT: :RETURNED_PAYMENT
              RETURNED_PAYMENT_REVERSAL: :RETURNED_PAYMENT_REVERSAL
              LITHIC_NETWORK_PAYMENT: :LITHIC_NETWORK_PAYMENT

              def self?.values: -> ::Array[Lithic::Models::FinancialAccounts::Statements::StatementLineItems::Data::event_type]
            end
          end
        end
      end
    end
  end
end
