module Lithic
  module Models
    module ExternalBankAccounts
      type micro_deposit_create_params =
        { micro_deposits: ::Array[Integer] }
        & Lithic::Internal::Type::request_parameters

      class MicroDepositCreateParams < Lithic::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        attr_accessor micro_deposits: ::Array[Integer]

        def initialize: (
          micro_deposits: ::Array[Integer],
          ?request_options: Lithic::request_opts
        ) -> void

        def to_hash: -> Lithic::Models::ExternalBankAccounts::micro_deposit_create_params
      end
    end
  end
end
