module Lithic
  module Resources
    class Accounts
      def retrieve: (
        String account_token,
        ?request_options: Lithic::request_opts
      ) -> Lithic::Models::Account

      def update: (
        String account_token,
        ?daily_spend_limit: Integer,
        ?lifetime_spend_limit: Integer,
        ?monthly_spend_limit: Integer,
        ?state: Lithic::Models::AccountUpdateParams::state,
        ?verification_address: Lithic::Models::AccountUpdateParams::VerificationAddress,
        ?request_options: Lithic::request_opts
      ) -> Lithic::Models::Account

      def list: (
        ?begin_: Time,
        ?end_: Time,
        ?ending_before: String,
        ?page_size: Integer,
        ?starting_after: String,
        ?request_options: Lithic::request_opts
      ) -> Lithic::CursorPage[Lithic::Models::Account]

      def retrieve_spend_limits: (
        String account_token,
        ?request_options: Lithic::request_opts
      ) -> Lithic::Models::AccountSpendLimits

      def initialize: (client: Lithic::Client) -> void
    end
  end
end
