module Lithic
  module Resources
    class AuthStreamEnrollment
      def retrieve_secret: (
        ?request_options: Lithic::request_opts
      ) -> Lithic::AuthStreamSecret

      def rotate_secret: (?request_options: Lithic::request_opts) -> nil

      def initialize: (client: Lithic::Client) -> void
    end
  end
end
