module Lithic
  module Resources
    class TokenizationDecisioning
      def retrieve_secret: (
        ?request_options: Lithic::request_opts
      ) -> Lithic::TokenizationSecret

      def rotate_secret: (
        ?request_options: Lithic::request_opts
      ) -> Lithic::Models::TokenizationDecisioningRotateSecretResponse

      def initialize: (client: Lithic::Client) -> void
    end
  end
end
