module Lithic
  module Resources
    class Transfers
      def create: (
        amount: Integer,
        from: String,
        to: String,
        ?token: String,
        ?memo: String,
        ?request_options: Lithic::request_opts
      ) -> Lithic::Transfer

      def initialize: (client: Lithic::Client) -> void
    end
  end
end
