module Lithic
  module Resources
    class Webhooks
      def parse: (
        String payload,
        headers: Hash[String, String],
        ?secret: String?
      ) -> Lithic::Models::parsed_webhook_event

      def parse_unsafe: (String payload) -> Lithic::Models::parsed_webhook_event

      def verify_signature: (
        payload: String,
        headers: Hash[String, String],
        ?secret: String?
      ) -> Hash[Symbol, untyped]

      def initialize: (client: Lithic::Client) -> void
    end
  end
end
