module Lithic
  module Resources
    class AuthRules
      class V2
        attr_reader backtests: Lithic::Resources::AuthRules::V2::Backtests

        def create: (
          parameters: Lithic::Models::AuthRules::V2CreateParams::parameters,
          type: Lithic::Models::AuthRules::V2CreateParams::type_,
          card_tokens: ::Array[String],
          program_level: bool,
          ?account_tokens: ::Array[String],
          ?business_account_tokens: ::Array[String],
          ?event_stream: Lithic::Models::AuthRules::V2CreateParams::event_stream,
          ?name: String?,
          ?excluded_card_tokens: ::Array[String],
          ?request_options: Lithic::request_opts
        ) -> Lithic::Models::AuthRules::V2CreateResponse

        def retrieve: (
          String auth_rule_token,
          ?request_options: Lithic::request_opts
        ) -> Lithic::Models::AuthRules::V2RetrieveResponse

        def update: (
          String auth_rule_token,
          ?account_tokens: ::Array[String],
          ?business_account_tokens: ::Array[String],
          ?name: String?,
          ?state: Lithic::Models::AuthRules::V2UpdateParams::state,
          ?card_tokens: ::Array[String],
          ?excluded_card_tokens: ::Array[String],
          ?program_level: bool,
          ?request_options: Lithic::request_opts
        ) -> Lithic::Models::AuthRules::V2UpdateResponse

        def list: (
          ?account_token: String,
          ?business_account_token: String,
          ?card_token: String,
          ?ending_before: String,
          ?event_stream: Lithic::Models::AuthRules::V2ListParams::event_stream,
          ?page_size: Integer,
          ?scope: Lithic::Models::AuthRules::V2ListParams::scope,
          ?starting_after: String,
          ?request_options: Lithic::request_opts
        ) -> Lithic::Internal::CursorPage[Lithic::Models::AuthRules::V2ListResponse]

        def delete: (
          String auth_rule_token,
          ?request_options: Lithic::request_opts
        ) -> nil

        def draft: (
          String auth_rule_token,
          ?parameters: Lithic::Models::AuthRules::V2DraftParams::parameters?,
          ?request_options: Lithic::request_opts
        ) -> Lithic::Models::AuthRules::V2DraftResponse

        def promote: (
          String auth_rule_token,
          ?request_options: Lithic::request_opts
        ) -> Lithic::Models::AuthRules::V2PromoteResponse

        def retrieve_features: (
          String auth_rule_token,
          ?account_token: String,
          ?card_token: String,
          ?request_options: Lithic::request_opts
        ) -> Lithic::Models::AuthRules::V2RetrieveFeaturesResponse

        def retrieve_report: (
          String auth_rule_token,
          begin_: Date,
          end_: Date,
          ?request_options: Lithic::request_opts
        ) -> Lithic::Models::AuthRules::V2RetrieveReportResponse

        def initialize: (client: Lithic::Client) -> void
      end
    end
  end
end
