module Lithic
  module Resources
    class AuthRules
      class V2
        attr_reader backtests: Lithic::Resources::AuthRules::V2::Backtests

        def create: (
          body: Lithic::Models::AuthRules::V2CreateParams::body,
          ?request_options: Lithic::request_opts
        ) -> Lithic::AuthRules::AuthRule

        def retrieve: (
          String auth_rule_token,
          ?request_options: Lithic::request_opts
        ) -> Lithic::AuthRules::AuthRule

        def update: (
          String auth_rule_token,
          body: Lithic::Models::AuthRules::V2UpdateParams::body,
          ?request_options: Lithic::request_opts
        ) -> Lithic::AuthRules::AuthRule

        def list: (
          ?account_token: String,
          ?business_account_token: String,
          ?card_token: String,
          ?ending_before: String,
          ?event_stream: Lithic::Models::AuthRules::event_stream,
          ?event_streams: ::Array[Lithic::Models::AuthRules::event_stream],
          ?page_size: Integer,
          ?scope: Lithic::Models::AuthRules::V2ListParams::scope,
          ?starting_after: String,
          ?request_options: Lithic::request_opts
        ) -> Lithic::Internal::CursorPage[Lithic::AuthRules::AuthRule]

        def delete: (
          String auth_rule_token,
          ?request_options: Lithic::request_opts
        ) -> nil

        def draft: (
          String auth_rule_token,
          ?parameters: Lithic::Models::AuthRules::V2DraftParams::parameters?,
          ?request_options: Lithic::request_opts
        ) -> Lithic::AuthRules::AuthRule

        def list_results: (
          ?auth_rule_token: String,
          ?begin_: Time,
          ?end_: Time,
          ?ending_before: String,
          ?event_token: String,
          ?has_actions: bool,
          ?page_size: Integer,
          ?starting_after: String,
          ?request_options: Lithic::request_opts
        ) -> Lithic::Internal::CursorPage[Lithic::Models::AuthRules::v2_list_results_response]

        def promote: (
          String auth_rule_token,
          ?request_options: Lithic::request_opts
        ) -> Lithic::AuthRules::AuthRule

        def retrieve_features: (
          String auth_rule_token,
          ?account_token: String,
          ?card_token: String,
          ?request_options: Lithic::request_opts
        ) -> Lithic::Models::AuthRules::V2RetrieveFeaturesResponse

        def retrieve_report: (
          String auth_rule_token,
          begin_: Date,
          end_: Date,
          ?request_options: Lithic::request_opts
        ) -> Lithic::Models::AuthRules::V2RetrieveReportResponse

        def initialize: (client: Lithic::Client) -> void
      end
    end
  end
end
