module Lithic
  module Resources
    class Transactions
      class Events
        class EnhancedCommercialData
          def retrieve: (
            String event_token,
            ?request_options: Lithic::request_opts
          ) -> Lithic::Transactions::Events::EnhancedData

          def initialize: (client: Lithic::Client) -> void
        end
      end
    end
  end
end
