module Lithic
  module Resources
    class AuthRules
      class V2
        class Backtests
          def create: (
            String auth_rule_token,
            ?end_: Time,
            ?start: Time,
            ?request_options: Lithic::request_opts
          ) -> Lithic::Models::AuthRules::V2::BacktestCreateResponse

          def retrieve: (
            String auth_rule_backtest_token,
            auth_rule_token: String,
            ?request_options: Lithic::request_opts
          ) -> Lithic::AuthRules::V2::BacktestResults

          def initialize: (client: Lithic::Client) -> void
        end
      end
    end
  end
end
