module Lithic
  module Resources
    class FinancialAccounts
      class Balances
        def list: (
          String financial_account_token,
          ?balance_date: Time,
          ?last_transaction_event_token: String,
          ?request_options: Lithic::request_opts
        ) -> Lithic::Internal::SinglePage[Lithic::Models::FinancialAccounts::BalanceListResponse]

        def initialize: (client: Lithic::Client) -> void
      end
    end
  end
end
