module Lithic
  module Resources
    class FinancialAccounts
      class CreditConfiguration
        def retrieve: (
          String financial_account_token,
          ?request_options: Lithic::request_opts
        ) -> Lithic::FinancialAccounts::FinancialAccountCreditConfig

        def update: (
          String financial_account_token,
          ?auto_collection_configuration: Lithic::FinancialAccounts::CreditConfigurationUpdateParams::AutoCollectionConfiguration,
          ?credit_limit: Integer,
          ?credit_product_token: String,
          ?external_bank_account_token: String,
          ?tier: String,
          ?request_options: Lithic::request_opts
        ) -> Lithic::FinancialAccounts::FinancialAccountCreditConfig

        def initialize: (client: Lithic::Client) -> void
      end
    end
  end
end
