module Lithic
  module Resources
    class FinancialAccounts
      class InstallmentPlans
        def retrieve: (
          String installment_plan_token,
          financial_account_token: String,
          ?request_options: Lithic::request_opts
        ) -> Lithic::FinancialAccounts::InstallmentPlan

        def list: (
          String financial_account_token,
          ?ending_before: String,
          ?page_size: Integer,
          ?starting_after: String,
          ?state: Lithic::Models::FinancialAccounts::InstallmentPlanListParams::state?,
          ?request_options: Lithic::request_opts
        ) -> Lithic::Internal::CursorPage[Lithic::FinancialAccounts::InstallmentPlan]

        def initialize: (client: Lithic::Client) -> void
      end
    end
  end
end
