module Lithic
  module Resources
    class FinancialAccounts
      class LoanTapes
        def retrieve: (
          String loan_tape_token,
          financial_account_token: String,
          ?request_options: Lithic::request_opts
        ) -> Lithic::Models::FinancialAccounts::LoanTape

        def list: (
          String financial_account_token,
          ?begin_: Date,
          ?end_: Date,
          ?ending_before: String,
          ?page_size: Integer,
          ?starting_after: String,
          ?request_options: Lithic::request_opts
        ) -> Lithic::Internal::CursorPage[Lithic::Models::FinancialAccounts::LoanTape]

        def initialize: (client: Lithic::Client) -> void
      end
    end
  end
end
