module Lithic
  module Resources
    class Cards
      class AggregateBalances
        def list: (
          ?account_token: String,
          ?business_account_token: String,
          ?request_options: Lithic::request_opts
        ) -> Lithic::SinglePage[Lithic::Models::Cards::AggregateBalanceListResponse]

        def initialize: (client: Lithic::Client) -> void
      end
    end
  end
end
