module Lithic
  module Models
    module Events
      type subscription_recover_params =
        { begin_: Time, end_: Time }
        & Lithic::Internal::Type::request_parameters

      class SubscriptionRecoverParams < Lithic::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        attr_reader begin_: Time?

        def begin_=: (Time) -> Time

        attr_reader end_: Time?

        def end_=: (Time) -> Time

        def initialize: (
          ?begin_: Time,
          ?end_: Time,
          ?request_options: Lithic::request_opts
        ) -> void

        def to_hash: -> Lithic::Models::Events::subscription_recover_params
      end
    end
  end
end
