module Lithic
  module Models
    module Events
      type subscription_rotate_secret_params =
        { event_subscription_token: String }
        & Lithic::Internal::Type::request_parameters

      class SubscriptionRotateSecretParams < Lithic::Internal::Type::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        attr_accessor event_subscription_token: String

        def initialize: (
          event_subscription_token: String,
          ?request_options: Lithic::request_opts
        ) -> void

        def to_hash: -> {
          event_subscription_token: String,
          request_options: Lithic::RequestOptions
        }
      end
    end
  end
end
