module Lithic
  module Models
    module Events
      type subscription_retrieve_params = {  } & Lithic::request_parameters

      class SubscriptionRetrieveParams < Lithic::BaseModel
        extend Lithic::Type::RequestParameters::Converter
        include Lithic::RequestParameters

        def initialize: (?request_options: Lithic::request_opts) -> void

        def to_hash: -> Lithic::Models::Events::subscription_retrieve_params
      end
    end
  end
end
