module Lithic
  module Models
    module Events
      type subscription_retrieve_secret_response = { secret: String }

      class SubscriptionRetrieveSecretResponse < Lithic::Internal::Type::BaseModel
        attr_reader secret: String?

        def secret=: (String) -> String

        def initialize: (?secret: String) -> void
      end
    end
  end
end
