module Lithic
  module Models
    module Cards
      type balance_list_response =
        {
          token: String,
          available_amount: Integer,
          created: Time,
          currency: String,
          last_transaction_event_token: String,
          last_transaction_token: String,
          pending_amount: Integer,
          total_amount: Integer,
          type: Lithic::Models::Cards::BalanceListResponse::type_,
          updated: Time
        }

      class BalanceListResponse < Lithic::Internal::Type::BaseModel
        attr_accessor token: String

        attr_accessor available_amount: Integer

        attr_accessor created: Time

        attr_accessor currency: String

        attr_accessor last_transaction_event_token: String

        attr_accessor last_transaction_token: String

        attr_accessor pending_amount: Integer

        attr_accessor total_amount: Integer

        attr_accessor type: Lithic::Models::Cards::BalanceListResponse::type_

        attr_accessor updated: Time

        def initialize: (
          token: String,
          available_amount: Integer,
          created: Time,
          currency: String,
          last_transaction_event_token: String,
          last_transaction_token: String,
          pending_amount: Integer,
          total_amount: Integer,
          type: Lithic::Models::Cards::BalanceListResponse::type_,
          updated: Time
        ) -> void

        def to_hash: -> {
          token: String,
          available_amount: Integer,
          created: Time,
          currency: String,
          last_transaction_event_token: String,
          last_transaction_token: String,
          pending_amount: Integer,
          total_amount: Integer,
          type: Lithic::Models::Cards::BalanceListResponse::type_,
          updated: Time
        }

        type type_ = :ISSUING | :OPERATING | :RESERVE

        module Type
          extend Lithic::Internal::Type::Enum

          ISSUING: :ISSUING
          OPERATING: :OPERATING
          RESERVE: :RESERVE

          def self?.values: -> ::Array[Lithic::Models::Cards::BalanceListResponse::type_]
        end
      end
    end
  end
end
