module Lithic
  module Models
    module Cards
      type balance_list_params =
        { balance_date: Time, last_transaction_event_token: String }
        & Lithic::Internal::Type::request_parameters

      class BalanceListParams < Lithic::Internal::Type::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        attr_reader balance_date: Time?

        def balance_date=: (Time) -> Time

        attr_reader last_transaction_event_token: String?

        def last_transaction_event_token=: (String) -> String

        def initialize: (
          ?balance_date: Time,
          ?last_transaction_event_token: String,
          ?request_options: Lithic::request_opts
        ) -> void
      end
    end
  end
end
