module Lithic
  module Models
    module Cards
      type financial_transaction_retrieve_params =
        { card_token: String } & Lithic::Internal::Type::request_parameters

      class FinancialTransactionRetrieveParams < Lithic::Internal::Type::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        attr_accessor card_token: String

        def initialize: (
          card_token: String,
          ?request_options: Lithic::request_opts
        ) -> void
      end
    end
  end
end
