module Lithic
  module Models
    module TransactionMonitoring
      module Cases
        type file_delete_params =
          { case_token: String, file_token: String }
          & Lithic::Internal::Type::request_parameters

        class FileDeleteParams < Lithic::Internal::Type::BaseModel
          extend Lithic::Internal::Type::RequestParameters::Converter
          include Lithic::Internal::Type::RequestParameters

          attr_accessor case_token: String

          attr_accessor file_token: String

          def initialize: (
            case_token: String,
            file_token: String,
            ?request_options: Lithic::request_opts
          ) -> void

          def to_hash: -> {
            case_token: String,
            file_token: String,
            request_options: Lithic::RequestOptions
          }
        end
      end
    end
  end
end
