module Lithic
  module Models
    type account_holder_update_params =
      { business_account_token: String, email: String, phone_number: String }
      & Lithic::request_parameters

    class AccountHolderUpdateParams < Lithic::BaseModel
      extend Lithic::RequestParameters::Converter
      include Lithic::RequestParameters

      attr_reader business_account_token: String?

      def business_account_token=: (String) -> String

      attr_reader email: String?

      def email=: (String) -> String

      attr_reader phone_number: String?

      def phone_number=: (String) -> String

      def initialize: (
        ?business_account_token: String,
        ?email: String,
        ?phone_number: String,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> Lithic::Models::account_holder_update_params
    end
  end
end
