module Lithic
  module Models
    type account_holder_upload_document_params =
      {
        document_type: Lithic::Models::AccountHolderUploadDocumentParams::document_type,
        entity_token: String
      }
      & Lithic::Internal::Type::request_parameters

    class AccountHolderUploadDocumentParams < Lithic::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_accessor document_type: Lithic::Models::AccountHolderUploadDocumentParams::document_type

      attr_accessor entity_token: String

      def initialize: (
        document_type: Lithic::Models::AccountHolderUploadDocumentParams::document_type,
        entity_token: String,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> Lithic::Models::account_holder_upload_document_params

      type document_type =
        :EIN_LETTER
        | :TAX_RETURN
        | :OPERATING_AGREEMENT
        | :CERTIFICATE_OF_FORMATION
        | :DRIVERS_LICENSE
        | :PASSPORT
        | :PASSPORT_CARD
        | :CERTIFICATE_OF_GOOD_STANDING
        | :ARTICLES_OF_INCORPORATION
        | :ARTICLES_OF_ORGANIZATION
        | :BYLAWS
        | :GOVERNMENT_BUSINESS_LICENSE
        | :PARTNERSHIP_AGREEMENT
        | :SS4_FORM
        | :BANK_STATEMENT
        | :UTILITY_BILL_STATEMENT
        | :SSN_CARD
        | :ITIN_LETTER
        | :FINCEN_BOI_REPORT

      module DocumentType
        extend Lithic::Enum

        EIN_LETTER: :EIN_LETTER
        TAX_RETURN: :TAX_RETURN
        OPERATING_AGREEMENT: :OPERATING_AGREEMENT
        CERTIFICATE_OF_FORMATION: :CERTIFICATE_OF_FORMATION
        DRIVERS_LICENSE: :DRIVERS_LICENSE
        PASSPORT: :PASSPORT
        PASSPORT_CARD: :PASSPORT_CARD
        CERTIFICATE_OF_GOOD_STANDING: :CERTIFICATE_OF_GOOD_STANDING
        ARTICLES_OF_INCORPORATION: :ARTICLES_OF_INCORPORATION
        ARTICLES_OF_ORGANIZATION: :ARTICLES_OF_ORGANIZATION
        BYLAWS: :BYLAWS
        GOVERNMENT_BUSINESS_LICENSE: :GOVERNMENT_BUSINESS_LICENSE
        PARTNERSHIP_AGREEMENT: :PARTNERSHIP_AGREEMENT
        SS4_FORM: :SS4_FORM
        BANK_STATEMENT: :BANK_STATEMENT
        UTILITY_BILL_STATEMENT: :UTILITY_BILL_STATEMENT
        SSN_CARD: :SSN_CARD
        ITIN_LETTER: :ITIN_LETTER
        FINCEN_BOI_REPORT: :FINCEN_BOI_REPORT

        def self?.values: -> ::Array[Lithic::Models::AccountHolderUploadDocumentParams::document_type]
      end
    end
  end
end
