module Lithic
  module Models
    type account_holder_retrieve_document_params =
      { account_holder_token: String }
      & Lithic::Internal::Type::request_parameters

    class AccountHolderRetrieveDocumentParams < Lithic::Internal::Type::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_accessor account_holder_token: String

      def initialize: (
        account_holder_token: String,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> {
        account_holder_token: String,
        request_options: Lithic::RequestOptions
      }
    end
  end
end
