module Lithic
  module Models
    type account_holder_retrieve_document_params =
      { account_holder_token: String } & Lithic::request_parameters

    class AccountHolderRetrieveDocumentParams < Lithic::BaseModel
      extend Lithic::RequestParameters::Converter
      include Lithic::RequestParameters

      attr_accessor account_holder_token: String

      def initialize: (
        account_holder_token: String,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> Lithic::Models::account_holder_retrieve_document_params
    end
  end
end
