module Lithic
  module Models
    type account_holder_list_documents_response =
      { data: ::Array[Lithic::Document] }

    class AccountHolderListDocumentsResponse < Lithic::Internal::Type::BaseModel
      attr_reader data: ::Array[Lithic::Document]?

      def data=: (::Array[Lithic::Document]) -> ::Array[Lithic::Document]

      def initialize: (?data: ::Array[Lithic::Document]) -> void

      def to_hash: -> { data: ::Array[Lithic::Document] }
    end
  end
end
