module Lithic
  module Models
    type account_financial_account_type = :ISSUING | :OPERATING

    module AccountFinancialAccountType
      extend Lithic::Enum

      ISSUING: :ISSUING
      OPERATING: :OPERATING

      def self.values: -> ::Array[Lithic::Models::account_financial_account_type]
    end
  end
end
