module Lithic
  module Models
    type account_activity_list_response =
      Lithic::Models::AccountActivityListResponse::Internal
      | Lithic::BookTransferResponse
      | Lithic::Models::AccountActivityListResponse::Card
      | Lithic::Payment
      | Lithic::ExternalPayment
      | Lithic::ManagementOperationTransaction

    module AccountActivityListResponse
      extend Lithic::Internal::Type::Union

      type internal =
        {
          token: String,
          category: Lithic::Models::AccountActivityListResponse::Internal::category,
          created: Time,
          currency: String,
          descriptor: String,
          events: ::Array[Lithic::FinancialEvent],
          family: :INTERNAL,
          financial_account_token: String,
          pending_amount: Integer,
          result: Lithic::Models::AccountActivityListResponse::Internal::result,
          settled_amount: Integer,
          status: Lithic::Models::AccountActivityListResponse::Internal::status,
          updated: Time
        }

      class Internal < Lithic::Internal::Type::BaseModel
        attr_accessor token: String

        attr_accessor category: Lithic::Models::AccountActivityListResponse::Internal::category

        attr_accessor created: Time

        attr_accessor currency: String

        attr_accessor descriptor: String

        attr_accessor events: ::Array[Lithic::FinancialEvent]

        attr_accessor family: :INTERNAL

        attr_accessor financial_account_token: String

        attr_accessor pending_amount: Integer

        attr_accessor result: Lithic::Models::AccountActivityListResponse::Internal::result

        attr_accessor settled_amount: Integer

        attr_accessor status: Lithic::Models::AccountActivityListResponse::Internal::status

        attr_accessor updated: Time

        def initialize: (
          token: String,
          category: Lithic::Models::AccountActivityListResponse::Internal::category,
          created: Time,
          currency: String,
          descriptor: String,
          events: ::Array[Lithic::FinancialEvent],
          financial_account_token: String,
          pending_amount: Integer,
          result: Lithic::Models::AccountActivityListResponse::Internal::result,
          settled_amount: Integer,
          status: Lithic::Models::AccountActivityListResponse::Internal::status,
          updated: Time,
          ?family: :INTERNAL
        ) -> void

        def to_hash: -> {
          token: String,
          category: Lithic::Models::AccountActivityListResponse::Internal::category,
          created: Time,
          currency: String,
          descriptor: String,
          events: ::Array[Lithic::FinancialEvent],
          family: :INTERNAL,
          financial_account_token: String,
          pending_amount: Integer,
          result: Lithic::Models::AccountActivityListResponse::Internal::result,
          settled_amount: Integer,
          status: Lithic::Models::AccountActivityListResponse::Internal::status,
          updated: Time
        }

        type category =
          :ACH
          | :BALANCE_OR_FUNDING
          | :FEE
          | :REWARD
          | :ADJUSTMENT
          | :DERECOGNITION
          | :DISPUTE
          | :CARD
          | :EXTERNAL_ACH
          | :EXTERNAL_CHECK
          | :EXTERNAL_FEDNOW
          | :EXTERNAL_RTP
          | :EXTERNAL_TRANSFER
          | :EXTERNAL_WIRE
          | :MANAGEMENT_ADJUSTMENT
          | :MANAGEMENT_DISPUTE
          | :MANAGEMENT_FEE
          | :MANAGEMENT_REWARD
          | :MANAGEMENT_DISBURSEMENT
          | :PROGRAM_FUNDING

        module Category
          extend Lithic::Internal::Type::Enum

          ACH: :ACH
          BALANCE_OR_FUNDING: :BALANCE_OR_FUNDING
          FEE: :FEE
          REWARD: :REWARD
          ADJUSTMENT: :ADJUSTMENT
          DERECOGNITION: :DERECOGNITION
          DISPUTE: :DISPUTE
          CARD: :CARD
          EXTERNAL_ACH: :EXTERNAL_ACH
          EXTERNAL_CHECK: :EXTERNAL_CHECK
          EXTERNAL_FEDNOW: :EXTERNAL_FEDNOW
          EXTERNAL_RTP: :EXTERNAL_RTP
          EXTERNAL_TRANSFER: :EXTERNAL_TRANSFER
          EXTERNAL_WIRE: :EXTERNAL_WIRE
          MANAGEMENT_ADJUSTMENT: :MANAGEMENT_ADJUSTMENT
          MANAGEMENT_DISPUTE: :MANAGEMENT_DISPUTE
          MANAGEMENT_FEE: :MANAGEMENT_FEE
          MANAGEMENT_REWARD: :MANAGEMENT_REWARD
          MANAGEMENT_DISBURSEMENT: :MANAGEMENT_DISBURSEMENT
          PROGRAM_FUNDING: :PROGRAM_FUNDING

          def self?.values: -> ::Array[Lithic::Models::AccountActivityListResponse::Internal::category]
        end

        type result = :APPROVED | :DECLINED

        module Result
          extend Lithic::Internal::Type::Enum

          APPROVED: :APPROVED
          DECLINED: :DECLINED

          def self?.values: -> ::Array[Lithic::Models::AccountActivityListResponse::Internal::result]
        end

        type status =
          :PENDING | :SETTLED | :DECLINED | :REVERSED | :CANCELED | :RETURNED

        module Status
          extend Lithic::Internal::Type::Enum

          PENDING: :PENDING
          SETTLED: :SETTLED
          DECLINED: :DECLINED
          REVERSED: :REVERSED
          CANCELED: :CANCELED
          RETURNED: :RETURNED

          def self?.values: -> ::Array[Lithic::Models::AccountActivityListResponse::Internal::status]
        end
      end

      type card =
        {
          token: String,
          created: Time,
          family: :CARD,
          status: Lithic::Models::AccountActivityListResponse::Card::status,
          updated: Time
        }

      class Card < Lithic::Models::Transaction
        def token: -> String

        def token=: (String _) -> String

        def created: -> Time

        def created=: (Time _) -> Time

        def family: -> :CARD

        def family=: (:CARD _) -> :CARD

        def status: -> Lithic::Models::AccountActivityListResponse::Card::status

        def status=: (
          Lithic::Models::AccountActivityListResponse::Card::status _
        ) -> Lithic::Models::AccountActivityListResponse::Card::status

        def updated: -> Time

        def updated=: (Time _) -> Time

        def initialize: (
          token: String,
          created: Time,
          status: Lithic::Models::AccountActivityListResponse::Card::status,
          updated: Time,
          ?family: :CARD
        ) -> void

        def to_hash: -> {
          token: String,
          created: Time,
          family: :CARD,
          status: Lithic::Models::AccountActivityListResponse::Card::status,
          updated: Time
        }

        type status =
          :PENDING | :SETTLED | :DECLINED | :REVERSED | :CANCELED | :RETURNED

        module Status
          extend Lithic::Internal::Type::Enum

          PENDING: :PENDING
          SETTLED: :SETTLED
          DECLINED: :DECLINED
          REVERSED: :REVERSED
          CANCELED: :CANCELED
          RETURNED: :RETURNED

          def self?.values: -> ::Array[Lithic::Models::AccountActivityListResponse::Card::status]
        end
      end

      def self?.variants: -> ::Array[Lithic::Models::account_activity_list_response]
    end
  end
end
