module Lithic
  module Models
    type account_holder_create_params =
      { body: Lithic::Models::AccountHolderCreateParams::body }
      & Lithic::Internal::Type::request_parameters

    class AccountHolderCreateParams < Lithic::Internal::Type::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_accessor body: Lithic::Models::AccountHolderCreateParams::body

      def initialize: (
        body: Lithic::Models::AccountHolderCreateParams::body,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> {
        body: Lithic::Models::AccountHolderCreateParams::body,
        request_options: Lithic::RequestOptions
      }

      type body =
        Lithic::KYB
        | Lithic::AccountHolderCreateParams::Body::KYBDelegated
        | Lithic::KYC
        | Lithic::KYCExempt

      module Body
        extend Lithic::Internal::Type::Union

        type kyb_delegated =
          {
            business_entity: Lithic::AccountHolderCreateParams::Body::KYBDelegated::BusinessEntity,
            beneficial_owner_individuals: ::Array[Lithic::AccountHolderCreateParams::Body::KYBDelegated::BeneficialOwnerIndividual],
            control_person: Lithic::AccountHolderCreateParams::Body::KYBDelegated::ControlPerson,
            external_id: String,
            naics_code: String,
            nature_of_business: String,
            tos_timestamp: String,
            website_url: String,
            workflow: Lithic::Models::AccountHolderCreateParams::Body::KYBDelegated::workflow
          }

        class KYBDelegated < Lithic::Internal::Type::BaseModel
          attr_accessor business_entity: Lithic::AccountHolderCreateParams::Body::KYBDelegated::BusinessEntity

          attr_reader beneficial_owner_individuals: ::Array[Lithic::AccountHolderCreateParams::Body::KYBDelegated::BeneficialOwnerIndividual]?

          def beneficial_owner_individuals=: (
            ::Array[Lithic::AccountHolderCreateParams::Body::KYBDelegated::BeneficialOwnerIndividual]
          ) -> ::Array[Lithic::AccountHolderCreateParams::Body::KYBDelegated::BeneficialOwnerIndividual]

          attr_reader control_person: Lithic::AccountHolderCreateParams::Body::KYBDelegated::ControlPerson?

          def control_person=: (
            Lithic::AccountHolderCreateParams::Body::KYBDelegated::ControlPerson
          ) -> Lithic::AccountHolderCreateParams::Body::KYBDelegated::ControlPerson

          attr_reader external_id: String?

          def external_id=: (String) -> String

          attr_reader naics_code: String?

          def naics_code=: (String) -> String

          attr_reader nature_of_business: String?

          def nature_of_business=: (String) -> String

          attr_reader tos_timestamp: String?

          def tos_timestamp=: (String) -> String

          attr_reader website_url: String?

          def website_url=: (String) -> String

          attr_reader workflow: Lithic::Models::AccountHolderCreateParams::Body::KYBDelegated::workflow?

          def workflow=: (
            Lithic::Models::AccountHolderCreateParams::Body::KYBDelegated::workflow
          ) -> Lithic::Models::AccountHolderCreateParams::Body::KYBDelegated::workflow

          def initialize: (
            business_entity: Lithic::AccountHolderCreateParams::Body::KYBDelegated::BusinessEntity,
            ?beneficial_owner_individuals: ::Array[Lithic::AccountHolderCreateParams::Body::KYBDelegated::BeneficialOwnerIndividual],
            ?control_person: Lithic::AccountHolderCreateParams::Body::KYBDelegated::ControlPerson,
            ?external_id: String,
            ?naics_code: String,
            ?nature_of_business: String,
            ?tos_timestamp: String,
            ?website_url: String,
            ?workflow: Lithic::Models::AccountHolderCreateParams::Body::KYBDelegated::workflow
          ) -> void

          def to_hash: -> {
            business_entity: Lithic::AccountHolderCreateParams::Body::KYBDelegated::BusinessEntity,
            beneficial_owner_individuals: ::Array[Lithic::AccountHolderCreateParams::Body::KYBDelegated::BeneficialOwnerIndividual],
            control_person: Lithic::AccountHolderCreateParams::Body::KYBDelegated::ControlPerson,
            external_id: String,
            naics_code: String,
            nature_of_business: String,
            tos_timestamp: String,
            website_url: String,
            workflow: Lithic::Models::AccountHolderCreateParams::Body::KYBDelegated::workflow
          }

          type business_entity =
            {
              address: Lithic::Address,
              legal_business_name: String,
              dba_business_name: String,
              government_id: String,
              parent_company: String,
              phone_numbers: ::Array[String]
            }

          class BusinessEntity < Lithic::Internal::Type::BaseModel
            attr_accessor address: Lithic::Address

            attr_accessor legal_business_name: String

            attr_reader dba_business_name: String?

            def dba_business_name=: (String) -> String

            attr_reader government_id: String?

            def government_id=: (String) -> String

            attr_reader parent_company: String?

            def parent_company=: (String) -> String

            attr_reader phone_numbers: ::Array[String]?

            def phone_numbers=: (::Array[String]) -> ::Array[String]

            def initialize: (
              address: Lithic::Address,
              legal_business_name: String,
              ?dba_business_name: String,
              ?government_id: String,
              ?parent_company: String,
              ?phone_numbers: ::Array[String]
            ) -> void

            def to_hash: -> {
              address: Lithic::Address,
              legal_business_name: String,
              dba_business_name: String,
              government_id: String,
              parent_company: String,
              phone_numbers: ::Array[String]
            }
          end

          type beneficial_owner_individual =
            {
              first_name: String,
              last_name: String,
              address: Lithic::Address,
              dob: String,
              email: String,
              government_id: String,
              phone_number: String
            }

          class BeneficialOwnerIndividual < Lithic::Internal::Type::BaseModel
            attr_accessor first_name: String

            attr_accessor last_name: String

            attr_reader address: Lithic::Address?

            def address=: (Lithic::Address) -> Lithic::Address

            attr_reader dob: String?

            def dob=: (String) -> String

            attr_reader email: String?

            def email=: (String) -> String

            attr_reader government_id: String?

            def government_id=: (String) -> String

            attr_reader phone_number: String?

            def phone_number=: (String) -> String

            def initialize: (
              first_name: String,
              last_name: String,
              ?address: Lithic::Address,
              ?dob: String,
              ?email: String,
              ?government_id: String,
              ?phone_number: String
            ) -> void

            def to_hash: -> {
              first_name: String,
              last_name: String,
              address: Lithic::Address,
              dob: String,
              email: String,
              government_id: String,
              phone_number: String
            }
          end

          type control_person =
            {
              first_name: String,
              last_name: String,
              address: Lithic::Address,
              dob: String,
              email: String,
              government_id: String,
              phone_number: String
            }

          class ControlPerson < Lithic::Internal::Type::BaseModel
            attr_accessor first_name: String

            attr_accessor last_name: String

            attr_reader address: Lithic::Address?

            def address=: (Lithic::Address) -> Lithic::Address

            attr_reader dob: String?

            def dob=: (String) -> String

            attr_reader email: String?

            def email=: (String) -> String

            attr_reader government_id: String?

            def government_id=: (String) -> String

            attr_reader phone_number: String?

            def phone_number=: (String) -> String

            def initialize: (
              first_name: String,
              last_name: String,
              ?address: Lithic::Address,
              ?dob: String,
              ?email: String,
              ?government_id: String,
              ?phone_number: String
            ) -> void

            def to_hash: -> {
              first_name: String,
              last_name: String,
              address: Lithic::Address,
              dob: String,
              email: String,
              government_id: String,
              phone_number: String
            }
          end

          type workflow = :KYB_DELEGATED

          module Workflow
            extend Lithic::Internal::Type::Enum

            KYB_DELEGATED: :KYB_DELEGATED

            def self?.values: -> ::Array[Lithic::Models::AccountHolderCreateParams::Body::KYBDelegated::workflow]
          end
        end

        def self?.variants: -> ::Array[Lithic::Models::AccountHolderCreateParams::body]
      end
    end
  end
end
