module Lithic
  module Models
    type account_activity_list_response =
      Lithic::Models::AccountActivityListResponse::Internal
      | Lithic::BookTransferResponse
      | Lithic::Models::AccountActivityListResponse::Card
      | Lithic::Payment
      | Lithic::ExternalPayment
      | Lithic::ManagementOperationTransaction

    module AccountActivityListResponse
      extend Lithic::Internal::Type::Union

      type internal =
        {
          token: String,
          category: Lithic::Models::AccountActivityListResponse::Internal::category,
          created: Time,
          currency: String,
          descriptor: String,
          events: ::Array[Lithic::Models::AccountActivityListResponse::Internal::Event],
          family: :INTERNAL,
          financial_account_token: String,
          pending_amount: Integer,
          result: Lithic::Models::AccountActivityListResponse::Internal::result,
          settled_amount: Integer,
          status: Lithic::Models::AccountActivityListResponse::Internal::status,
          updated: Time
        }

      class Internal < Lithic::Internal::Type::BaseModel
        attr_accessor token: String

        attr_accessor category: Lithic::Models::AccountActivityListResponse::Internal::category

        attr_accessor created: Time

        attr_accessor currency: String

        attr_accessor descriptor: String

        attr_accessor events: ::Array[Lithic::Models::AccountActivityListResponse::Internal::Event]

        attr_accessor family: :INTERNAL

        attr_accessor financial_account_token: String

        attr_accessor pending_amount: Integer

        attr_accessor result: Lithic::Models::AccountActivityListResponse::Internal::result

        attr_accessor settled_amount: Integer

        attr_accessor status: Lithic::Models::AccountActivityListResponse::Internal::status

        attr_accessor updated: Time

        def initialize: (
          token: String,
          category: Lithic::Models::AccountActivityListResponse::Internal::category,
          created: Time,
          currency: String,
          descriptor: String,
          events: ::Array[Lithic::Models::AccountActivityListResponse::Internal::Event],
          financial_account_token: String,
          pending_amount: Integer,
          result: Lithic::Models::AccountActivityListResponse::Internal::result,
          settled_amount: Integer,
          status: Lithic::Models::AccountActivityListResponse::Internal::status,
          updated: Time,
          ?family: :INTERNAL
        ) -> void

        def to_hash: -> {
          token: String,
          category: Lithic::Models::AccountActivityListResponse::Internal::category,
          created: Time,
          currency: String,
          descriptor: String,
          events: ::Array[Lithic::Models::AccountActivityListResponse::Internal::Event],
          family: :INTERNAL,
          financial_account_token: String,
          pending_amount: Integer,
          result: Lithic::Models::AccountActivityListResponse::Internal::result,
          settled_amount: Integer,
          status: Lithic::Models::AccountActivityListResponse::Internal::status,
          updated: Time
        }

        type category =
          :ACH
          | :BALANCE_OR_FUNDING
          | :FEE
          | :REWARD
          | :ADJUSTMENT
          | :DERECOGNITION
          | :DISPUTE
          | :CARD
          | :EXTERNAL_ACH
          | :EXTERNAL_CHECK
          | :EXTERNAL_TRANSFER
          | :EXTERNAL_WIRE
          | :MANAGEMENT_ADJUSTMENT
          | :MANAGEMENT_DISPUTE
          | :MANAGEMENT_FEE
          | :MANAGEMENT_REWARD
          | :MANAGEMENT_DISBURSEMENT
          | :PROGRAM_FUNDING

        module Category
          extend Lithic::Internal::Type::Enum

          ACH: :ACH
          BALANCE_OR_FUNDING: :BALANCE_OR_FUNDING
          FEE: :FEE
          REWARD: :REWARD
          ADJUSTMENT: :ADJUSTMENT
          DERECOGNITION: :DERECOGNITION
          DISPUTE: :DISPUTE
          CARD: :CARD
          EXTERNAL_ACH: :EXTERNAL_ACH
          EXTERNAL_CHECK: :EXTERNAL_CHECK
          EXTERNAL_TRANSFER: :EXTERNAL_TRANSFER
          EXTERNAL_WIRE: :EXTERNAL_WIRE
          MANAGEMENT_ADJUSTMENT: :MANAGEMENT_ADJUSTMENT
          MANAGEMENT_DISPUTE: :MANAGEMENT_DISPUTE
          MANAGEMENT_FEE: :MANAGEMENT_FEE
          MANAGEMENT_REWARD: :MANAGEMENT_REWARD
          MANAGEMENT_DISBURSEMENT: :MANAGEMENT_DISBURSEMENT
          PROGRAM_FUNDING: :PROGRAM_FUNDING

          def self?.values: -> ::Array[Lithic::Models::AccountActivityListResponse::Internal::category]
        end

        type event =
          {
            token: String,
            amount: Integer,
            created: Time,
            result: Lithic::Models::AccountActivityListResponse::Internal::Event::result,
            type: Lithic::Models::AccountActivityListResponse::Internal::Event::type_
          }

        class Event < Lithic::Internal::Type::BaseModel
          attr_reader token: String?

          def token=: (String) -> String

          attr_reader amount: Integer?

          def amount=: (Integer) -> Integer

          attr_reader created: Time?

          def created=: (Time) -> Time

          attr_reader result: Lithic::Models::AccountActivityListResponse::Internal::Event::result?

          def result=: (
            Lithic::Models::AccountActivityListResponse::Internal::Event::result
          ) -> Lithic::Models::AccountActivityListResponse::Internal::Event::result

          attr_reader type: Lithic::Models::AccountActivityListResponse::Internal::Event::type_?

          def type=: (
            Lithic::Models::AccountActivityListResponse::Internal::Event::type_
          ) -> Lithic::Models::AccountActivityListResponse::Internal::Event::type_

          def initialize: (
            ?token: String,
            ?amount: Integer,
            ?created: Time,
            ?result: Lithic::Models::AccountActivityListResponse::Internal::Event::result,
            ?type: Lithic::Models::AccountActivityListResponse::Internal::Event::type_
          ) -> void

          def to_hash: -> {
            token: String,
            amount: Integer,
            created: Time,
            result: Lithic::Models::AccountActivityListResponse::Internal::Event::result,
            type: Lithic::Models::AccountActivityListResponse::Internal::Event::type_
          }

          type result = :APPROVED | :DECLINED

          module Result
            extend Lithic::Internal::Type::Enum

            APPROVED: :APPROVED
            DECLINED: :DECLINED

            def self?.values: -> ::Array[Lithic::Models::AccountActivityListResponse::Internal::Event::result]
          end

          type type_ =
            :ACH_ORIGINATION_CANCELLED
            | :ACH_ORIGINATION_INITIATED
            | :ACH_ORIGINATION_PROCESSED
            | :ACH_ORIGINATION_RELEASED
            | :ACH_ORIGINATION_REJECTED
            | :ACH_ORIGINATION_REVIEWED
            | :ACH_ORIGINATION_SETTLED
            | :ACH_RECEIPT_PROCESSED
            | :ACH_RECEIPT_SETTLED
            | :ACH_RETURN_INITIATED
            | :ACH_RETURN_PROCESSED
            | :ACH_RETURN_REJECTED
            | :ACH_RETURN_SETTLED
            | :AUTHORIZATION
            | :AUTHORIZATION_ADVICE
            | :AUTHORIZATION_EXPIRY
            | :AUTHORIZATION_REVERSAL
            | :BALANCE_INQUIRY
            | :BILLING_ERROR
            | :BILLING_ERROR_REVERSAL
            | :CARD_TO_CARD
            | :CASH_BACK
            | :CASH_BACK_REVERSAL
            | :CLEARING
            | :COLLECTION
            | :CORRECTION_CREDIT
            | :CORRECTION_DEBIT
            | :CREDIT_AUTHORIZATION
            | :CREDIT_AUTHORIZATION_ADVICE
            | :CURRENCY_CONVERSION
            | :CURRENCY_CONVERSION_REVERSAL
            | :DISPUTE_WON
            | :EXTERNAL_ACH_CANCELED
            | :EXTERNAL_ACH_INITIATED
            | :EXTERNAL_ACH_RELEASED
            | :EXTERNAL_ACH_REVERSED
            | :EXTERNAL_ACH_SETTLED
            | :EXTERNAL_CHECK_CANCELED
            | :EXTERNAL_CHECK_INITIATED
            | :EXTERNAL_CHECK_RELEASED
            | :EXTERNAL_CHECK_REVERSED
            | :EXTERNAL_CHECK_SETTLED
            | :EXTERNAL_TRANSFER_CANCELED
            | :EXTERNAL_TRANSFER_INITIATED
            | :EXTERNAL_TRANSFER_RELEASED
            | :EXTERNAL_TRANSFER_REVERSED
            | :EXTERNAL_TRANSFER_SETTLED
            | :EXTERNAL_WIRE_CANCELED
            | :EXTERNAL_WIRE_INITIATED
            | :EXTERNAL_WIRE_RELEASED
            | :EXTERNAL_WIRE_REVERSED
            | :EXTERNAL_WIRE_SETTLED
            | :FINANCIAL_AUTHORIZATION
            | :FINANCIAL_CREDIT_AUTHORIZATION
            | :INTEREST
            | :INTEREST_REVERSAL
            | :INTERNAL_ADJUSTMENT
            | :LATE_PAYMENT
            | :LATE_PAYMENT_REVERSAL
            | :LOSS_WRITE_OFF
            | :PROVISIONAL_CREDIT
            | :PROVISIONAL_CREDIT_REVERSAL
            | :SERVICE
            | :RETURN
            | :RETURN_REVERSAL
            | :TRANSFER
            | :TRANSFER_INSUFFICIENT_FUNDS
            | :RETURNED_PAYMENT
            | :RETURNED_PAYMENT_REVERSAL
            | :LITHIC_NETWORK_PAYMENT

          module Type
            extend Lithic::Internal::Type::Enum

            ACH_ORIGINATION_CANCELLED: :ACH_ORIGINATION_CANCELLED
            ACH_ORIGINATION_INITIATED: :ACH_ORIGINATION_INITIATED
            ACH_ORIGINATION_PROCESSED: :ACH_ORIGINATION_PROCESSED
            ACH_ORIGINATION_RELEASED: :ACH_ORIGINATION_RELEASED
            ACH_ORIGINATION_REJECTED: :ACH_ORIGINATION_REJECTED
            ACH_ORIGINATION_REVIEWED: :ACH_ORIGINATION_REVIEWED
            ACH_ORIGINATION_SETTLED: :ACH_ORIGINATION_SETTLED
            ACH_RECEIPT_PROCESSED: :ACH_RECEIPT_PROCESSED
            ACH_RECEIPT_SETTLED: :ACH_RECEIPT_SETTLED
            ACH_RETURN_INITIATED: :ACH_RETURN_INITIATED
            ACH_RETURN_PROCESSED: :ACH_RETURN_PROCESSED
            ACH_RETURN_REJECTED: :ACH_RETURN_REJECTED
            ACH_RETURN_SETTLED: :ACH_RETURN_SETTLED
            AUTHORIZATION: :AUTHORIZATION
            AUTHORIZATION_ADVICE: :AUTHORIZATION_ADVICE
            AUTHORIZATION_EXPIRY: :AUTHORIZATION_EXPIRY
            AUTHORIZATION_REVERSAL: :AUTHORIZATION_REVERSAL
            BALANCE_INQUIRY: :BALANCE_INQUIRY
            BILLING_ERROR: :BILLING_ERROR
            BILLING_ERROR_REVERSAL: :BILLING_ERROR_REVERSAL
            CARD_TO_CARD: :CARD_TO_CARD
            CASH_BACK: :CASH_BACK
            CASH_BACK_REVERSAL: :CASH_BACK_REVERSAL
            CLEARING: :CLEARING
            COLLECTION: :COLLECTION
            CORRECTION_CREDIT: :CORRECTION_CREDIT
            CORRECTION_DEBIT: :CORRECTION_DEBIT
            CREDIT_AUTHORIZATION: :CREDIT_AUTHORIZATION
            CREDIT_AUTHORIZATION_ADVICE: :CREDIT_AUTHORIZATION_ADVICE
            CURRENCY_CONVERSION: :CURRENCY_CONVERSION
            CURRENCY_CONVERSION_REVERSAL: :CURRENCY_CONVERSION_REVERSAL
            DISPUTE_WON: :DISPUTE_WON
            EXTERNAL_ACH_CANCELED: :EXTERNAL_ACH_CANCELED
            EXTERNAL_ACH_INITIATED: :EXTERNAL_ACH_INITIATED
            EXTERNAL_ACH_RELEASED: :EXTERNAL_ACH_RELEASED
            EXTERNAL_ACH_REVERSED: :EXTERNAL_ACH_REVERSED
            EXTERNAL_ACH_SETTLED: :EXTERNAL_ACH_SETTLED
            EXTERNAL_CHECK_CANCELED: :EXTERNAL_CHECK_CANCELED
            EXTERNAL_CHECK_INITIATED: :EXTERNAL_CHECK_INITIATED
            EXTERNAL_CHECK_RELEASED: :EXTERNAL_CHECK_RELEASED
            EXTERNAL_CHECK_REVERSED: :EXTERNAL_CHECK_REVERSED
            EXTERNAL_CHECK_SETTLED: :EXTERNAL_CHECK_SETTLED
            EXTERNAL_TRANSFER_CANCELED: :EXTERNAL_TRANSFER_CANCELED
            EXTERNAL_TRANSFER_INITIATED: :EXTERNAL_TRANSFER_INITIATED
            EXTERNAL_TRANSFER_RELEASED: :EXTERNAL_TRANSFER_RELEASED
            EXTERNAL_TRANSFER_REVERSED: :EXTERNAL_TRANSFER_REVERSED
            EXTERNAL_TRANSFER_SETTLED: :EXTERNAL_TRANSFER_SETTLED
            EXTERNAL_WIRE_CANCELED: :EXTERNAL_WIRE_CANCELED
            EXTERNAL_WIRE_INITIATED: :EXTERNAL_WIRE_INITIATED
            EXTERNAL_WIRE_RELEASED: :EXTERNAL_WIRE_RELEASED
            EXTERNAL_WIRE_REVERSED: :EXTERNAL_WIRE_REVERSED
            EXTERNAL_WIRE_SETTLED: :EXTERNAL_WIRE_SETTLED
            FINANCIAL_AUTHORIZATION: :FINANCIAL_AUTHORIZATION
            FINANCIAL_CREDIT_AUTHORIZATION: :FINANCIAL_CREDIT_AUTHORIZATION
            INTEREST: :INTEREST
            INTEREST_REVERSAL: :INTEREST_REVERSAL
            INTERNAL_ADJUSTMENT: :INTERNAL_ADJUSTMENT
            LATE_PAYMENT: :LATE_PAYMENT
            LATE_PAYMENT_REVERSAL: :LATE_PAYMENT_REVERSAL
            LOSS_WRITE_OFF: :LOSS_WRITE_OFF
            PROVISIONAL_CREDIT: :PROVISIONAL_CREDIT
            PROVISIONAL_CREDIT_REVERSAL: :PROVISIONAL_CREDIT_REVERSAL
            SERVICE: :SERVICE
            RETURN: :RETURN
            RETURN_REVERSAL: :RETURN_REVERSAL
            TRANSFER: :TRANSFER
            TRANSFER_INSUFFICIENT_FUNDS: :TRANSFER_INSUFFICIENT_FUNDS
            RETURNED_PAYMENT: :RETURNED_PAYMENT
            RETURNED_PAYMENT_REVERSAL: :RETURNED_PAYMENT_REVERSAL
            LITHIC_NETWORK_PAYMENT: :LITHIC_NETWORK_PAYMENT

            def self?.values: -> ::Array[Lithic::Models::AccountActivityListResponse::Internal::Event::type_]
          end
        end

        type result = :APPROVED | :DECLINED

        module Result
          extend Lithic::Internal::Type::Enum

          APPROVED: :APPROVED
          DECLINED: :DECLINED

          def self?.values: -> ::Array[Lithic::Models::AccountActivityListResponse::Internal::result]
        end

        type status = :PENDING | :SETTLED | :DECLINED | :REVERSED | :CANCELED

        module Status
          extend Lithic::Internal::Type::Enum

          PENDING: :PENDING
          SETTLED: :SETTLED
          DECLINED: :DECLINED
          REVERSED: :REVERSED
          CANCELED: :CANCELED

          def self?.values: -> ::Array[Lithic::Models::AccountActivityListResponse::Internal::status]
        end
      end

      type card = {  }

      class Card < Lithic::Models::Transaction
        def initialize: -> void

        def to_hash: -> {  }
      end

      def self?.variants: -> ::Array[Lithic::Models::account_activity_list_response]
    end
  end
end
