module Lithic
  module Models
    type address =
      {
        :address1 => String,
        city: String,
        country: String,
        :address2 => String,
        postal_code: String?,
        state: String?
      }

    class Address < Lithic::Internal::Type::BaseModel
      attr_accessor address1: String

      attr_accessor city: String

      attr_accessor country: String

      attr_reader address2: String?

      def address2=: (String) -> String

      attr_accessor postal_code: String?

      attr_accessor state: String?

      def initialize: (
        address1: String,
        city: String,
        country: String,
        ?address2: String,
        ?postal_code: String?,
        ?state: String?
      ) -> void

      def to_hash: -> {
        :address1 => String,
        city: String,
        country: String,
        :address2 => String,
        postal_code: String?,
        state: String?
      }
    end
  end
end
