module Lithic
  module Models
    type api_status = { message: String }

    class APIStatus < Lithic::Internal::Type::BaseModel
      attr_reader message: String?

      def message=: (String) -> String

      def initialize: (?message: String) -> void

      def to_hash: -> { message: String }
    end
  end
end
