module Lithic
  module Models
    type auth_stream_enrollment_retrieve_secret_params =
      {  } & Lithic::Internal::Type::request_parameters

    class AuthStreamEnrollmentRetrieveSecretParams < Lithic::Internal::Type::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      def initialize: (?request_options: Lithic::request_opts) -> void
    end
  end
end
