module Lithic
  module Models
    type auth_stream_secret = { secret: String }

    class AuthStreamSecret < Lithic::Internal::Type::BaseModel
      attr_reader secret: String?

      def secret=: (String) -> String

      def initialize: (?secret: String) -> void

      def to_hash: -> { secret: String }
    end
  end
end
