module Lithic
  module Models
    type blockchain_recipient_retrieve_params =
      { blockchain_recipient_token: String }
      & Lithic::Internal::Type::request_parameters

    class BlockchainRecipientRetrieveParams < Lithic::Internal::Type::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_accessor blockchain_recipient_token: String

      def initialize: (
        blockchain_recipient_token: String,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> {
        blockchain_recipient_token: String,
        request_options: Lithic::RequestOptions
      }
    end
  end
end
