module Lithic
  module Models
    type book_transfer_list_params =
      {
        account_token: String,
        begin_: Time,
        business_account_token: String,
        category: Lithic::Models::BookTransferListParams::category,
        end_: Time,
        ending_before: String,
        financial_account_token: String,
        page_size: Integer,
        result: Lithic::Models::BookTransferListParams::result,
        starting_after: String,
        status: Lithic::Models::BookTransferListParams::status
      }
      & Lithic::Internal::Type::request_parameters

    class BookTransferListParams < Lithic::Internal::Type::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_reader account_token: String?

      def account_token=: (String) -> String

      attr_reader begin_: Time?

      def begin_=: (Time) -> Time

      attr_reader business_account_token: String?

      def business_account_token=: (String) -> String

      attr_reader category: Lithic::Models::BookTransferListParams::category?

      def category=: (
        Lithic::Models::BookTransferListParams::category
      ) -> Lithic::Models::BookTransferListParams::category

      attr_reader end_: Time?

      def end_=: (Time) -> Time

      attr_reader ending_before: String?

      def ending_before=: (String) -> String

      attr_reader financial_account_token: String?

      def financial_account_token=: (String) -> String

      attr_reader page_size: Integer?

      def page_size=: (Integer) -> Integer

      attr_reader result: Lithic::Models::BookTransferListParams::result?

      def result=: (
        Lithic::Models::BookTransferListParams::result
      ) -> Lithic::Models::BookTransferListParams::result

      attr_reader starting_after: String?

      def starting_after=: (String) -> String

      attr_reader status: Lithic::Models::BookTransferListParams::status?

      def status=: (
        Lithic::Models::BookTransferListParams::status
      ) -> Lithic::Models::BookTransferListParams::status

      def initialize: (
        ?account_token: String,
        ?begin_: Time,
        ?business_account_token: String,
        ?category: Lithic::Models::BookTransferListParams::category,
        ?end_: Time,
        ?ending_before: String,
        ?financial_account_token: String,
        ?page_size: Integer,
        ?result: Lithic::Models::BookTransferListParams::result,
        ?starting_after: String,
        ?status: Lithic::Models::BookTransferListParams::status,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> {
        account_token: String,
        begin_: Time,
        business_account_token: String,
        category: Lithic::Models::BookTransferListParams::category,
        end_: Time,
        ending_before: String,
        financial_account_token: String,
        page_size: Integer,
        result: Lithic::Models::BookTransferListParams::result,
        starting_after: String,
        status: Lithic::Models::BookTransferListParams::status,
        request_options: Lithic::RequestOptions
      }

      type category =
        :ADJUSTMENT
        | :BALANCE_OR_FUNDING
        | :DERECOGNITION
        | :DISPUTE
        | :FEE
        | :INTERNAL
        | :REWARD
        | :PROGRAM_FUNDING
        | :TRANSFER

      module Category
        extend Lithic::Internal::Type::Enum

        ADJUSTMENT: :ADJUSTMENT
        BALANCE_OR_FUNDING: :BALANCE_OR_FUNDING
        DERECOGNITION: :DERECOGNITION
        DISPUTE: :DISPUTE
        FEE: :FEE
        INTERNAL: :INTERNAL
        REWARD: :REWARD
        PROGRAM_FUNDING: :PROGRAM_FUNDING
        TRANSFER: :TRANSFER

        def self?.values: -> ::Array[Lithic::Models::BookTransferListParams::category]
      end

      type result = :APPROVED | :DECLINED

      module Result
        extend Lithic::Internal::Type::Enum

        APPROVED: :APPROVED
        DECLINED: :DECLINED

        def self?.values: -> ::Array[Lithic::Models::BookTransferListParams::result]
      end

      type status = :DECLINED | :SETTLED

      module Status
        extend Lithic::Internal::Type::Enum

        DECLINED: :DECLINED
        SETTLED: :SETTLED

        def self?.values: -> ::Array[Lithic::Models::BookTransferListParams::status]
      end
    end
  end
end
