module Lithic
  module Models
    type book_transfer_reverse_params =
      { memo: String } & Lithic::Internal::Type::request_parameters

    class BookTransferReverseParams < Lithic::Internal::Type::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_reader memo: String?

      def memo=: (String) -> String

      def initialize: (
        ?memo: String,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> Lithic::Models::book_transfer_reverse_params
    end
  end
end
