module Lithic
  module Models
    type book_transfer_response =
      {
        token: String,
        category: Lithic::Models::BookTransferResponse::category,
        created: Time,
        currency: String,
        events: ::Array[Lithic::BookTransferResponse::Event],
        external_resource: Lithic::ExternalResource?,
        from_financial_account_token: String,
        pending_amount: Integer,
        result: Lithic::Models::BookTransferResponse::result,
        settled_amount: Integer,
        status: Lithic::Models::BookTransferResponse::status,
        to_financial_account_token: top,
        transaction_series: Lithic::BookTransferResponse::TransactionSeries?,
        updated: Time
      }

    class BookTransferResponse < Lithic::Internal::Type::BaseModel
      attr_accessor token: String

      attr_accessor category: Lithic::Models::BookTransferResponse::category

      attr_accessor created: Time

      attr_accessor currency: String

      attr_accessor events: ::Array[Lithic::BookTransferResponse::Event]

      attr_accessor external_resource: Lithic::ExternalResource?

      attr_accessor from_financial_account_token: String

      attr_accessor pending_amount: Integer

      attr_accessor result: Lithic::Models::BookTransferResponse::result

      attr_accessor settled_amount: Integer

      attr_accessor status: Lithic::Models::BookTransferResponse::status

      attr_accessor to_financial_account_token: top

      attr_accessor transaction_series: Lithic::BookTransferResponse::TransactionSeries?

      attr_accessor updated: Time

      def initialize: (
        token: String,
        category: Lithic::Models::BookTransferResponse::category,
        created: Time,
        currency: String,
        events: ::Array[Lithic::BookTransferResponse::Event],
        external_resource: Lithic::ExternalResource?,
        from_financial_account_token: String,
        pending_amount: Integer,
        result: Lithic::Models::BookTransferResponse::result,
        settled_amount: Integer,
        status: Lithic::Models::BookTransferResponse::status,
        to_financial_account_token: top,
        transaction_series: Lithic::BookTransferResponse::TransactionSeries?,
        updated: Time
      ) -> void

      def to_hash: -> {
        token: String,
        category: Lithic::Models::BookTransferResponse::category,
        created: Time,
        currency: String,
        events: ::Array[Lithic::BookTransferResponse::Event],
        external_resource: Lithic::ExternalResource?,
        from_financial_account_token: String,
        pending_amount: Integer,
        result: Lithic::Models::BookTransferResponse::result,
        settled_amount: Integer,
        status: Lithic::Models::BookTransferResponse::status,
        to_financial_account_token: top,
        transaction_series: Lithic::BookTransferResponse::TransactionSeries?,
        updated: Time
      }

      type category =
        :ADJUSTMENT
        | :BALANCE_OR_FUNDING
        | :DERECOGNITION
        | :DISPUTE
        | :FEE
        | :REWARD
        | :TRANSFER

      module Category
        extend Lithic::Internal::Type::Enum

        ADJUSTMENT: :ADJUSTMENT
        BALANCE_OR_FUNDING: :BALANCE_OR_FUNDING
        DERECOGNITION: :DERECOGNITION
        DISPUTE: :DISPUTE
        FEE: :FEE
        REWARD: :REWARD
        TRANSFER: :TRANSFER

        def self?.values: -> ::Array[Lithic::Models::BookTransferResponse::category]
      end

      type event =
        {
          token: String,
          amount: Integer,
          created: Time,
          detailed_results: ::Array[Lithic::Models::BookTransferResponse::Event::detailed_result],
          memo: String,
          result: Lithic::Models::BookTransferResponse::Event::result,
          subtype: String,
          type: String
        }

      class Event < Lithic::Internal::Type::BaseModel
        attr_accessor token: String

        attr_accessor amount: Integer

        attr_accessor created: Time

        attr_accessor detailed_results: ::Array[Lithic::Models::BookTransferResponse::Event::detailed_result]

        attr_accessor memo: String

        attr_accessor result: Lithic::Models::BookTransferResponse::Event::result

        attr_accessor subtype: String

        attr_accessor type: String

        def initialize: (
          token: String,
          amount: Integer,
          created: Time,
          detailed_results: ::Array[Lithic::Models::BookTransferResponse::Event::detailed_result],
          memo: String,
          result: Lithic::Models::BookTransferResponse::Event::result,
          subtype: String,
          type: String
        ) -> void

        def to_hash: -> {
          token: String,
          amount: Integer,
          created: Time,
          detailed_results: ::Array[Lithic::Models::BookTransferResponse::Event::detailed_result],
          memo: String,
          result: Lithic::Models::BookTransferResponse::Event::result,
          subtype: String,
          type: String
        }

        type detailed_result = :APPROVED | :FUNDS_INSUFFICIENT

        module DetailedResult
          extend Lithic::Internal::Type::Enum

          APPROVED: :APPROVED
          FUNDS_INSUFFICIENT: :FUNDS_INSUFFICIENT

          def self?.values: -> ::Array[Lithic::Models::BookTransferResponse::Event::detailed_result]
        end

        type result = :APPROVED | :DECLINED

        module Result
          extend Lithic::Internal::Type::Enum

          APPROVED: :APPROVED
          DECLINED: :DECLINED

          def self?.values: -> ::Array[Lithic::Models::BookTransferResponse::Event::result]
        end
      end

      type result = :APPROVED | :DECLINED

      module Result
        extend Lithic::Internal::Type::Enum

        APPROVED: :APPROVED
        DECLINED: :DECLINED

        def self?.values: -> ::Array[Lithic::Models::BookTransferResponse::result]
      end

      type status = :DECLINED | :REVERSED | :SETTLED

      module Status
        extend Lithic::Internal::Type::Enum

        DECLINED: :DECLINED
        REVERSED: :REVERSED
        SETTLED: :SETTLED

        def self?.values: -> ::Array[Lithic::Models::BookTransferResponse::status]
      end

      type transaction_series =
        {
          related_transaction_event_token: String?,
          related_transaction_token: String?,
          type: String
        }

      class TransactionSeries < Lithic::Internal::Type::BaseModel
        attr_accessor related_transaction_event_token: String?

        attr_accessor related_transaction_token: String?

        attr_accessor type: String

        def initialize: (
          related_transaction_event_token: String?,
          related_transaction_token: String?,
          type: String
        ) -> void

        def to_hash: -> {
          related_transaction_event_token: String?,
          related_transaction_token: String?,
          type: String
        }
      end
    end
  end
end
