module Lithic
  module Models
    type book_transfer_retrieve_params =
      {  } & Lithic::Internal::Type::request_parameters

    class BookTransferRetrieveParams < Lithic::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      def initialize: (?request_options: Lithic::request_opts) -> void

      def to_hash: -> Lithic::Models::book_transfer_retrieve_params
    end
  end
end
