module Lithic
  module Models
    type card_search_by_pan_params =
      { pan: String } & Lithic::Internal::Type::request_parameters

    class CardSearchByPanParams < Lithic::Internal::Type::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_accessor pan: String

      def initialize: (
        pan: String,
        ?request_options: Lithic::request_opts
      ) -> void
    end
  end
end
