module Lithic
  module Models
    type card_embed_params =
      { embed_request: String, hmac: String } & Lithic::request_parameters

    class CardEmbedParams < Lithic::BaseModel
      extend Lithic::Type::RequestParameters::Converter
      include Lithic::RequestParameters

      attr_accessor embed_request: String

      attr_accessor hmac: String

      def initialize: (
        embed_request: String,
        hmac: String,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> Lithic::Models::card_embed_params
    end
  end
end
