module Lithic
  module Models
    type card_convert_physical_params =
      {
        shipping_address: Lithic::ShippingAddress,
        carrier: Lithic::Carrier,
        product_id: String,
        shipping_method: Lithic::Models::CardConvertPhysicalParams::shipping_method
      }
      & Lithic::Internal::Type::request_parameters

    class CardConvertPhysicalParams < Lithic::Internal::Type::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_accessor shipping_address: Lithic::ShippingAddress

      attr_reader carrier: Lithic::Carrier?

      def carrier=: (Lithic::Carrier) -> Lithic::Carrier

      attr_reader product_id: String?

      def product_id=: (String) -> String

      attr_reader shipping_method: Lithic::Models::CardConvertPhysicalParams::shipping_method?

      def shipping_method=: (
        Lithic::Models::CardConvertPhysicalParams::shipping_method
      ) -> Lithic::Models::CardConvertPhysicalParams::shipping_method

      def initialize: (
        shipping_address: Lithic::ShippingAddress,
        ?carrier: Lithic::Carrier,
        ?product_id: String,
        ?shipping_method: Lithic::Models::CardConvertPhysicalParams::shipping_method,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> {
        shipping_address: Lithic::ShippingAddress,
        carrier: Lithic::Carrier,
        product_id: String,
        shipping_method: Lithic::Models::CardConvertPhysicalParams::shipping_method,
        request_options: Lithic::RequestOptions
      }

      type shipping_method =
        :"2_DAY"
        | :BULK_EXPEDITED
        | :EXPEDITED
        | :EXPRESS
        | :PRIORITY
        | :STANDARD
        | :STANDARD_WITH_TRACKING

      module ShippingMethod
        extend Lithic::Internal::Type::Enum

        SHIPPING_METHOD_2_DAY: :"2_DAY"
        BULK_EXPEDITED: :BULK_EXPEDITED
        EXPEDITED: :EXPEDITED
        EXPRESS: :EXPRESS
        PRIORITY: :PRIORITY
        STANDARD: :STANDARD
        STANDARD_WITH_TRACKING: :STANDARD_WITH_TRACKING

        def self?.values: -> ::Array[Lithic::Models::CardConvertPhysicalParams::shipping_method]
      end
    end
  end
end
