module Lithic
  module Models
    type card_program_retrieve_params =
      {  } & Lithic::Internal::Type::request_parameters

    class CardProgramRetrieveParams < Lithic::Internal::Type::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      def initialize: (?request_options: Lithic::request_opts) -> void

      def to_hash: -> { request_options: Lithic::RequestOptions }
    end
  end
end
