module Lithic
  module Models
    type card_provision_response = { provisioning_payload: String }

    class CardProvisionResponse < Lithic::Internal::Type::BaseModel
      attr_reader provisioning_payload: String?

      def provisioning_payload=: (String) -> String

      def initialize: (?provisioning_payload: String) -> void

      def to_hash: -> { provisioning_payload: String }
    end
  end
end
