module Lithic
  module Models
    type cardholder_authentication =
      {
        authentication_method: Lithic::Models::CardholderAuthentication::authentication_method,
        authentication_result: Lithic::Models::CardholderAuthentication::authentication_result,
        decision_made_by: Lithic::Models::CardholderAuthentication::decision_made_by,
        liability_shift: Lithic::Models::CardholderAuthentication::liability_shift,
        three_ds_authentication_token: String?
      }

    class CardholderAuthentication < Lithic::Internal::Type::BaseModel
      attr_accessor authentication_method: Lithic::Models::CardholderAuthentication::authentication_method

      attr_accessor authentication_result: Lithic::Models::CardholderAuthentication::authentication_result

      attr_accessor decision_made_by: Lithic::Models::CardholderAuthentication::decision_made_by

      attr_accessor liability_shift: Lithic::Models::CardholderAuthentication::liability_shift

      attr_accessor three_ds_authentication_token: String?

      def initialize: (
        authentication_method: Lithic::Models::CardholderAuthentication::authentication_method,
        authentication_result: Lithic::Models::CardholderAuthentication::authentication_result,
        decision_made_by: Lithic::Models::CardholderAuthentication::decision_made_by,
        liability_shift: Lithic::Models::CardholderAuthentication::liability_shift,
        three_ds_authentication_token: String?
      ) -> void

      def to_hash: -> {
        authentication_method: Lithic::Models::CardholderAuthentication::authentication_method,
        authentication_result: Lithic::Models::CardholderAuthentication::authentication_result,
        decision_made_by: Lithic::Models::CardholderAuthentication::decision_made_by,
        liability_shift: Lithic::Models::CardholderAuthentication::liability_shift,
        three_ds_authentication_token: String?
      }

      type authentication_method = :FRICTIONLESS | :CHALLENGE | :NONE

      module AuthenticationMethod
        extend Lithic::Internal::Type::Enum

        FRICTIONLESS: :FRICTIONLESS
        CHALLENGE: :CHALLENGE
        NONE: :NONE

        def self?.values: -> ::Array[Lithic::Models::CardholderAuthentication::authentication_method]
      end

      type authentication_result = :ATTEMPTS | :DECLINE | :NONE | :SUCCESS

      module AuthenticationResult
        extend Lithic::Internal::Type::Enum

        ATTEMPTS: :ATTEMPTS
        DECLINE: :DECLINE
        NONE: :NONE
        SUCCESS: :SUCCESS

        def self?.values: -> ::Array[Lithic::Models::CardholderAuthentication::authentication_result]
      end

      type decision_made_by =
        :CUSTOMER_RULES
        | :CUSTOMER_ENDPOINT
        | :LITHIC_DEFAULT
        | :LITHIC_RULES
        | :NETWORK
        | :UNKNOWN

      module DecisionMadeBy
        extend Lithic::Internal::Type::Enum

        CUSTOMER_RULES: :CUSTOMER_RULES
        CUSTOMER_ENDPOINT: :CUSTOMER_ENDPOINT
        LITHIC_DEFAULT: :LITHIC_DEFAULT
        LITHIC_RULES: :LITHIC_RULES
        NETWORK: :NETWORK
        UNKNOWN: :UNKNOWN

        def self?.values: -> ::Array[Lithic::Models::CardholderAuthentication::decision_made_by]
      end

      type liability_shift = :"3DS_AUTHENTICATED" | :TOKEN_AUTHENTICATED | :NONE

      module LiabilityShift
        extend Lithic::Internal::Type::Enum

        LIABILITY_SHIFT_3DS_AUTHENTICATED: :"3DS_AUTHENTICATED"
        TOKEN_AUTHENTICATED: :TOKEN_AUTHENTICATED
        NONE: :NONE

        def self?.values: -> ::Array[Lithic::Models::CardholderAuthentication::liability_shift]
      end
    end
  end
end
