module Lithic
  module Models
    type card_transaction_enhanced_data_updated_webhook_event =
      { event_type: :"card_transaction.enhanced_data.updated" }

    class CardTransactionEnhancedDataUpdatedWebhookEvent < Lithic::Models::Transactions::Events::EnhancedData
      def event_type: -> :"card_transaction.enhanced_data.updated"

      def event_type=: (
        :"card_transaction.enhanced_data.updated" _
      ) -> :"card_transaction.enhanced_data.updated"

      def initialize: (
        ?event_type: :"card_transaction.enhanced_data.updated"
      ) -> void

      def to_hash: -> { event_type: :"card_transaction.enhanced_data.updated" }
    end
  end
end
