module Lithic
  module Models
    type card_program_retrieve_params =
      { card_program_token: String }
      & Lithic::Internal::Type::request_parameters

    class CardProgramRetrieveParams < Lithic::Internal::Type::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_accessor card_program_token: String

      def initialize: (
        card_program_token: String,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> {
        card_program_token: String,
        request_options: Lithic::RequestOptions
      }
    end
  end
end
