module Lithic
  module Models
    type digital_wallet_tokenization_two_factor_authentication_code_sent_webhook_event =
      {
        account_token: String,
        activation_method: Lithic::DigitalWalletTokenizationTwoFactorAuthenticationCodeSentWebhookEvent::ActivationMethod,
        card_token: String,
        created: Time,
        event_type: :"digital_wallet.tokenization_two_factor_authentication_code_sent",
        tokenization_token: String
      }

    class DigitalWalletTokenizationTwoFactorAuthenticationCodeSentWebhookEvent < Lithic::Internal::Type::BaseModel
      attr_accessor account_token: String

      attr_accessor activation_method: Lithic::DigitalWalletTokenizationTwoFactorAuthenticationCodeSentWebhookEvent::ActivationMethod

      attr_accessor card_token: String

      attr_accessor created: Time

      attr_accessor event_type: :"digital_wallet.tokenization_two_factor_authentication_code_sent"

      attr_accessor tokenization_token: String

      def initialize: (
        account_token: String,
        activation_method: Lithic::DigitalWalletTokenizationTwoFactorAuthenticationCodeSentWebhookEvent::ActivationMethod,
        card_token: String,
        created: Time,
        tokenization_token: String,
        ?event_type: :"digital_wallet.tokenization_two_factor_authentication_code_sent"
      ) -> void

      def to_hash: -> {
        account_token: String,
        activation_method: Lithic::DigitalWalletTokenizationTwoFactorAuthenticationCodeSentWebhookEvent::ActivationMethod,
        card_token: String,
        created: Time,
        event_type: :"digital_wallet.tokenization_two_factor_authentication_code_sent",
        tokenization_token: String
      }

      type activation_method =
        {
          type: Lithic::Models::DigitalWalletTokenizationTwoFactorAuthenticationCodeSentWebhookEvent::ActivationMethod::type_,
          value: String
        }

      class ActivationMethod < Lithic::Internal::Type::BaseModel
        attr_accessor type: Lithic::Models::DigitalWalletTokenizationTwoFactorAuthenticationCodeSentWebhookEvent::ActivationMethod::type_

        attr_accessor value: String

        def initialize: (
          type: Lithic::Models::DigitalWalletTokenizationTwoFactorAuthenticationCodeSentWebhookEvent::ActivationMethod::type_,
          value: String
        ) -> void

        def to_hash: -> {
          type: Lithic::Models::DigitalWalletTokenizationTwoFactorAuthenticationCodeSentWebhookEvent::ActivationMethod::type_,
          value: String
        }

        type type_ = :EMAIL_TO_CARDHOLDER_ADDRESS | :TEXT_TO_CARDHOLDER_NUMBER

        module Type
          extend Lithic::Internal::Type::Enum

          EMAIL_TO_CARDHOLDER_ADDRESS: :EMAIL_TO_CARDHOLDER_ADDRESS
          TEXT_TO_CARDHOLDER_NUMBER: :TEXT_TO_CARDHOLDER_NUMBER

          def self?.values: -> ::Array[Lithic::Models::DigitalWalletTokenizationTwoFactorAuthenticationCodeSentWebhookEvent::ActivationMethod::type_]
        end
      end
    end
  end
end
