module Lithic
  module Models
    type digital_card_art_retrieve_params = {  } & Lithic::request_parameters

    class DigitalCardArtRetrieveParams < Lithic::BaseModel
      extend Lithic::Type::RequestParameters::Converter
      include Lithic::RequestParameters

      def initialize: (?request_options: Lithic::request_opts) -> void

      def to_hash: -> Lithic::Models::digital_card_art_retrieve_params
    end
  end
end
