module Lithic
  module Models
    type dispute =
      {
        token: String,
        account_token: String,
        card_token: String,
        case_id: String?,
        created: Time,
        currency: String,
        disposition: Lithic::Models::Dispute::disposition?,
        events: ::Array[Lithic::Dispute::Event],
        liability_allocation: Lithic::Dispute::LiabilityAllocation,
        merchant: Lithic::Dispute::Merchant,
        network: Lithic::Models::Dispute::network,
        status: Lithic::Models::Dispute::status?,
        transaction_series: Lithic::Dispute::TransactionSeries?,
        updated: Time
      }

    class Dispute < Lithic::Internal::Type::BaseModel
      attr_accessor token: String

      attr_accessor account_token: String

      attr_accessor card_token: String

      attr_accessor case_id: String?

      attr_accessor created: Time

      attr_accessor currency: String

      attr_accessor disposition: Lithic::Models::Dispute::disposition?

      attr_accessor events: ::Array[Lithic::Dispute::Event]

      attr_accessor liability_allocation: Lithic::Dispute::LiabilityAllocation

      attr_accessor merchant: Lithic::Dispute::Merchant

      attr_accessor network: Lithic::Models::Dispute::network

      attr_accessor status: Lithic::Models::Dispute::status?

      attr_accessor transaction_series: Lithic::Dispute::TransactionSeries?

      attr_accessor updated: Time

      def initialize: (
        token: String,
        account_token: String,
        card_token: String,
        case_id: String?,
        created: Time,
        currency: String,
        disposition: Lithic::Models::Dispute::disposition?,
        events: ::Array[Lithic::Dispute::Event],
        liability_allocation: Lithic::Dispute::LiabilityAllocation,
        merchant: Lithic::Dispute::Merchant,
        network: Lithic::Models::Dispute::network,
        status: Lithic::Models::Dispute::status?,
        transaction_series: Lithic::Dispute::TransactionSeries?,
        updated: Time
      ) -> void

      def to_hash: -> {
        token: String,
        account_token: String,
        card_token: String,
        case_id: String?,
        created: Time,
        currency: String,
        disposition: Lithic::Models::Dispute::disposition?,
        events: ::Array[Lithic::Dispute::Event],
        liability_allocation: Lithic::Dispute::LiabilityAllocation,
        merchant: Lithic::Dispute::Merchant,
        network: Lithic::Models::Dispute::network,
        status: Lithic::Models::Dispute::status?,
        transaction_series: Lithic::Dispute::TransactionSeries?,
        updated: Time
      }

      type disposition = :WON | :LOST | :PARTIALLY_WON | :WITHDRAWN | :DENIED

      module Disposition
        extend Lithic::Internal::Type::Enum

        WON: :WON
        LOST: :LOST
        PARTIALLY_WON: :PARTIALLY_WON
        WITHDRAWN: :WITHDRAWN
        DENIED: :DENIED

        def self?.values: -> ::Array[Lithic::Models::Dispute::disposition]
      end

      type event =
        {
          token: String,
          created: Time,
          data: Lithic::Models::Dispute::Event::data,
          type: Lithic::Models::Dispute::Event::type_
        }

      class Event < Lithic::Internal::Type::BaseModel
        attr_accessor token: String

        attr_accessor created: Time

        attr_accessor data: Lithic::Models::Dispute::Event::data

        attr_accessor type: Lithic::Models::Dispute::Event::type_

        def initialize: (
          token: String,
          created: Time,
          data: Lithic::Models::Dispute::Event::data,
          type: Lithic::Models::Dispute::Event::type_
        ) -> void

        def to_hash: -> {
          token: String,
          created: Time,
          data: Lithic::Models::Dispute::Event::data,
          type: Lithic::Models::Dispute::Event::type_
        }

        type data =
          Lithic::Dispute::Event::Data::WorkflowEventData
          | Lithic::Dispute::Event::Data::FinancialEventData
          | Lithic::Dispute::Event::Data::CardholderLiabilityEventData

        module Data
          extend Lithic::Internal::Type::Union

          type workflow_event_data =
            {
              action: Lithic::Models::Dispute::Event::Data::WorkflowEventData::action,
              amount: Integer?,
              disposition: Lithic::Models::Dispute::Event::Data::WorkflowEventData::disposition?,
              reason: String?,
              stage: Lithic::Models::Dispute::Event::Data::WorkflowEventData::stage
            }

          class WorkflowEventData < Lithic::Internal::Type::BaseModel
            attr_accessor action: Lithic::Models::Dispute::Event::Data::WorkflowEventData::action

            attr_accessor amount: Integer?

            attr_accessor disposition: Lithic::Models::Dispute::Event::Data::WorkflowEventData::disposition?

            attr_accessor reason: String?

            attr_accessor stage: Lithic::Models::Dispute::Event::Data::WorkflowEventData::stage

            def initialize: (
              action: Lithic::Models::Dispute::Event::Data::WorkflowEventData::action,
              amount: Integer?,
              disposition: Lithic::Models::Dispute::Event::Data::WorkflowEventData::disposition?,
              reason: String?,
              stage: Lithic::Models::Dispute::Event::Data::WorkflowEventData::stage
            ) -> void

            def to_hash: -> {
              action: Lithic::Models::Dispute::Event::Data::WorkflowEventData::action,
              amount: Integer?,
              disposition: Lithic::Models::Dispute::Event::Data::WorkflowEventData::disposition?,
              reason: String?,
              stage: Lithic::Models::Dispute::Event::Data::WorkflowEventData::stage
            }

            type action = :OPENED | :CLOSED | :REOPENED

            module Action
              extend Lithic::Internal::Type::Enum

              OPENED: :OPENED
              CLOSED: :CLOSED
              REOPENED: :REOPENED

              def self?.values: -> ::Array[Lithic::Models::Dispute::Event::Data::WorkflowEventData::action]
            end

            type disposition =
              :WON | :LOST | :PARTIALLY_WON | :WITHDRAWN | :DENIED

            module Disposition
              extend Lithic::Internal::Type::Enum

              WON: :WON
              LOST: :LOST
              PARTIALLY_WON: :PARTIALLY_WON
              WITHDRAWN: :WITHDRAWN
              DENIED: :DENIED

              def self?.values: -> ::Array[Lithic::Models::Dispute::Event::Data::WorkflowEventData::disposition]
            end

            type stage = :CLAIM

            module Stage
              extend Lithic::Internal::Type::Enum

              CLAIM: :CLAIM

              def self?.values: -> ::Array[Lithic::Models::Dispute::Event::Data::WorkflowEventData::stage]
            end
          end

          type financial_event_data =
            {
              amount: Integer,
              polarity: Lithic::Models::Dispute::Event::Data::FinancialEventData::polarity,
              stage: Lithic::Models::Dispute::Event::Data::FinancialEventData::stage
            }

          class FinancialEventData < Lithic::Internal::Type::BaseModel
            attr_accessor amount: Integer

            attr_accessor polarity: Lithic::Models::Dispute::Event::Data::FinancialEventData::polarity

            attr_accessor stage: Lithic::Models::Dispute::Event::Data::FinancialEventData::stage

            def initialize: (
              amount: Integer,
              polarity: Lithic::Models::Dispute::Event::Data::FinancialEventData::polarity,
              stage: Lithic::Models::Dispute::Event::Data::FinancialEventData::stage
            ) -> void

            def to_hash: -> {
              amount: Integer,
              polarity: Lithic::Models::Dispute::Event::Data::FinancialEventData::polarity,
              stage: Lithic::Models::Dispute::Event::Data::FinancialEventData::stage
            }

            type polarity = :CREDIT | :DEBIT

            module Polarity
              extend Lithic::Internal::Type::Enum

              CREDIT: :CREDIT
              DEBIT: :DEBIT

              def self?.values: -> ::Array[Lithic::Models::Dispute::Event::Data::FinancialEventData::polarity]
            end

            type stage =
              :CHARGEBACK
              | :REPRESENTMENT
              | :PREARBITRATION
              | :ARBITRATION
              | :COLLABORATION

            module Stage
              extend Lithic::Internal::Type::Enum

              CHARGEBACK: :CHARGEBACK
              REPRESENTMENT: :REPRESENTMENT
              PREARBITRATION: :PREARBITRATION
              ARBITRATION: :ARBITRATION
              COLLABORATION: :COLLABORATION

              def self?.values: -> ::Array[Lithic::Models::Dispute::Event::Data::FinancialEventData::stage]
            end
          end

          type cardholder_liability_event_data =
            {
              action: Lithic::Models::Dispute::Event::Data::CardholderLiabilityEventData::action,
              amount: Integer,
              reason: String
            }

          class CardholderLiabilityEventData < Lithic::Internal::Type::BaseModel
            attr_accessor action: Lithic::Models::Dispute::Event::Data::CardholderLiabilityEventData::action

            attr_accessor amount: Integer

            attr_accessor reason: String

            def initialize: (
              action: Lithic::Models::Dispute::Event::Data::CardholderLiabilityEventData::action,
              amount: Integer,
              reason: String
            ) -> void

            def to_hash: -> {
              action: Lithic::Models::Dispute::Event::Data::CardholderLiabilityEventData::action,
              amount: Integer,
              reason: String
            }

            type action =
              :PROVISIONAL_CREDIT_GRANTED
              | :PROVISIONAL_CREDIT_REVERSED
              | :WRITTEN_OFF

            module Action
              extend Lithic::Internal::Type::Enum

              PROVISIONAL_CREDIT_GRANTED: :PROVISIONAL_CREDIT_GRANTED
              PROVISIONAL_CREDIT_REVERSED: :PROVISIONAL_CREDIT_REVERSED
              WRITTEN_OFF: :WRITTEN_OFF

              def self?.values: -> ::Array[Lithic::Models::Dispute::Event::Data::CardholderLiabilityEventData::action]
            end
          end

          def self?.variants: -> ::Array[Lithic::Models::Dispute::Event::data]
        end

        type type_ = :WORKFLOW | :FINANCIAL | :CARDHOLDER_LIABILITY

        module Type
          extend Lithic::Internal::Type::Enum

          WORKFLOW: :WORKFLOW
          FINANCIAL: :FINANCIAL
          CARDHOLDER_LIABILITY: :CARDHOLDER_LIABILITY

          def self?.values: -> ::Array[Lithic::Models::Dispute::Event::type_]
        end
      end

      type liability_allocation =
        {
          denied_amount: Integer,
          original_amount: Integer,
          recovered_amount: Integer,
          remaining_amount: Integer,
          written_off_amount: Integer
        }

      class LiabilityAllocation < Lithic::Internal::Type::BaseModel
        attr_accessor denied_amount: Integer

        attr_accessor original_amount: Integer

        attr_accessor recovered_amount: Integer

        attr_accessor remaining_amount: Integer

        attr_accessor written_off_amount: Integer

        def initialize: (
          denied_amount: Integer,
          original_amount: Integer,
          recovered_amount: Integer,
          remaining_amount: Integer,
          written_off_amount: Integer
        ) -> void

        def to_hash: -> {
          denied_amount: Integer,
          original_amount: Integer,
          recovered_amount: Integer,
          remaining_amount: Integer,
          written_off_amount: Integer
        }
      end

      type merchant =
        {
          acceptor_id: String,
          acquiring_institution_id: String,
          city: String,
          country: String,
          descriptor: String,
          mcc: String,
          state: String
        }

      class Merchant < Lithic::Internal::Type::BaseModel
        attr_accessor acceptor_id: String

        attr_accessor acquiring_institution_id: String

        attr_accessor city: String

        attr_accessor country: String

        attr_accessor descriptor: String

        attr_accessor mcc: String

        attr_accessor state: String

        def initialize: (
          acceptor_id: String,
          acquiring_institution_id: String,
          city: String,
          country: String,
          descriptor: String,
          mcc: String,
          state: String
        ) -> void

        def to_hash: -> {
          acceptor_id: String,
          acquiring_institution_id: String,
          city: String,
          country: String,
          descriptor: String,
          mcc: String,
          state: String
        }
      end

      type network = :VISA | :MASTERCARD

      module Network
        extend Lithic::Internal::Type::Enum

        VISA: :VISA
        MASTERCARD: :MASTERCARD

        def self?.values: -> ::Array[Lithic::Models::Dispute::network]
      end

      type status = :OPEN | :CLOSED

      module Status
        extend Lithic::Internal::Type::Enum

        OPEN: :OPEN
        CLOSED: :CLOSED

        def self?.values: -> ::Array[Lithic::Models::Dispute::status]
      end

      type transaction_series =
        {
          related_transaction_event_token: String?,
          related_transaction_token: String,
          type: Lithic::Models::Dispute::TransactionSeries::type_
        }

      class TransactionSeries < Lithic::Internal::Type::BaseModel
        attr_accessor related_transaction_event_token: String?

        attr_accessor related_transaction_token: String

        attr_accessor type: Lithic::Models::Dispute::TransactionSeries::type_

        def initialize: (
          related_transaction_event_token: String?,
          related_transaction_token: String,
          type: Lithic::Models::Dispute::TransactionSeries::type_
        ) -> void

        def to_hash: -> {
          related_transaction_event_token: String?,
          related_transaction_token: String,
          type: Lithic::Models::Dispute::TransactionSeries::type_
        }

        type type_ = :DISPUTE

        module Type
          extend Lithic::Internal::Type::Enum

          DISPUTE: :DISPUTE

          def self?.values: -> ::Array[Lithic::Models::Dispute::TransactionSeries::type_]
        end
      end
    end
  end
end
