module Lithic
  module Models
    type dispute_initiate_evidence_upload_params =
      { filename: String } & Lithic::Internal::Type::request_parameters

    class DisputeInitiateEvidenceUploadParams < Lithic::Internal::Type::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_reader filename: String?

      def filename=: (String) -> String

      def initialize: (
        ?filename: String,
        ?request_options: Lithic::request_opts
      ) -> void
    end
  end
end
