module Lithic
  module Models
    type dispute_transaction_updated_webhook_event =
      { event_type: :"dispute_transaction.updated" }

    class DisputeTransactionUpdatedWebhookEvent < Lithic::Models::DisputeV2
      def event_type: -> :"dispute_transaction.updated"

      def event_type=: (
        :"dispute_transaction.updated" _
      ) -> :"dispute_transaction.updated"

      def initialize: (?event_type: :"dispute_transaction.updated") -> void

      def to_hash: -> { event_type: :"dispute_transaction.updated" }
    end
  end
end
