module Lithic
  module Models
    type embed_session_generated_webhook_event =
      {
        account_token: String,
        card_token: String,
        device_details: Lithic::EmbedSessionGeneratedWebhookEvent::DeviceDetails,
        event_type: :"embed.session_generated",
        session_id: String,
        session_type: Lithic::Models::EmbedSessionGeneratedWebhookEvent::session_type
      }

    class EmbedSessionGeneratedWebhookEvent < Lithic::Internal::Type::BaseModel
      attr_accessor account_token: String

      attr_accessor card_token: String

      attr_accessor device_details: Lithic::EmbedSessionGeneratedWebhookEvent::DeviceDetails

      attr_accessor event_type: :"embed.session_generated"

      attr_accessor session_id: String

      attr_accessor session_type: Lithic::Models::EmbedSessionGeneratedWebhookEvent::session_type

      def initialize: (
        account_token: String,
        card_token: String,
        device_details: Lithic::EmbedSessionGeneratedWebhookEvent::DeviceDetails,
        session_id: String,
        session_type: Lithic::Models::EmbedSessionGeneratedWebhookEvent::session_type,
        ?event_type: :"embed.session_generated"
      ) -> void

      def to_hash: -> {
        account_token: String,
        card_token: String,
        device_details: Lithic::EmbedSessionGeneratedWebhookEvent::DeviceDetails,
        event_type: :"embed.session_generated",
        session_id: String,
        session_type: Lithic::Models::EmbedSessionGeneratedWebhookEvent::session_type
      }

      type device_details = { ip_address: String }

      class DeviceDetails < Lithic::Internal::Type::BaseModel
        attr_accessor ip_address: String

        def initialize: (ip_address: String) -> void

        def to_hash: -> { ip_address: String }
      end

      type session_type = :CARD_EMBED | :PIN_SETTING_EMBED

      module SessionType
        extend Lithic::Internal::Type::Enum

        CARD_EMBED: :CARD_EMBED
        PIN_SETTING_EMBED: :PIN_SETTING_EMBED

        def self?.values: -> ::Array[Lithic::Models::EmbedSessionGeneratedWebhookEvent::session_type]
      end
    end
  end
end
