module Lithic
  module Models
    type external_payment_release_params =
      { effective_date: Date, memo: String }
      & Lithic::Internal::Type::request_parameters

    class ExternalPaymentReleaseParams < Lithic::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_accessor effective_date: Date

      attr_reader memo: String?

      def memo=: (String) -> String

      def initialize: (
        effective_date: Date,
        ?memo: String,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> Lithic::Models::external_payment_release_params
    end
  end
end
