module Lithic
  module Models
    type external_bank_account_retry_micro_deposits_params =
      { financial_account_token: String }
      & Lithic::Internal::Type::request_parameters

    class ExternalBankAccountRetryMicroDepositsParams < Lithic::Internal::Type::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_reader financial_account_token: String?

      def financial_account_token=: (String) -> String

      def initialize: (
        ?financial_account_token: String,
        ?request_options: Lithic::request_opts
      ) -> void
    end
  end
end
