module Lithic
  module Models
    type external_payment_retrieve_params =
      { external_payment_token: String }
      & Lithic::Internal::Type::request_parameters

    class ExternalPaymentRetrieveParams < Lithic::Internal::Type::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_accessor external_payment_token: String

      def initialize: (
        external_payment_token: String,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> {
        external_payment_token: String,
        request_options: Lithic::RequestOptions
      }
    end
  end
end
