module Lithic
  module Models
    type financial_account =
      {
        token: String,
        account_token: String?,
        created: Time,
        credit_configuration: Lithic::FinancialAccount::CreditConfiguration?,
        is_for_benefit_of: bool,
        nickname: String?,
        status: Lithic::Models::FinancialAccount::status,
        type: Lithic::Models::FinancialAccount::type_,
        updated: Time,
        account_number: String?,
        routing_number: String?,
        substatus: Lithic::Models::FinancialAccount::substatus?
      }

    class FinancialAccount < Lithic::Internal::Type::BaseModel
      attr_accessor token: String

      attr_accessor account_token: String?

      attr_accessor created: Time

      attr_accessor credit_configuration: Lithic::FinancialAccount::CreditConfiguration?

      attr_accessor is_for_benefit_of: bool

      attr_accessor nickname: String?

      attr_accessor status: Lithic::Models::FinancialAccount::status

      attr_accessor type: Lithic::Models::FinancialAccount::type_

      attr_accessor updated: Time

      attr_accessor account_number: String?

      attr_accessor routing_number: String?

      attr_accessor substatus: Lithic::Models::FinancialAccount::substatus?

      def initialize: (
        token: String,
        account_token: String?,
        created: Time,
        credit_configuration: Lithic::FinancialAccount::CreditConfiguration?,
        is_for_benefit_of: bool,
        nickname: String?,
        status: Lithic::Models::FinancialAccount::status,
        type: Lithic::Models::FinancialAccount::type_,
        updated: Time,
        ?account_number: String?,
        ?routing_number: String?,
        ?substatus: Lithic::Models::FinancialAccount::substatus?
      ) -> void

      def to_hash: -> {
        token: String,
        account_token: String?,
        created: Time,
        credit_configuration: Lithic::FinancialAccount::CreditConfiguration?,
        is_for_benefit_of: bool,
        nickname: String?,
        status: Lithic::Models::FinancialAccount::status,
        type: Lithic::Models::FinancialAccount::type_,
        updated: Time,
        account_number: String?,
        routing_number: String?,
        substatus: Lithic::Models::FinancialAccount::substatus?
      }

      type credit_configuration =
        {
          auto_collection_configuration: Lithic::FinancialAccount::CreditConfiguration::AutoCollectionConfiguration,
          credit_limit: Integer?,
          credit_product_token: String?,
          external_bank_account_token: String?,
          tier: String?,
          charged_off_reason: Lithic::Models::FinancialAccount::CreditConfiguration::charged_off_reason?,
          financial_account_state: Lithic::Models::FinancialAccount::CreditConfiguration::financial_account_state?,
          is_spend_blocked: bool
        }

      class CreditConfiguration < Lithic::Internal::Type::BaseModel
        attr_accessor auto_collection_configuration: Lithic::FinancialAccount::CreditConfiguration::AutoCollectionConfiguration

        attr_accessor credit_limit: Integer?

        attr_accessor credit_product_token: String?

        attr_accessor external_bank_account_token: String?

        attr_accessor tier: String?

        attr_accessor charged_off_reason: Lithic::Models::FinancialAccount::CreditConfiguration::charged_off_reason?

        attr_accessor financial_account_state: Lithic::Models::FinancialAccount::CreditConfiguration::financial_account_state?

        attr_reader is_spend_blocked: bool?

        def is_spend_blocked=: (bool) -> bool

        def initialize: (
          auto_collection_configuration: Lithic::FinancialAccount::CreditConfiguration::AutoCollectionConfiguration,
          credit_limit: Integer?,
          credit_product_token: String?,
          external_bank_account_token: String?,
          tier: String?,
          ?charged_off_reason: Lithic::Models::FinancialAccount::CreditConfiguration::charged_off_reason?,
          ?financial_account_state: Lithic::Models::FinancialAccount::CreditConfiguration::financial_account_state?,
          ?is_spend_blocked: bool
        ) -> void

        def to_hash: -> {
          auto_collection_configuration: Lithic::FinancialAccount::CreditConfiguration::AutoCollectionConfiguration,
          credit_limit: Integer?,
          credit_product_token: String?,
          external_bank_account_token: String?,
          tier: String?,
          charged_off_reason: Lithic::Models::FinancialAccount::CreditConfiguration::charged_off_reason?,
          financial_account_state: Lithic::Models::FinancialAccount::CreditConfiguration::financial_account_state?,
          is_spend_blocked: bool
        }

        type auto_collection_configuration = { auto_collection_enabled: bool }

        class AutoCollectionConfiguration < Lithic::Internal::Type::BaseModel
          attr_accessor auto_collection_enabled: bool

          def initialize: (auto_collection_enabled: bool) -> void

          def to_hash: -> { auto_collection_enabled: bool }
        end

        type charged_off_reason = :DELINQUENT | :FRAUD

        module ChargedOffReason
          extend Lithic::Internal::Type::Enum

          DELINQUENT: :DELINQUENT
          FRAUD: :FRAUD

          def self?.values: -> ::Array[Lithic::Models::FinancialAccount::CreditConfiguration::charged_off_reason]
        end

        type financial_account_state =
          :PENDING | :CURRENT | :DELINQUENT | :CHARGED_OFF

        module FinancialAccountState
          extend Lithic::Internal::Type::Enum

          PENDING: :PENDING
          CURRENT: :CURRENT
          DELINQUENT: :DELINQUENT
          CHARGED_OFF: :CHARGED_OFF

          def self?.values: -> ::Array[Lithic::Models::FinancialAccount::CreditConfiguration::financial_account_state]
        end
      end

      type status = :OPEN | :CLOSED | :SUSPENDED | :PENDING

      module Status
        extend Lithic::Internal::Type::Enum

        OPEN: :OPEN
        CLOSED: :CLOSED
        SUSPENDED: :SUSPENDED
        PENDING: :PENDING

        def self?.values: -> ::Array[Lithic::Models::FinancialAccount::status]
      end

      type type_ =
        :ISSUING
        | :RESERVE
        | :OPERATING
        | :CHARGED_OFF_FEES
        | :CHARGED_OFF_INTEREST
        | :CHARGED_OFF_PRINCIPAL
        | :SECURITY
        | :PROGRAM_RECEIVABLES
        | :COLLECTION
        | :PROGRAM_BANK_ACCOUNTS_PAYABLE

      module Type
        extend Lithic::Internal::Type::Enum

        ISSUING: :ISSUING
        RESERVE: :RESERVE
        OPERATING: :OPERATING
        CHARGED_OFF_FEES: :CHARGED_OFF_FEES
        CHARGED_OFF_INTEREST: :CHARGED_OFF_INTEREST
        CHARGED_OFF_PRINCIPAL: :CHARGED_OFF_PRINCIPAL
        SECURITY: :SECURITY
        PROGRAM_RECEIVABLES: :PROGRAM_RECEIVABLES
        COLLECTION: :COLLECTION
        PROGRAM_BANK_ACCOUNTS_PAYABLE: :PROGRAM_BANK_ACCOUNTS_PAYABLE

        def self?.values: -> ::Array[Lithic::Models::FinancialAccount::type_]
      end

      type substatus =
        :CHARGED_OFF_DELINQUENT
        | :CHARGED_OFF_FRAUD
        | :END_USER_REQUEST
        | :BANK_REQUEST
        | :DELINQUENT

      module Substatus
        extend Lithic::Internal::Type::Enum

        CHARGED_OFF_DELINQUENT: :CHARGED_OFF_DELINQUENT
        CHARGED_OFF_FRAUD: :CHARGED_OFF_FRAUD
        END_USER_REQUEST: :END_USER_REQUEST
        BANK_REQUEST: :BANK_REQUEST
        DELINQUENT: :DELINQUENT

        def self?.values: -> ::Array[Lithic::Models::FinancialAccount::substatus]
      end
    end
  end
end
