module Lithic
  module Models
    type financial_account_updated_webhook_event =
      { event_type: :"financial_account.updated" }

    class FinancialAccountUpdatedWebhookEvent < Lithic::Models::FinancialAccount
      def event_type: -> :"financial_account.updated"

      def event_type=: (
        :"financial_account.updated" _
      ) -> :"financial_account.updated"

      def initialize: (?event_type: :"financial_account.updated") -> void

      def to_hash: -> { event_type: :"financial_account.updated" }
    end
  end
end
