module Lithic
  module Models
    type financial_transaction =
      {
        token: String,
        category: Lithic::Models::FinancialTransaction::category,
        created: Time,
        currency: String,
        descriptor: String,
        events: ::Array[Lithic::FinancialEvent],
        pending_amount: Integer,
        result: Lithic::Models::FinancialTransaction::result,
        settled_amount: Integer,
        status: Lithic::Models::FinancialTransaction::status,
        updated: Time
      }

    class FinancialTransaction < Lithic::Internal::Type::BaseModel
      attr_accessor token: String

      attr_accessor category: Lithic::Models::FinancialTransaction::category

      attr_accessor created: Time

      attr_accessor currency: String

      attr_accessor descriptor: String

      attr_accessor events: ::Array[Lithic::FinancialEvent]

      attr_accessor pending_amount: Integer

      attr_accessor result: Lithic::Models::FinancialTransaction::result

      attr_accessor settled_amount: Integer

      attr_accessor status: Lithic::Models::FinancialTransaction::status

      attr_accessor updated: Time

      def initialize: (
        token: String,
        category: Lithic::Models::FinancialTransaction::category,
        created: Time,
        currency: String,
        descriptor: String,
        events: ::Array[Lithic::FinancialEvent],
        pending_amount: Integer,
        result: Lithic::Models::FinancialTransaction::result,
        settled_amount: Integer,
        status: Lithic::Models::FinancialTransaction::status,
        updated: Time
      ) -> void

      def to_hash: -> {
        token: String,
        category: Lithic::Models::FinancialTransaction::category,
        created: Time,
        currency: String,
        descriptor: String,
        events: ::Array[Lithic::FinancialEvent],
        pending_amount: Integer,
        result: Lithic::Models::FinancialTransaction::result,
        settled_amount: Integer,
        status: Lithic::Models::FinancialTransaction::status,
        updated: Time
      }

      type category = :ACH | :CARD | :INTERNAL | :TRANSFER

      module Category
        extend Lithic::Internal::Type::Enum

        ACH: :ACH
        CARD: :CARD
        INTERNAL: :INTERNAL
        TRANSFER: :TRANSFER

        def self?.values: -> ::Array[Lithic::Models::FinancialTransaction::category]
      end

      type result = :APPROVED | :DECLINED

      module Result
        extend Lithic::Internal::Type::Enum

        APPROVED: :APPROVED
        DECLINED: :DECLINED

        def self?.values: -> ::Array[Lithic::Models::FinancialTransaction::result]
      end

      type status =
        :DECLINED | :EXPIRED | :PENDING | :RETURNED | :SETTLED | :VOIDED

      module Status
        extend Lithic::Internal::Type::Enum

        DECLINED: :DECLINED
        EXPIRED: :EXPIRED
        PENDING: :PENDING
        RETURNED: :RETURNED
        SETTLED: :SETTLED
        VOIDED: :VOIDED

        def self?.values: -> ::Array[Lithic::Models::FinancialTransaction::status]
      end
    end
  end
end
