module Lithic
  module Models
    type hold_retrieve_params =
      { hold_token: String } & Lithic::Internal::Type::request_parameters

    class HoldRetrieveParams < Lithic::Internal::Type::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_accessor hold_token: String

      def initialize: (
        hold_token: String,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> {
        hold_token: String,
        request_options: Lithic::RequestOptions
      }
    end
  end
end
