module Lithic
  module Models
    type kyc =
      {
        individual: Lithic::Models::KYC::Individual,
        tos_timestamp: String,
        workflow: Lithic::Models::KYC::workflow,
        external_id: String,
        kyc_passed_timestamp: String
      }

    class KYC < Lithic::BaseModel
      attr_accessor individual: Lithic::Models::KYC::Individual

      attr_accessor tos_timestamp: String

      attr_accessor workflow: Lithic::Models::KYC::workflow

      attr_reader external_id: String?

      def external_id=: (String) -> String

      attr_reader kyc_passed_timestamp: String?

      def kyc_passed_timestamp=: (String) -> String

      def initialize: (
        individual: Lithic::Models::KYC::Individual,
        tos_timestamp: String,
        workflow: Lithic::Models::KYC::workflow,
        ?external_id: String,
        ?kyc_passed_timestamp: String
      ) -> void

      def to_hash: -> Lithic::Models::kyc

      type individual =
        {
          address: Lithic::Models::Address,
          dob: String,
          email: String,
          first_name: String,
          government_id: String,
          last_name: String,
          phone_number: String
        }

      class Individual < Lithic::BaseModel
        attr_accessor address: Lithic::Models::Address

        attr_accessor dob: String

        attr_accessor email: String

        attr_accessor first_name: String

        attr_accessor government_id: String

        attr_accessor last_name: String

        attr_accessor phone_number: String

        def initialize: (
          address: Lithic::Models::Address,
          dob: String,
          email: String,
          first_name: String,
          government_id: String,
          last_name: String,
          phone_number: String
        ) -> void

        def to_hash: -> Lithic::Models::KYC::individual
      end

      type workflow = :KYC_BASIC | :KYC_BYO

      module Workflow
        extend Lithic::Enum

        KYC_BASIC: :KYC_BASIC
        KYC_BYO: :KYC_BYO

        def self?.values: -> ::Array[Lithic::Models::KYC::workflow]
      end
    end
  end
end
