module Lithic
  module Models
    type loan_tape_created_webhook_event = { event_type: :"loan_tape.created" }

    class LoanTapeCreatedWebhookEvent < Lithic::Models::FinancialAccounts::LoanTape
      def event_type: -> :"loan_tape.created"

      def event_type=: (:"loan_tape.created" _) -> :"loan_tape.created"

      def initialize: (?event_type: :"loan_tape.created") -> void

      def to_hash: -> { event_type: :"loan_tape.created" }
    end
  end
end
