module Lithic
  module Models
    type management_operation_transaction =
      {
        token: String,
        created: Time,
        status: Lithic::Models::ManagementOperationTransaction::status,
        updated: Time,
        category: Lithic::Models::ManagementOperationTransaction::category,
        currency: String,
        direction: Lithic::Models::ManagementOperationTransaction::direction,
        events: ::Array[Lithic::ManagementOperationTransaction::Event],
        external_resource: Lithic::ExternalResource?,
        family: Lithic::Models::ManagementOperationTransaction::family,
        financial_account_token: String,
        pending_amount: Integer,
        result: Lithic::Models::ManagementOperationTransaction::result,
        settled_amount: Integer,
        transaction_series: Lithic::ManagementOperationTransaction::TransactionSeries?,
        user_defined_id: String?
      }

    class ManagementOperationTransaction < Lithic::Internal::Type::BaseModel
      attr_accessor token: String

      attr_accessor created: Time

      attr_accessor status: Lithic::Models::ManagementOperationTransaction::status

      attr_accessor updated: Time

      attr_reader category: Lithic::Models::ManagementOperationTransaction::category?

      def category=: (
        Lithic::Models::ManagementOperationTransaction::category
      ) -> Lithic::Models::ManagementOperationTransaction::category

      attr_reader currency: String?

      def currency=: (String) -> String

      attr_reader direction: Lithic::Models::ManagementOperationTransaction::direction?

      def direction=: (
        Lithic::Models::ManagementOperationTransaction::direction
      ) -> Lithic::Models::ManagementOperationTransaction::direction

      attr_reader events: ::Array[Lithic::ManagementOperationTransaction::Event]?

      def events=: (
        ::Array[Lithic::ManagementOperationTransaction::Event]
      ) -> ::Array[Lithic::ManagementOperationTransaction::Event]

      attr_accessor external_resource: Lithic::ExternalResource?

      attr_reader family: Lithic::Models::ManagementOperationTransaction::family?

      def family=: (
        Lithic::Models::ManagementOperationTransaction::family
      ) -> Lithic::Models::ManagementOperationTransaction::family

      attr_reader financial_account_token: String?

      def financial_account_token=: (String) -> String

      attr_reader pending_amount: Integer?

      def pending_amount=: (Integer) -> Integer

      attr_reader result: Lithic::Models::ManagementOperationTransaction::result?

      def result=: (
        Lithic::Models::ManagementOperationTransaction::result
      ) -> Lithic::Models::ManagementOperationTransaction::result

      attr_reader settled_amount: Integer?

      def settled_amount=: (Integer) -> Integer

      attr_accessor transaction_series: Lithic::ManagementOperationTransaction::TransactionSeries?

      attr_accessor user_defined_id: String?

      def initialize: (
        token: String,
        created: Time,
        status: Lithic::Models::ManagementOperationTransaction::status,
        updated: Time,
        ?category: Lithic::Models::ManagementOperationTransaction::category,
        ?currency: String,
        ?direction: Lithic::Models::ManagementOperationTransaction::direction,
        ?events: ::Array[Lithic::ManagementOperationTransaction::Event],
        ?external_resource: Lithic::ExternalResource?,
        ?family: Lithic::Models::ManagementOperationTransaction::family,
        ?financial_account_token: String,
        ?pending_amount: Integer,
        ?result: Lithic::Models::ManagementOperationTransaction::result,
        ?settled_amount: Integer,
        ?transaction_series: Lithic::ManagementOperationTransaction::TransactionSeries?,
        ?user_defined_id: String?
      ) -> void

      def to_hash: -> {
        token: String,
        created: Time,
        status: Lithic::Models::ManagementOperationTransaction::status,
        updated: Time,
        category: Lithic::Models::ManagementOperationTransaction::category,
        currency: String,
        direction: Lithic::Models::ManagementOperationTransaction::direction,
        events: ::Array[Lithic::ManagementOperationTransaction::Event],
        external_resource: Lithic::ExternalResource?,
        family: Lithic::Models::ManagementOperationTransaction::family,
        financial_account_token: String,
        pending_amount: Integer,
        result: Lithic::Models::ManagementOperationTransaction::result,
        settled_amount: Integer,
        transaction_series: Lithic::ManagementOperationTransaction::TransactionSeries?,
        user_defined_id: String?
      }

      type status =
        :PENDING | :SETTLED | :DECLINED | :REVERSED | :CANCELED | :RETURNED

      module Status
        extend Lithic::Internal::Type::Enum

        PENDING: :PENDING
        SETTLED: :SETTLED
        DECLINED: :DECLINED
        REVERSED: :REVERSED
        CANCELED: :CANCELED
        RETURNED: :RETURNED

        def self?.values: -> ::Array[Lithic::Models::ManagementOperationTransaction::status]
      end

      type category =
        :MANAGEMENT_FEE
        | :MANAGEMENT_DISPUTE
        | :MANAGEMENT_REWARD
        | :MANAGEMENT_ADJUSTMENT
        | :MANAGEMENT_DISBURSEMENT

      module Category
        extend Lithic::Internal::Type::Enum

        MANAGEMENT_FEE: :MANAGEMENT_FEE
        MANAGEMENT_DISPUTE: :MANAGEMENT_DISPUTE
        MANAGEMENT_REWARD: :MANAGEMENT_REWARD
        MANAGEMENT_ADJUSTMENT: :MANAGEMENT_ADJUSTMENT
        MANAGEMENT_DISBURSEMENT: :MANAGEMENT_DISBURSEMENT

        def self?.values: -> ::Array[Lithic::Models::ManagementOperationTransaction::category]
      end

      type direction = :CREDIT | :DEBIT

      module Direction
        extend Lithic::Internal::Type::Enum

        CREDIT: :CREDIT
        DEBIT: :DEBIT

        def self?.values: -> ::Array[Lithic::Models::ManagementOperationTransaction::direction]
      end

      type event =
        {
          token: String,
          amount: Integer,
          created: Time,
          detailed_results: ::Array[Lithic::Models::ManagementOperationTransaction::Event::detailed_result],
          effective_date: Date,
          memo: String,
          result: Lithic::Models::ManagementOperationTransaction::Event::result,
          type: Lithic::Models::ManagementOperationTransaction::Event::type_,
          subtype: String?
        }

      class Event < Lithic::Internal::Type::BaseModel
        attr_accessor token: String

        attr_accessor amount: Integer

        attr_accessor created: Time

        attr_accessor detailed_results: ::Array[Lithic::Models::ManagementOperationTransaction::Event::detailed_result]

        attr_accessor effective_date: Date

        attr_accessor memo: String

        attr_accessor result: Lithic::Models::ManagementOperationTransaction::Event::result

        attr_accessor type: Lithic::Models::ManagementOperationTransaction::Event::type_

        attr_accessor subtype: String?

        def initialize: (
          token: String,
          amount: Integer,
          created: Time,
          detailed_results: ::Array[Lithic::Models::ManagementOperationTransaction::Event::detailed_result],
          effective_date: Date,
          memo: String,
          result: Lithic::Models::ManagementOperationTransaction::Event::result,
          type: Lithic::Models::ManagementOperationTransaction::Event::type_,
          ?subtype: String?
        ) -> void

        def to_hash: -> {
          token: String,
          amount: Integer,
          created: Time,
          detailed_results: ::Array[Lithic::Models::ManagementOperationTransaction::Event::detailed_result],
          effective_date: Date,
          memo: String,
          result: Lithic::Models::ManagementOperationTransaction::Event::result,
          type: Lithic::Models::ManagementOperationTransaction::Event::type_,
          subtype: String?
        }

        type detailed_result = :APPROVED | :INSUFFICIENT_FUNDS

        module DetailedResult
          extend Lithic::Internal::Type::Enum

          APPROVED: :APPROVED
          INSUFFICIENT_FUNDS: :INSUFFICIENT_FUNDS

          def self?.values: -> ::Array[Lithic::Models::ManagementOperationTransaction::Event::detailed_result]
        end

        type result = :APPROVED | :DECLINED

        module Result
          extend Lithic::Internal::Type::Enum

          APPROVED: :APPROVED
          DECLINED: :DECLINED

          def self?.values: -> ::Array[Lithic::Models::ManagementOperationTransaction::Event::result]
        end

        type type_ =
          :LOSS_WRITE_OFF
          | :CASH_BACK
          | :CASH_BACK_REVERSAL
          | :CURRENCY_CONVERSION
          | :CURRENCY_CONVERSION_REVERSAL
          | :INTEREST
          | :INTEREST_REVERSAL
          | :LATE_PAYMENT
          | :LATE_PAYMENT_REVERSAL
          | :BILLING_ERROR
          | :BILLING_ERROR_REVERSAL
          | :PROVISIONAL_CREDIT
          | :PROVISIONAL_CREDIT_REVERSAL
          | :RETURNED_PAYMENT
          | :RETURNED_PAYMENT_REVERSAL
          | :DISPUTE_WON
          | :DISPUTE_WON_REVERSAL
          | :DISBURSE
          | :DISBURSE_REVERSAL

        module Type
          extend Lithic::Internal::Type::Enum

          LOSS_WRITE_OFF: :LOSS_WRITE_OFF
          CASH_BACK: :CASH_BACK
          CASH_BACK_REVERSAL: :CASH_BACK_REVERSAL
          CURRENCY_CONVERSION: :CURRENCY_CONVERSION
          CURRENCY_CONVERSION_REVERSAL: :CURRENCY_CONVERSION_REVERSAL
          INTEREST: :INTEREST
          INTEREST_REVERSAL: :INTEREST_REVERSAL
          LATE_PAYMENT: :LATE_PAYMENT
          LATE_PAYMENT_REVERSAL: :LATE_PAYMENT_REVERSAL
          BILLING_ERROR: :BILLING_ERROR
          BILLING_ERROR_REVERSAL: :BILLING_ERROR_REVERSAL
          PROVISIONAL_CREDIT: :PROVISIONAL_CREDIT
          PROVISIONAL_CREDIT_REVERSAL: :PROVISIONAL_CREDIT_REVERSAL
          RETURNED_PAYMENT: :RETURNED_PAYMENT
          RETURNED_PAYMENT_REVERSAL: :RETURNED_PAYMENT_REVERSAL
          DISPUTE_WON: :DISPUTE_WON
          DISPUTE_WON_REVERSAL: :DISPUTE_WON_REVERSAL
          DISBURSE: :DISBURSE
          DISBURSE_REVERSAL: :DISBURSE_REVERSAL

          def self?.values: -> ::Array[Lithic::Models::ManagementOperationTransaction::Event::type_]
        end
      end

      type family = :MANAGEMENT_OPERATION

      module Family
        extend Lithic::Internal::Type::Enum

        MANAGEMENT_OPERATION: :MANAGEMENT_OPERATION

        def self?.values: -> ::Array[Lithic::Models::ManagementOperationTransaction::family]
      end

      type result = :APPROVED | :DECLINED

      module Result
        extend Lithic::Internal::Type::Enum

        APPROVED: :APPROVED
        DECLINED: :DECLINED

        def self?.values: -> ::Array[Lithic::Models::ManagementOperationTransaction::result]
      end

      type transaction_series =
        {
          related_transaction_event_token: String?,
          related_transaction_token: String?,
          type: String
        }

      class TransactionSeries < Lithic::Internal::Type::BaseModel
        attr_accessor related_transaction_event_token: String?

        attr_accessor related_transaction_token: String?

        attr_accessor type: String

        def initialize: (
          related_transaction_event_token: String?,
          related_transaction_token: String?,
          type: String
        ) -> void

        def to_hash: -> {
          related_transaction_event_token: String?,
          related_transaction_token: String?,
          type: String
        }
      end
    end
  end
end
