module Lithic
  module Models
    type owner_type = :INDIVIDUAL | :BUSINESS

    module OwnerType
      extend Lithic::Enum

      INDIVIDUAL: :INDIVIDUAL
      BUSINESS: :BUSINESS

      def self?.values: -> ::Array[Lithic::Models::owner_type]
    end
  end
end
