module Lithic
  module Models
    type payment_return_response =
      {
        result: Lithic::Models::PaymentReturnResponse::result,
        transaction_group_uuid: String,
        transaction_uuid: String
      }

    class PaymentReturnResponse < Lithic::Internal::Type::BaseModel
      attr_accessor result: Lithic::Models::PaymentReturnResponse::result

      attr_accessor transaction_group_uuid: String

      attr_accessor transaction_uuid: String

      def initialize: (
        result: Lithic::Models::PaymentReturnResponse::result,
        transaction_group_uuid: String,
        transaction_uuid: String
      ) -> void

      def to_hash: -> {
        result: Lithic::Models::PaymentReturnResponse::result,
        transaction_group_uuid: String,
        transaction_uuid: String
      }

      type result = :APPROVED | :DECLINED

      module Result
        extend Lithic::Internal::Type::Enum

        APPROVED: :APPROVED
        DECLINED: :DECLINED

        def self?.values: -> ::Array[Lithic::Models::PaymentReturnResponse::result]
      end
    end
  end
end
