module Lithic
  module Models
    type payment =
      {
        token: String,
        category: Lithic::Models::Payment::category,
        created: Time,
        descriptor: String,
        direction: Lithic::Models::Payment::direction,
        events: ::Array[Lithic::Payment::Event],
        family: :PAYMENT,
        financial_account_token: String,
        method_: Lithic::Models::Payment::method_,
        method_attributes: Lithic::Models::Payment::method_attributes,
        pending_amount: Integer,
        related_account_tokens: Lithic::Payment::RelatedAccountTokens?,
        result: Lithic::Models::Payment::result,
        settled_amount: Integer,
        source: Lithic::Models::Payment::source,
        status: Lithic::Models::Payment::status,
        updated: Time,
        currency: String,
        expected_release_date: Date?,
        external_bank_account_token: String?,
        type: Lithic::Models::Payment::type_,
        user_defined_id: String?
      }

    class Payment < Lithic::Internal::Type::BaseModel
      attr_accessor token: String

      attr_accessor category: Lithic::Models::Payment::category

      attr_accessor created: Time

      attr_accessor descriptor: String

      attr_accessor direction: Lithic::Models::Payment::direction

      attr_accessor events: ::Array[Lithic::Payment::Event]

      attr_accessor family: :PAYMENT

      attr_accessor financial_account_token: String

      attr_accessor method_: Lithic::Models::Payment::method_

      attr_accessor method_attributes: Lithic::Models::Payment::method_attributes

      attr_accessor pending_amount: Integer

      attr_accessor related_account_tokens: Lithic::Payment::RelatedAccountTokens?

      attr_accessor result: Lithic::Models::Payment::result

      attr_accessor settled_amount: Integer

      attr_accessor source: Lithic::Models::Payment::source

      attr_accessor status: Lithic::Models::Payment::status

      attr_accessor updated: Time

      attr_reader currency: String?

      def currency=: (String) -> String

      attr_accessor expected_release_date: Date?

      attr_accessor external_bank_account_token: String?

      attr_reader type: Lithic::Models::Payment::type_?

      def type=: (
        Lithic::Models::Payment::type_
      ) -> Lithic::Models::Payment::type_

      attr_accessor user_defined_id: String?

      def initialize: (
        token: String,
        category: Lithic::Models::Payment::category,
        created: Time,
        descriptor: String,
        direction: Lithic::Models::Payment::direction,
        events: ::Array[Lithic::Payment::Event],
        financial_account_token: String,
        method_: Lithic::Models::Payment::method_,
        method_attributes: Lithic::Models::Payment::method_attributes,
        pending_amount: Integer,
        related_account_tokens: Lithic::Payment::RelatedAccountTokens?,
        result: Lithic::Models::Payment::result,
        settled_amount: Integer,
        source: Lithic::Models::Payment::source,
        status: Lithic::Models::Payment::status,
        updated: Time,
        ?currency: String,
        ?expected_release_date: Date?,
        ?external_bank_account_token: String?,
        ?type: Lithic::Models::Payment::type_,
        ?user_defined_id: String?,
        ?family: :PAYMENT
      ) -> void

      def to_hash: -> {
        token: String,
        category: Lithic::Models::Payment::category,
        created: Time,
        descriptor: String,
        direction: Lithic::Models::Payment::direction,
        events: ::Array[Lithic::Payment::Event],
        family: :PAYMENT,
        financial_account_token: String,
        method_: Lithic::Models::Payment::method_,
        method_attributes: Lithic::Models::Payment::method_attributes,
        pending_amount: Integer,
        related_account_tokens: Lithic::Payment::RelatedAccountTokens?,
        result: Lithic::Models::Payment::result,
        settled_amount: Integer,
        source: Lithic::Models::Payment::source,
        status: Lithic::Models::Payment::status,
        updated: Time,
        currency: String,
        expected_release_date: Date?,
        external_bank_account_token: String?,
        type: Lithic::Models::Payment::type_,
        user_defined_id: String?
      }

      type category =
        :ACH
        | :BALANCE_OR_FUNDING
        | :FEE
        | :REWARD
        | :ADJUSTMENT
        | :DERECOGNITION
        | :DISPUTE
        | :CARD
        | :EXTERNAL_ACH
        | :EXTERNAL_CHECK
        | :EXTERNAL_FEDNOW
        | :EXTERNAL_RTP
        | :EXTERNAL_TRANSFER
        | :EXTERNAL_WIRE
        | :MANAGEMENT_ADJUSTMENT
        | :MANAGEMENT_DISPUTE
        | :MANAGEMENT_FEE
        | :MANAGEMENT_REWARD
        | :MANAGEMENT_DISBURSEMENT
        | :PROGRAM_FUNDING

      module Category
        extend Lithic::Internal::Type::Enum

        ACH: :ACH
        BALANCE_OR_FUNDING: :BALANCE_OR_FUNDING
        FEE: :FEE
        REWARD: :REWARD
        ADJUSTMENT: :ADJUSTMENT
        DERECOGNITION: :DERECOGNITION
        DISPUTE: :DISPUTE
        CARD: :CARD
        EXTERNAL_ACH: :EXTERNAL_ACH
        EXTERNAL_CHECK: :EXTERNAL_CHECK
        EXTERNAL_FEDNOW: :EXTERNAL_FEDNOW
        EXTERNAL_RTP: :EXTERNAL_RTP
        EXTERNAL_TRANSFER: :EXTERNAL_TRANSFER
        EXTERNAL_WIRE: :EXTERNAL_WIRE
        MANAGEMENT_ADJUSTMENT: :MANAGEMENT_ADJUSTMENT
        MANAGEMENT_DISPUTE: :MANAGEMENT_DISPUTE
        MANAGEMENT_FEE: :MANAGEMENT_FEE
        MANAGEMENT_REWARD: :MANAGEMENT_REWARD
        MANAGEMENT_DISBURSEMENT: :MANAGEMENT_DISBURSEMENT
        PROGRAM_FUNDING: :PROGRAM_FUNDING

        def self?.values: -> ::Array[Lithic::Models::Payment::category]
      end

      type direction = :CREDIT | :DEBIT

      module Direction
        extend Lithic::Internal::Type::Enum

        CREDIT: :CREDIT
        DEBIT: :DEBIT

        def self?.values: -> ::Array[Lithic::Models::Payment::direction]
      end

      type event =
        {
          token: String,
          amount: Integer,
          created: Time,
          result: Lithic::Models::Payment::Event::result,
          type: Lithic::Models::Payment::Event::type_,
          detailed_results: ::Array[Lithic::Models::Payment::Event::detailed_result],
          external_id: String?
        }

      class Event < Lithic::Internal::Type::BaseModel
        attr_accessor token: String

        attr_accessor amount: Integer

        attr_accessor created: Time

        attr_accessor result: Lithic::Models::Payment::Event::result

        attr_accessor type: Lithic::Models::Payment::Event::type_

        attr_reader detailed_results: ::Array[Lithic::Models::Payment::Event::detailed_result]?

        def detailed_results=: (
          ::Array[Lithic::Models::Payment::Event::detailed_result]
        ) -> ::Array[Lithic::Models::Payment::Event::detailed_result]

        attr_accessor external_id: String?

        def initialize: (
          token: String,
          amount: Integer,
          created: Time,
          result: Lithic::Models::Payment::Event::result,
          type: Lithic::Models::Payment::Event::type_,
          ?detailed_results: ::Array[Lithic::Models::Payment::Event::detailed_result],
          ?external_id: String?
        ) -> void

        def to_hash: -> {
          token: String,
          amount: Integer,
          created: Time,
          result: Lithic::Models::Payment::Event::result,
          type: Lithic::Models::Payment::Event::type_,
          detailed_results: ::Array[Lithic::Models::Payment::Event::detailed_result],
          external_id: String?
        }

        type result = :APPROVED | :DECLINED

        module Result
          extend Lithic::Internal::Type::Enum

          APPROVED: :APPROVED
          DECLINED: :DECLINED

          def self?.values: -> ::Array[Lithic::Models::Payment::Event::result]
        end

        type type_ =
          :ACH_ORIGINATION_CANCELLED
          | :ACH_ORIGINATION_INITIATED
          | :ACH_ORIGINATION_PROCESSED
          | :ACH_ORIGINATION_REJECTED
          | :ACH_ORIGINATION_RELEASED
          | :ACH_ORIGINATION_REVIEWED
          | :ACH_ORIGINATION_SETTLED
          | :ACH_RECEIPT_PROCESSED
          | :ACH_RECEIPT_RELEASED
          | :ACH_RECEIPT_SETTLED
          | :ACH_RETURN_INITIATED
          | :ACH_RETURN_PROCESSED
          | :ACH_RETURN_REJECTED
          | :ACH_RETURN_SETTLED

        module Type
          extend Lithic::Internal::Type::Enum

          ACH_ORIGINATION_CANCELLED: :ACH_ORIGINATION_CANCELLED
          ACH_ORIGINATION_INITIATED: :ACH_ORIGINATION_INITIATED
          ACH_ORIGINATION_PROCESSED: :ACH_ORIGINATION_PROCESSED
          ACH_ORIGINATION_REJECTED: :ACH_ORIGINATION_REJECTED
          ACH_ORIGINATION_RELEASED: :ACH_ORIGINATION_RELEASED
          ACH_ORIGINATION_REVIEWED: :ACH_ORIGINATION_REVIEWED
          ACH_ORIGINATION_SETTLED: :ACH_ORIGINATION_SETTLED
          ACH_RECEIPT_PROCESSED: :ACH_RECEIPT_PROCESSED
          ACH_RECEIPT_RELEASED: :ACH_RECEIPT_RELEASED
          ACH_RECEIPT_SETTLED: :ACH_RECEIPT_SETTLED
          ACH_RETURN_INITIATED: :ACH_RETURN_INITIATED
          ACH_RETURN_PROCESSED: :ACH_RETURN_PROCESSED
          ACH_RETURN_REJECTED: :ACH_RETURN_REJECTED
          ACH_RETURN_SETTLED: :ACH_RETURN_SETTLED

          def self?.values: -> ::Array[Lithic::Models::Payment::Event::type_]
        end

        type detailed_result =
          :APPROVED
          | :DECLINED
          | :FUNDS_INSUFFICIENT
          | :ACCOUNT_INVALID
          | :PROGRAM_TRANSACTION_LIMIT_EXCEEDED
          | :PROGRAM_DAILY_LIMIT_EXCEEDED
          | :PROGRAM_MONTHLY_LIMIT_EXCEEDED

        module DetailedResult
          extend Lithic::Internal::Type::Enum

          APPROVED: :APPROVED
          DECLINED: :DECLINED
          FUNDS_INSUFFICIENT: :FUNDS_INSUFFICIENT
          ACCOUNT_INVALID: :ACCOUNT_INVALID
          PROGRAM_TRANSACTION_LIMIT_EXCEEDED: :PROGRAM_TRANSACTION_LIMIT_EXCEEDED
          PROGRAM_DAILY_LIMIT_EXCEEDED: :PROGRAM_DAILY_LIMIT_EXCEEDED
          PROGRAM_MONTHLY_LIMIT_EXCEEDED: :PROGRAM_MONTHLY_LIMIT_EXCEEDED

          def self?.values: -> ::Array[Lithic::Models::Payment::Event::detailed_result]
        end
      end

      type method_ = :ACH_NEXT_DAY | :ACH_SAME_DAY | :WIRE

      module Method
        extend Lithic::Internal::Type::Enum

        ACH_NEXT_DAY: :ACH_NEXT_DAY
        ACH_SAME_DAY: :ACH_SAME_DAY
        WIRE: :WIRE

        def self?.values: -> ::Array[Lithic::Models::Payment::method_]
      end

      type method_attributes =
        Lithic::Payment::MethodAttributes::ACHMethodAttributes
        | Lithic::Payment::MethodAttributes::WireMethodAttributes

      module MethodAttributes
        extend Lithic::Internal::Type::Union

        type ach_method_attributes =
          {
            sec_code: Lithic::Models::Payment::MethodAttributes::ACHMethodAttributes::sec_code,
            ach_hold_period: Integer?,
            addenda: String?,
            company_id: String?,
            receipt_routing_number: String?,
            retries: Integer?,
            return_reason_code: String?,
            trace_numbers: ::Array[String]
          }

        class ACHMethodAttributes < Lithic::Internal::Type::BaseModel
          attr_accessor sec_code: Lithic::Models::Payment::MethodAttributes::ACHMethodAttributes::sec_code

          attr_accessor ach_hold_period: Integer?

          attr_accessor addenda: String?

          attr_accessor company_id: String?

          attr_accessor receipt_routing_number: String?

          attr_accessor retries: Integer?

          attr_accessor return_reason_code: String?

          attr_reader trace_numbers: ::Array[String]?

          def trace_numbers=: (::Array[String]) -> ::Array[String]

          def initialize: (
            sec_code: Lithic::Models::Payment::MethodAttributes::ACHMethodAttributes::sec_code,
            ?ach_hold_period: Integer?,
            ?addenda: String?,
            ?company_id: String?,
            ?receipt_routing_number: String?,
            ?retries: Integer?,
            ?return_reason_code: String?,
            ?trace_numbers: ::Array[String]
          ) -> void

          def to_hash: -> {
            sec_code: Lithic::Models::Payment::MethodAttributes::ACHMethodAttributes::sec_code,
            ach_hold_period: Integer?,
            addenda: String?,
            company_id: String?,
            receipt_routing_number: String?,
            retries: Integer?,
            return_reason_code: String?,
            trace_numbers: ::Array[String]
          }

          type sec_code = :CCD | :PPD | :WEB | :TEL | :CIE | :CTX

          module SecCode
            extend Lithic::Internal::Type::Enum

            CCD: :CCD
            PPD: :PPD
            WEB: :WEB
            TEL: :TEL
            CIE: :CIE
            CTX: :CTX

            def self?.values: -> ::Array[Lithic::Models::Payment::MethodAttributes::ACHMethodAttributes::sec_code]
          end
        end

        type wire_method_attributes =
          {
            wire_message_type: String?,
            wire_network: Lithic::Models::Payment::MethodAttributes::WireMethodAttributes::wire_network,
            creditor: Lithic::WirePartyDetails,
            debtor: Lithic::WirePartyDetails,
            message_id: String?,
            remittance_information: String?
          }

        class WireMethodAttributes < Lithic::Internal::Type::BaseModel
          attr_accessor wire_message_type: String?

          attr_accessor wire_network: Lithic::Models::Payment::MethodAttributes::WireMethodAttributes::wire_network

          attr_reader creditor: Lithic::WirePartyDetails?

          def creditor=: (Lithic::WirePartyDetails) -> Lithic::WirePartyDetails

          attr_reader debtor: Lithic::WirePartyDetails?

          def debtor=: (Lithic::WirePartyDetails) -> Lithic::WirePartyDetails

          attr_accessor message_id: String?

          attr_accessor remittance_information: String?

          def initialize: (
            wire_message_type: String?,
            wire_network: Lithic::Models::Payment::MethodAttributes::WireMethodAttributes::wire_network,
            ?creditor: Lithic::WirePartyDetails,
            ?debtor: Lithic::WirePartyDetails,
            ?message_id: String?,
            ?remittance_information: String?
          ) -> void

          def to_hash: -> {
            wire_message_type: String?,
            wire_network: Lithic::Models::Payment::MethodAttributes::WireMethodAttributes::wire_network,
            creditor: Lithic::WirePartyDetails,
            debtor: Lithic::WirePartyDetails,
            message_id: String?,
            remittance_information: String?
          }

          type wire_network = :FEDWIRE | :SWIFT

          module WireNetwork
            extend Lithic::Internal::Type::Enum

            FEDWIRE: :FEDWIRE
            SWIFT: :SWIFT

            def self?.values: -> ::Array[Lithic::Models::Payment::MethodAttributes::WireMethodAttributes::wire_network]
          end
        end

        def self?.variants: -> ::Array[Lithic::Models::Payment::method_attributes]
      end

      type related_account_tokens =
        { account_token: String?, business_account_token: String? }

      class RelatedAccountTokens < Lithic::Internal::Type::BaseModel
        attr_accessor account_token: String?

        attr_accessor business_account_token: String?

        def initialize: (
          account_token: String?,
          business_account_token: String?
        ) -> void

        def to_hash: -> {
          account_token: String?,
          business_account_token: String?
        }
      end

      type result = :APPROVED | :DECLINED

      module Result
        extend Lithic::Internal::Type::Enum

        APPROVED: :APPROVED
        DECLINED: :DECLINED

        def self?.values: -> ::Array[Lithic::Models::Payment::result]
      end

      type source = :LITHIC | :EXTERNAL | :CUSTOMER

      module Source
        extend Lithic::Internal::Type::Enum

        LITHIC: :LITHIC
        EXTERNAL: :EXTERNAL
        CUSTOMER: :CUSTOMER

        def self?.values: -> ::Array[Lithic::Models::Payment::source]
      end

      type status =
        :PENDING | :SETTLED | :DECLINED | :REVERSED | :CANCELED | :RETURNED

      module Status
        extend Lithic::Internal::Type::Enum

        PENDING: :PENDING
        SETTLED: :SETTLED
        DECLINED: :DECLINED
        REVERSED: :REVERSED
        CANCELED: :CANCELED
        RETURNED: :RETURNED

        def self?.values: -> ::Array[Lithic::Models::Payment::status]
      end

      type type_ =
        :ORIGINATION_CREDIT
        | :ORIGINATION_DEBIT
        | :RECEIPT_CREDIT
        | :RECEIPT_DEBIT
        | :WIRE_INBOUND_PAYMENT
        | :WIRE_INBOUND_ADMIN
        | :WIRE_OUTBOUND_PAYMENT
        | :WIRE_OUTBOUND_ADMIN
        | :WIRE_INBOUND_DRAWDOWN_REQUEST

      module Type
        extend Lithic::Internal::Type::Enum

        ORIGINATION_CREDIT: :ORIGINATION_CREDIT
        ORIGINATION_DEBIT: :ORIGINATION_DEBIT
        RECEIPT_CREDIT: :RECEIPT_CREDIT
        RECEIPT_DEBIT: :RECEIPT_DEBIT
        WIRE_INBOUND_PAYMENT: :WIRE_INBOUND_PAYMENT
        WIRE_INBOUND_ADMIN: :WIRE_INBOUND_ADMIN
        WIRE_OUTBOUND_PAYMENT: :WIRE_OUTBOUND_PAYMENT
        WIRE_OUTBOUND_ADMIN: :WIRE_OUTBOUND_ADMIN
        WIRE_INBOUND_DRAWDOWN_REQUEST: :WIRE_INBOUND_DRAWDOWN_REQUEST

        def self?.values: -> ::Array[Lithic::Models::Payment::type_]
      end
    end
  end
end
