module Lithic
  module Models
    type payment_simulate_receipt_params =
      {
        token: String,
        amount: Integer,
        financial_account_token: String,
        receipt_type: Lithic::Models::PaymentSimulateReceiptParams::receipt_type,
        memo: String
      }
      & Lithic::Internal::Type::request_parameters

    class PaymentSimulateReceiptParams < Lithic::Internal::Type::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_accessor token: String

      attr_accessor amount: Integer

      attr_accessor financial_account_token: String

      attr_accessor receipt_type: Lithic::Models::PaymentSimulateReceiptParams::receipt_type

      attr_reader memo: String?

      def memo=: (String) -> String

      def initialize: (
        token: String,
        amount: Integer,
        financial_account_token: String,
        receipt_type: Lithic::Models::PaymentSimulateReceiptParams::receipt_type,
        ?memo: String,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> {
        token: String,
        amount: Integer,
        financial_account_token: String,
        receipt_type: Lithic::Models::PaymentSimulateReceiptParams::receipt_type,
        memo: String,
        request_options: Lithic::RequestOptions
      }

      type receipt_type = :RECEIPT_CREDIT | :RECEIPT_DEBIT

      module ReceiptType
        extend Lithic::Internal::Type::Enum

        RECEIPT_CREDIT: :RECEIPT_CREDIT
        RECEIPT_DEBIT: :RECEIPT_DEBIT

        def self?.values: -> ::Array[Lithic::Models::PaymentSimulateReceiptParams::receipt_type]
      end
    end
  end
end
