module Lithic
  module Models
    type payment_simulate_return_params =
      { payment_token: String, return_reason_code: String }
      & Lithic::Internal::Type::request_parameters

    class PaymentSimulateReturnParams < Lithic::Internal::Type::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_accessor payment_token: String

      attr_reader return_reason_code: String?

      def return_reason_code=: (String) -> String

      def initialize: (
        payment_token: String,
        ?return_reason_code: String,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> {
        payment_token: String,
        return_reason_code: String,
        request_options: Lithic::RequestOptions
      }
    end
  end
end
