module Lithic
  module Models
    type payment_create_response = { balance: Lithic::Balance }

    class PaymentCreateResponse < Lithic::Models::Payment
      def balance: -> Lithic::Balance?

      def balance=: (Lithic::Balance _) -> Lithic::Balance

      def initialize: (?balance: Lithic::Balance) -> void

      def to_hash: -> { balance: Lithic::Balance }
    end
  end
end
