module Lithic
  module Models
    type payment_simulate_action_params =
      {
        event_type: Lithic::Models::PaymentSimulateActionParams::event_type,
        decline_reason: Lithic::Models::PaymentSimulateActionParams::decline_reason,
        return_reason_code: String
      }
      & Lithic::request_parameters

    class PaymentSimulateActionParams < Lithic::BaseModel
      extend Lithic::Type::RequestParameters::Converter
      include Lithic::RequestParameters

      attr_accessor event_type: Lithic::Models::PaymentSimulateActionParams::event_type

      attr_reader decline_reason: Lithic::Models::PaymentSimulateActionParams::decline_reason?

      def decline_reason=: (
        Lithic::Models::PaymentSimulateActionParams::decline_reason
      ) -> Lithic::Models::PaymentSimulateActionParams::decline_reason

      attr_reader return_reason_code: String?

      def return_reason_code=: (String) -> String

      def initialize: (
        event_type: Lithic::Models::PaymentSimulateActionParams::event_type,
        ?decline_reason: Lithic::Models::PaymentSimulateActionParams::decline_reason,
        ?return_reason_code: String,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> Lithic::Models::payment_simulate_action_params

      type event_type =
        :ACH_ORIGINATION_REVIEWED
        | :ACH_ORIGINATION_RELEASED
        | :ACH_ORIGINATION_PROCESSED
        | :ACH_ORIGINATION_SETTLED
        | :ACH_RECEIPT_SETTLED
        | :ACH_RETURN_INITIATED
        | :ACH_RETURN_PROCESSED
        | :ACH_RETURN_SETTLED

      module EventType
        extend Lithic::Enum

        ACH_ORIGINATION_REVIEWED: :ACH_ORIGINATION_REVIEWED
        ACH_ORIGINATION_RELEASED: :ACH_ORIGINATION_RELEASED
        ACH_ORIGINATION_PROCESSED: :ACH_ORIGINATION_PROCESSED
        ACH_ORIGINATION_SETTLED: :ACH_ORIGINATION_SETTLED
        ACH_RECEIPT_SETTLED: :ACH_RECEIPT_SETTLED
        ACH_RETURN_INITIATED: :ACH_RETURN_INITIATED
        ACH_RETURN_PROCESSED: :ACH_RETURN_PROCESSED
        ACH_RETURN_SETTLED: :ACH_RETURN_SETTLED

        def self?.values: -> ::Array[Lithic::Models::PaymentSimulateActionParams::event_type]
      end

      type decline_reason =
        :PROGRAM_TRANSACTION_LIMIT_EXCEEDED
        | :PROGRAM_DAILY_LIMIT_EXCEEDED
        | :PROGRAM_MONTHLY_LIMIT_EXCEEDED

      module DeclineReason
        extend Lithic::Enum

        PROGRAM_TRANSACTION_LIMIT_EXCEEDED: :PROGRAM_TRANSACTION_LIMIT_EXCEEDED
        PROGRAM_DAILY_LIMIT_EXCEEDED: :PROGRAM_DAILY_LIMIT_EXCEEDED
        PROGRAM_MONTHLY_LIMIT_EXCEEDED: :PROGRAM_MONTHLY_LIMIT_EXCEEDED

        def self?.values: -> ::Array[Lithic::Models::PaymentSimulateActionParams::decline_reason]
      end
    end
  end
end
