module Lithic
  module Models
    type payment_retry_params = {  } & Lithic::request_parameters

    class PaymentRetryParams < Lithic::BaseModel
      extend Lithic::RequestParameters::Converter
      include Lithic::RequestParameters

      def initialize: (?request_options: Lithic::request_opts) -> void

      def to_hash: -> Lithic::Models::payment_retry_params
    end
  end
end
