module Lithic
  module Models
    type tokenization_update_digital_card_art_params =
      { digital_card_art_token: String }
      & Lithic::Internal::Type::request_parameters

    class TokenizationUpdateDigitalCardArtParams < Lithic::Internal::Type::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_reader digital_card_art_token: String?

      def digital_card_art_token=: (String) -> String

      def initialize: (
        ?digital_card_art_token: String,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> {
        digital_card_art_token: String,
        request_options: Lithic::RequestOptions
      }
    end
  end
end
