module Lithic
  module Models
    type tokenization_unpause_params =
      {  } & Lithic::Internal::Type::request_parameters

    class TokenizationUnpauseParams < Lithic::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      def initialize: (?request_options: Lithic::request_opts) -> void

      def to_hash: -> Lithic::Models::tokenization_unpause_params
    end
  end
end
