module Lithic
  module Models
    type tokenization_tfa_reason =
      :WALLET_RECOMMENDED_TFA
      | :SUSPICIOUS_ACTIVITY
      | :DEVICE_RECENTLY_LOST
      | :TOO_MANY_RECENT_ATTEMPTS
      | :TOO_MANY_RECENT_TOKENS
      | :TOO_MANY_DIFFERENT_CARDHOLDERS
      | :OUTSIDE_HOME_TERRITORY
      | :HAS_SUSPENDED_TOKENS
      | :HIGH_RISK
      | :ACCOUNT_SCORE_LOW
      | :DEVICE_SCORE_LOW
      | :CARD_STATE_TFA
      | :HARDCODED_TFA
      | :CUSTOMER_RULE_TFA
      | :DEVICE_HOST_CARD_EMULATION

    module TokenizationTfaReason
      extend Lithic::Internal::Type::Enum

      WALLET_RECOMMENDED_TFA: :WALLET_RECOMMENDED_TFA
      SUSPICIOUS_ACTIVITY: :SUSPICIOUS_ACTIVITY
      DEVICE_RECENTLY_LOST: :DEVICE_RECENTLY_LOST
      TOO_MANY_RECENT_ATTEMPTS: :TOO_MANY_RECENT_ATTEMPTS
      TOO_MANY_RECENT_TOKENS: :TOO_MANY_RECENT_TOKENS
      TOO_MANY_DIFFERENT_CARDHOLDERS: :TOO_MANY_DIFFERENT_CARDHOLDERS
      OUTSIDE_HOME_TERRITORY: :OUTSIDE_HOME_TERRITORY
      HAS_SUSPENDED_TOKENS: :HAS_SUSPENDED_TOKENS
      HIGH_RISK: :HIGH_RISK
      ACCOUNT_SCORE_LOW: :ACCOUNT_SCORE_LOW
      DEVICE_SCORE_LOW: :DEVICE_SCORE_LOW
      CARD_STATE_TFA: :CARD_STATE_TFA
      HARDCODED_TFA: :HARDCODED_TFA
      CUSTOMER_RULE_TFA: :CUSTOMER_RULE_TFA
      DEVICE_HOST_CARD_EMULATION: :DEVICE_HOST_CARD_EMULATION

      def self?.values: -> ::Array[Lithic::Models::tokenization_tfa_reason]
    end
  end
end
