module Lithic
  module Models
    type tokenization_decisioning_rotate_secret_params =
      {  } & Lithic::request_parameters

    class TokenizationDecisioningRotateSecretParams < Lithic::BaseModel
      extend Lithic::RequestParameters::Converter
      include Lithic::RequestParameters

      def initialize: (?request_options: Lithic::request_opts) -> void

      def to_hash: -> Lithic::Models::tokenization_decisioning_rotate_secret_params
    end
  end
end
