module Lithic
  module Models
    type tokenization_secret = { secret: String }

    class TokenizationSecret < Lithic::BaseModel
      attr_reader secret: String?

      def secret=: (String) -> String

      def initialize: (?secret: String) -> void

      def to_hash: -> Lithic::Models::tokenization_secret
    end
  end
end
