module Lithic
  module Models
    type tokenization =
      {
        token: String,
        account_token: String,
        card_token: String,
        created_at: Time,
        dpan: String?,
        status: Lithic::Models::Tokenization::status,
        token_requestor_name: Lithic::Models::Tokenization::token_requestor_name,
        token_unique_reference: String,
        tokenization_channel: Lithic::Models::Tokenization::tokenization_channel,
        updated_at: Time,
        device_id: String?,
        digital_card_art_token: String?,
        events: ::Array[Lithic::Tokenization::Event],
        payment_account_reference_id: String?
      }

    class Tokenization < Lithic::Internal::Type::BaseModel
      attr_accessor token: String

      attr_accessor account_token: String

      attr_accessor card_token: String

      attr_accessor created_at: Time

      attr_accessor dpan: String?

      attr_accessor status: Lithic::Models::Tokenization::status

      attr_accessor token_requestor_name: Lithic::Models::Tokenization::token_requestor_name

      attr_accessor token_unique_reference: String

      attr_accessor tokenization_channel: Lithic::Models::Tokenization::tokenization_channel

      attr_accessor updated_at: Time

      attr_accessor device_id: String?

      attr_accessor digital_card_art_token: String?

      attr_reader events: ::Array[Lithic::Tokenization::Event]?

      def events=: (
        ::Array[Lithic::Tokenization::Event]
      ) -> ::Array[Lithic::Tokenization::Event]

      attr_accessor payment_account_reference_id: String?

      def initialize: (
        token: String,
        account_token: String,
        card_token: String,
        created_at: Time,
        dpan: String?,
        status: Lithic::Models::Tokenization::status,
        token_requestor_name: Lithic::Models::Tokenization::token_requestor_name,
        token_unique_reference: String,
        tokenization_channel: Lithic::Models::Tokenization::tokenization_channel,
        updated_at: Time,
        ?device_id: String?,
        ?digital_card_art_token: String?,
        ?events: ::Array[Lithic::Tokenization::Event],
        ?payment_account_reference_id: String?
      ) -> void

      def to_hash: -> {
        token: String,
        account_token: String,
        card_token: String,
        created_at: Time,
        dpan: String?,
        status: Lithic::Models::Tokenization::status,
        token_requestor_name: Lithic::Models::Tokenization::token_requestor_name,
        token_unique_reference: String,
        tokenization_channel: Lithic::Models::Tokenization::tokenization_channel,
        updated_at: Time,
        device_id: String?,
        digital_card_art_token: String?,
        events: ::Array[Lithic::Tokenization::Event],
        payment_account_reference_id: String?
      }

      type status =
        :ACTIVE
        | :DEACTIVATED
        | :INACTIVE
        | :PAUSED
        | :PENDING_2FA
        | :PENDING_ACTIVATION
        | :UNKNOWN

      module Status
        extend Lithic::Internal::Type::Enum

        ACTIVE: :ACTIVE
        DEACTIVATED: :DEACTIVATED
        INACTIVE: :INACTIVE
        PAUSED: :PAUSED
        PENDING_2_FA: :PENDING_2FA
        PENDING_ACTIVATION: :PENDING_ACTIVATION
        UNKNOWN: :UNKNOWN

        def self?.values: -> ::Array[Lithic::Models::Tokenization::status]
      end

      type token_requestor_name =
        :AMAZON_ONE
        | :ANDROID_PAY
        | :APPLE_PAY
        | :FACEBOOK
        | :FITBIT_PAY
        | :GARMIN_PAY
        | :GOOGLE_PAY
        | :MICROSOFT_PAY
        | :NETFLIX
        | :SAMSUNG_PAY
        | :UNKNOWN
        | :VISA_CHECKOUT
        | String

      module TokenRequestorName
        extend Lithic::Internal::Type::Union

        def self?.variants: -> ::Array[Lithic::Models::Tokenization::token_requestor_name]

        AMAZON_ONE: :AMAZON_ONE
        ANDROID_PAY: :ANDROID_PAY
        APPLE_PAY: :APPLE_PAY
        FACEBOOK: :FACEBOOK
        FITBIT_PAY: :FITBIT_PAY
        GARMIN_PAY: :GARMIN_PAY
        GOOGLE_PAY: :GOOGLE_PAY
        MICROSOFT_PAY: :MICROSOFT_PAY
        NETFLIX: :NETFLIX
        SAMSUNG_PAY: :SAMSUNG_PAY
        UNKNOWN: :UNKNOWN
        VISA_CHECKOUT: :VISA_CHECKOUT
      end

      type tokenization_channel = :DIGITAL_WALLET | :MERCHANT

      module TokenizationChannel
        extend Lithic::Internal::Type::Enum

        DIGITAL_WALLET: :DIGITAL_WALLET
        MERCHANT: :MERCHANT

        def self?.values: -> ::Array[Lithic::Models::Tokenization::tokenization_channel]
      end

      type event =
        {
          token: String,
          created_at: Time,
          result: Lithic::Models::Tokenization::Event::result,
          rule_results: ::Array[Lithic::Tokenization::Event::RuleResult],
          tokenization_decline_reasons: ::Array[Lithic::Models::Tokenization::Event::tokenization_decline_reason],
          tokenization_tfa_reasons: ::Array[Lithic::Models::Tokenization::Event::tokenization_tfa_reason],
          type: Lithic::Models::Tokenization::Event::type_
        }

      class Event < Lithic::Internal::Type::BaseModel
        attr_reader token: String?

        def token=: (String) -> String

        attr_reader created_at: Time?

        def created_at=: (Time) -> Time

        attr_reader result: Lithic::Models::Tokenization::Event::result?

        def result=: (
          Lithic::Models::Tokenization::Event::result
        ) -> Lithic::Models::Tokenization::Event::result

        attr_reader rule_results: ::Array[Lithic::Tokenization::Event::RuleResult]?

        def rule_results=: (
          ::Array[Lithic::Tokenization::Event::RuleResult]
        ) -> ::Array[Lithic::Tokenization::Event::RuleResult]

        attr_reader tokenization_decline_reasons: ::Array[Lithic::Models::Tokenization::Event::tokenization_decline_reason]?

        def tokenization_decline_reasons=: (
          ::Array[Lithic::Models::Tokenization::Event::tokenization_decline_reason]
        ) -> ::Array[Lithic::Models::Tokenization::Event::tokenization_decline_reason]

        attr_reader tokenization_tfa_reasons: ::Array[Lithic::Models::Tokenization::Event::tokenization_tfa_reason]?

        def tokenization_tfa_reasons=: (
          ::Array[Lithic::Models::Tokenization::Event::tokenization_tfa_reason]
        ) -> ::Array[Lithic::Models::Tokenization::Event::tokenization_tfa_reason]

        attr_reader type: Lithic::Models::Tokenization::Event::type_?

        def type=: (
          Lithic::Models::Tokenization::Event::type_
        ) -> Lithic::Models::Tokenization::Event::type_

        def initialize: (
          ?token: String,
          ?created_at: Time,
          ?result: Lithic::Models::Tokenization::Event::result,
          ?rule_results: ::Array[Lithic::Tokenization::Event::RuleResult],
          ?tokenization_decline_reasons: ::Array[Lithic::Models::Tokenization::Event::tokenization_decline_reason],
          ?tokenization_tfa_reasons: ::Array[Lithic::Models::Tokenization::Event::tokenization_tfa_reason],
          ?type: Lithic::Models::Tokenization::Event::type_
        ) -> void

        def to_hash: -> {
          token: String,
          created_at: Time,
          result: Lithic::Models::Tokenization::Event::result,
          rule_results: ::Array[Lithic::Tokenization::Event::RuleResult],
          tokenization_decline_reasons: ::Array[Lithic::Models::Tokenization::Event::tokenization_decline_reason],
          tokenization_tfa_reasons: ::Array[Lithic::Models::Tokenization::Event::tokenization_tfa_reason],
          type: Lithic::Models::Tokenization::Event::type_
        }

        type result =
          :APPROVED
          | :DECLINED
          | :NOTIFICATION_DELIVERED
          | :REQUIRE_ADDITIONAL_AUTHENTICATION
          | :TOKEN_ACTIVATED
          | :TOKEN_CREATED
          | :TOKEN_DEACTIVATED
          | :TOKEN_DELETED_FROM_CONSUMER_APP
          | :TOKEN_INACTIVE
          | :TOKEN_STATE_UNKNOWN
          | :TOKEN_SUSPENDED
          | :TOKEN_UPDATED

        module Result
          extend Lithic::Internal::Type::Enum

          APPROVED: :APPROVED
          DECLINED: :DECLINED
          NOTIFICATION_DELIVERED: :NOTIFICATION_DELIVERED
          REQUIRE_ADDITIONAL_AUTHENTICATION: :REQUIRE_ADDITIONAL_AUTHENTICATION
          TOKEN_ACTIVATED: :TOKEN_ACTIVATED
          TOKEN_CREATED: :TOKEN_CREATED
          TOKEN_DEACTIVATED: :TOKEN_DEACTIVATED
          TOKEN_DELETED_FROM_CONSUMER_APP: :TOKEN_DELETED_FROM_CONSUMER_APP
          TOKEN_INACTIVE: :TOKEN_INACTIVE
          TOKEN_STATE_UNKNOWN: :TOKEN_STATE_UNKNOWN
          TOKEN_SUSPENDED: :TOKEN_SUSPENDED
          TOKEN_UPDATED: :TOKEN_UPDATED

          def self?.values: -> ::Array[Lithic::Models::Tokenization::Event::result]
        end

        type rule_result =
          {
            auth_rule_token: String?,
            explanation: String?,
            name: String?,
            result: Lithic::Models::Tokenization::Event::RuleResult::result
          }

        class RuleResult < Lithic::Internal::Type::BaseModel
          attr_accessor auth_rule_token: String?

          attr_accessor explanation: String?

          attr_accessor name: String?

          attr_accessor result: Lithic::Models::Tokenization::Event::RuleResult::result

          def initialize: (
            auth_rule_token: String?,
            explanation: String?,
            name: String?,
            result: Lithic::Models::Tokenization::Event::RuleResult::result
          ) -> void

          def to_hash: -> {
            auth_rule_token: String?,
            explanation: String?,
            name: String?,
            result: Lithic::Models::Tokenization::Event::RuleResult::result
          }

          type result = :APPROVED | :DECLINED | :REQUIRE_TFA | :ERROR

          module Result
            extend Lithic::Internal::Type::Enum

            APPROVED: :APPROVED
            DECLINED: :DECLINED
            REQUIRE_TFA: :REQUIRE_TFA
            ERROR: :ERROR

            def self?.values: -> ::Array[Lithic::Models::Tokenization::Event::RuleResult::result]
          end
        end

        type tokenization_decline_reason =
          :ACCOUNT_SCORE_1
          | :DEVICE_SCORE_1
          | :ALL_WALLET_DECLINE_REASONS_PRESENT
          | :WALLET_RECOMMENDED_DECISION_RED
          | :CVC_MISMATCH
          | :CARD_EXPIRY_MONTH_MISMATCH
          | :CARD_EXPIRY_YEAR_MISMATCH
          | :CARD_INVALID_STATE
          | :CUSTOMER_RED_PATH
          | :INVALID_CUSTOMER_RESPONSE
          | :NETWORK_FAILURE
          | :GENERIC_DECLINE
          | :DIGITAL_CARD_ART_REQUIRED

        module TokenizationDeclineReason
          extend Lithic::Internal::Type::Enum

          ACCOUNT_SCORE_1: :ACCOUNT_SCORE_1
          DEVICE_SCORE_1: :DEVICE_SCORE_1
          ALL_WALLET_DECLINE_REASONS_PRESENT: :ALL_WALLET_DECLINE_REASONS_PRESENT
          WALLET_RECOMMENDED_DECISION_RED: :WALLET_RECOMMENDED_DECISION_RED
          CVC_MISMATCH: :CVC_MISMATCH
          CARD_EXPIRY_MONTH_MISMATCH: :CARD_EXPIRY_MONTH_MISMATCH
          CARD_EXPIRY_YEAR_MISMATCH: :CARD_EXPIRY_YEAR_MISMATCH
          CARD_INVALID_STATE: :CARD_INVALID_STATE
          CUSTOMER_RED_PATH: :CUSTOMER_RED_PATH
          INVALID_CUSTOMER_RESPONSE: :INVALID_CUSTOMER_RESPONSE
          NETWORK_FAILURE: :NETWORK_FAILURE
          GENERIC_DECLINE: :GENERIC_DECLINE
          DIGITAL_CARD_ART_REQUIRED: :DIGITAL_CARD_ART_REQUIRED

          def self?.values: -> ::Array[Lithic::Models::Tokenization::Event::tokenization_decline_reason]
        end

        type tokenization_tfa_reason =
          :WALLET_RECOMMENDED_TFA
          | :SUSPICIOUS_ACTIVITY
          | :DEVICE_RECENTLY_LOST
          | :TOO_MANY_RECENT_ATTEMPTS
          | :TOO_MANY_RECENT_TOKENS
          | :TOO_MANY_DIFFERENT_CARDHOLDERS
          | :OUTSIDE_HOME_TERRITORY
          | :HAS_SUSPENDED_TOKENS
          | :HIGH_RISK
          | :ACCOUNT_SCORE_LOW
          | :DEVICE_SCORE_LOW
          | :CARD_STATE_TFA
          | :HARDCODED_TFA
          | :CUSTOMER_RULE_TFA
          | :DEVICE_HOST_CARD_EMULATION

        module TokenizationTfaReason
          extend Lithic::Internal::Type::Enum

          WALLET_RECOMMENDED_TFA: :WALLET_RECOMMENDED_TFA
          SUSPICIOUS_ACTIVITY: :SUSPICIOUS_ACTIVITY
          DEVICE_RECENTLY_LOST: :DEVICE_RECENTLY_LOST
          TOO_MANY_RECENT_ATTEMPTS: :TOO_MANY_RECENT_ATTEMPTS
          TOO_MANY_RECENT_TOKENS: :TOO_MANY_RECENT_TOKENS
          TOO_MANY_DIFFERENT_CARDHOLDERS: :TOO_MANY_DIFFERENT_CARDHOLDERS
          OUTSIDE_HOME_TERRITORY: :OUTSIDE_HOME_TERRITORY
          HAS_SUSPENDED_TOKENS: :HAS_SUSPENDED_TOKENS
          HIGH_RISK: :HIGH_RISK
          ACCOUNT_SCORE_LOW: :ACCOUNT_SCORE_LOW
          DEVICE_SCORE_LOW: :DEVICE_SCORE_LOW
          CARD_STATE_TFA: :CARD_STATE_TFA
          HARDCODED_TFA: :HARDCODED_TFA
          CUSTOMER_RULE_TFA: :CUSTOMER_RULE_TFA
          DEVICE_HOST_CARD_EMULATION: :DEVICE_HOST_CARD_EMULATION

          def self?.values: -> ::Array[Lithic::Models::Tokenization::Event::tokenization_tfa_reason]
        end

        type type_ =
          :TOKENIZATION_2FA
          | :TOKENIZATION_AUTHORIZATION
          | :TOKENIZATION_DECISIONING
          | :TOKENIZATION_ELIGIBILITY_CHECK
          | :TOKENIZATION_UPDATED

        module Type
          extend Lithic::Internal::Type::Enum

          TOKENIZATION_2_FA: :TOKENIZATION_2FA
          TOKENIZATION_AUTHORIZATION: :TOKENIZATION_AUTHORIZATION
          TOKENIZATION_DECISIONING: :TOKENIZATION_DECISIONING
          TOKENIZATION_ELIGIBILITY_CHECK: :TOKENIZATION_ELIGIBILITY_CHECK
          TOKENIZATION_UPDATED: :TOKENIZATION_UPDATED

          def self?.values: -> ::Array[Lithic::Models::Tokenization::Event::type_]
        end
      end
    end
  end
end
