module Lithic
  module Models
    type tokenization_simulate_response =
      { data: ::Array[Lithic::Tokenization] }

    class TokenizationSimulateResponse < Lithic::Internal::Type::BaseModel
      attr_reader data: ::Array[Lithic::Tokenization]?

      def data=: (
        ::Array[Lithic::Tokenization]
      ) -> ::Array[Lithic::Tokenization]

      def initialize: (?data: ::Array[Lithic::Tokenization]) -> void

      def to_hash: -> { data: ::Array[Lithic::Tokenization] }
    end
  end
end
