module Lithic
  module Models
    type tokenization_decisioning_rotate_secret_response = { secret: String }

    class TokenizationDecisioningRotateSecretResponse < Lithic::Internal::Type::BaseModel
      attr_reader secret: String?

      def secret=: (String) -> String

      def initialize: (?secret: String) -> void
    end
  end
end
