module Lithic
  module Models
    type tokenization_retrieve_response = { data: Lithic::Tokenization }

    class TokenizationRetrieveResponse < Lithic::Internal::Type::BaseModel
      attr_reader data: Lithic::Tokenization?

      def data=: (Lithic::Tokenization) -> Lithic::Tokenization

      def initialize: (?data: Lithic::Tokenization) -> void
    end
  end
end
