module Lithic
  module Models
    type tokenization_activate_params = {  } & Lithic::request_parameters

    class TokenizationActivateParams < Lithic::BaseModel
      extend Lithic::RequestParameters::Converter
      include Lithic::RequestParameters

      def initialize: (?request_options: Lithic::request_opts) -> void

      def to_hash: -> Lithic::Models::tokenization_activate_params
    end
  end
end
