module Lithic
  module Models
    type transaction_simulate_authorization_advice_response =
      { token: String, debugging_request_id: String }

    class TransactionSimulateAuthorizationAdviceResponse < Lithic::BaseModel
      attr_reader token: String?

      def token=: (String) -> String

      attr_reader debugging_request_id: String?

      def debugging_request_id=: (String) -> String

      def initialize: (?token: String, ?debugging_request_id: String) -> void

      def to_hash: -> Lithic::Models::transaction_simulate_authorization_advice_response
    end
  end
end
