module Lithic
  module Models
    type transaction_simulate_return_params =
      { amount: Integer, descriptor: String, pan: String }
      & Lithic::Internal::Type::request_parameters

    class TransactionSimulateReturnParams < Lithic::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_accessor amount: Integer

      attr_accessor descriptor: String

      attr_accessor pan: String

      def initialize: (
        amount: Integer,
        descriptor: String,
        pan: String,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> Lithic::Models::transaction_simulate_return_params
    end
  end
end
