module Lithic
  module Models
    type transfer =
      {
        token: String,
        category: Lithic::Models::Transfer::category,
        created: Time,
        currency: String,
        descriptor: String,
        events: ::Array[Lithic::FinancialEvent],
        from_balance: ::Array[Lithic::Balance],
        pending_amount: Integer,
        result: Lithic::Models::Transfer::result,
        settled_amount: Integer,
        status: Lithic::Models::Transfer::status,
        to_balance: ::Array[Lithic::Balance],
        updated: Time
      }

    class Transfer < Lithic::Internal::Type::BaseModel
      attr_reader token: String?

      def token=: (String) -> String

      attr_reader category: Lithic::Models::Transfer::category?

      def category=: (
        Lithic::Models::Transfer::category
      ) -> Lithic::Models::Transfer::category

      attr_reader created: Time?

      def created=: (Time) -> Time

      attr_reader currency: String?

      def currency=: (String) -> String

      attr_reader descriptor: String?

      def descriptor=: (String) -> String

      attr_reader events: ::Array[Lithic::FinancialEvent]?

      def events=: (
        ::Array[Lithic::FinancialEvent]
      ) -> ::Array[Lithic::FinancialEvent]

      attr_reader from_balance: ::Array[Lithic::Balance]?

      def from_balance=: (::Array[Lithic::Balance]) -> ::Array[Lithic::Balance]

      attr_reader pending_amount: Integer?

      def pending_amount=: (Integer) -> Integer

      attr_reader result: Lithic::Models::Transfer::result?

      def result=: (
        Lithic::Models::Transfer::result
      ) -> Lithic::Models::Transfer::result

      attr_reader settled_amount: Integer?

      def settled_amount=: (Integer) -> Integer

      attr_reader status: Lithic::Models::Transfer::status?

      def status=: (
        Lithic::Models::Transfer::status
      ) -> Lithic::Models::Transfer::status

      attr_reader to_balance: ::Array[Lithic::Balance]?

      def to_balance=: (::Array[Lithic::Balance]) -> ::Array[Lithic::Balance]

      attr_reader updated: Time?

      def updated=: (Time) -> Time

      def initialize: (
        ?token: String,
        ?category: Lithic::Models::Transfer::category,
        ?created: Time,
        ?currency: String,
        ?descriptor: String,
        ?events: ::Array[Lithic::FinancialEvent],
        ?from_balance: ::Array[Lithic::Balance],
        ?pending_amount: Integer,
        ?result: Lithic::Models::Transfer::result,
        ?settled_amount: Integer,
        ?status: Lithic::Models::Transfer::status,
        ?to_balance: ::Array[Lithic::Balance],
        ?updated: Time
      ) -> void

      def to_hash: -> {
        token: String,
        category: Lithic::Models::Transfer::category,
        created: Time,
        currency: String,
        descriptor: String,
        events: ::Array[Lithic::FinancialEvent],
        from_balance: ::Array[Lithic::Balance],
        pending_amount: Integer,
        result: Lithic::Models::Transfer::result,
        settled_amount: Integer,
        status: Lithic::Models::Transfer::status,
        to_balance: ::Array[Lithic::Balance],
        updated: Time
      }

      type category = :TRANSFER

      module Category
        extend Lithic::Internal::Type::Enum

        TRANSFER: :TRANSFER

        def self?.values: -> ::Array[Lithic::Models::Transfer::category]
      end

      type result = :APPROVED | :DECLINED

      module Result
        extend Lithic::Internal::Type::Enum

        APPROVED: :APPROVED
        DECLINED: :DECLINED

        def self?.values: -> ::Array[Lithic::Models::Transfer::result]
      end

      type status = :DECLINED | :EXPIRED | :PENDING | :SETTLED | :VOIDED

      module Status
        extend Lithic::Internal::Type::Enum

        DECLINED: :DECLINED
        EXPIRED: :EXPIRED
        PENDING: :PENDING
        SETTLED: :SETTLED
        VOIDED: :VOIDED

        def self?.values: -> ::Array[Lithic::Models::Transfer::status]
      end
    end
  end
end
