module Lithic
  module Models
    type transaction_simulate_return_reversal_params =
      { token: String } & Lithic::request_parameters

    class TransactionSimulateReturnReversalParams < Lithic::BaseModel
      extend Lithic::Type::RequestParameters::Converter
      include Lithic::RequestParameters

      attr_accessor token: String

      def initialize: (
        token: String,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> Lithic::Models::transaction_simulate_return_reversal_params
    end
  end
end
