module Lithic
  module Models
    type transaction_simulate_return_reversal_response =
      { debugging_request_id: String }

    class TransactionSimulateReturnReversalResponse < Lithic::Internal::Type::BaseModel
      attr_reader debugging_request_id: String?

      def debugging_request_id=: (String) -> String

      def initialize: (?debugging_request_id: String) -> void
    end
  end
end
