module Lithic
  module Models
    type transaction_expire_authorization_params =
      {  } & Lithic::Internal::Type::request_parameters

    class TransactionExpireAuthorizationParams < Lithic::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      def initialize: (?request_options: Lithic::request_opts) -> void

      def to_hash: -> Lithic::Models::transaction_expire_authorization_params
    end
  end
end
