module Lithic
  module Models
    type transaction_simulate_credit_authorization_advice_response =
      { token: String, debugging_request_id: String }

    class TransactionSimulateCreditAuthorizationAdviceResponse < Lithic::Internal::Type::BaseModel
      attr_reader token: String?

      def token=: (String) -> String

      attr_reader debugging_request_id: String?

      def debugging_request_id=: (String) -> String

      def initialize: (?token: String, ?debugging_request_id: String) -> void

      def to_hash: -> { token: String, debugging_request_id: String }
    end
  end
end
