module Lithic
  module Models
    type transaction_list_params =
      {
        account_token: String,
        begin_: Time,
        card_token: String,
        end_: Time,
        ending_before: String,
        page_size: Integer,
        result: Lithic::Models::TransactionListParams::result,
        starting_after: String,
        status: Lithic::Models::TransactionListParams::status
      }
      & Lithic::Internal::Type::request_parameters

    class TransactionListParams < Lithic::Internal::Type::BaseModel
      extend Lithic::Internal::Type::RequestParameters::Converter
      include Lithic::Internal::Type::RequestParameters

      attr_reader account_token: String?

      def account_token=: (String) -> String

      attr_reader begin_: Time?

      def begin_=: (Time) -> Time

      attr_reader card_token: String?

      def card_token=: (String) -> String

      attr_reader end_: Time?

      def end_=: (Time) -> Time

      attr_reader ending_before: String?

      def ending_before=: (String) -> String

      attr_reader page_size: Integer?

      def page_size=: (Integer) -> Integer

      attr_reader result: Lithic::Models::TransactionListParams::result?

      def result=: (
        Lithic::Models::TransactionListParams::result
      ) -> Lithic::Models::TransactionListParams::result

      attr_reader starting_after: String?

      def starting_after=: (String) -> String

      attr_reader status: Lithic::Models::TransactionListParams::status?

      def status=: (
        Lithic::Models::TransactionListParams::status
      ) -> Lithic::Models::TransactionListParams::status

      def initialize: (
        ?account_token: String,
        ?begin_: Time,
        ?card_token: String,
        ?end_: Time,
        ?ending_before: String,
        ?page_size: Integer,
        ?result: Lithic::Models::TransactionListParams::result,
        ?starting_after: String,
        ?status: Lithic::Models::TransactionListParams::status,
        ?request_options: Lithic::request_opts
      ) -> void

      type result = :APPROVED | :DECLINED

      module Result
        extend Lithic::Internal::Type::Enum

        APPROVED: :APPROVED
        DECLINED: :DECLINED

        def self?.values: -> ::Array[Lithic::Models::TransactionListParams::result]
      end

      type status = :PENDING | :VOIDED | :SETTLED | :DECLINED | :EXPIRED

      module Status
        extend Lithic::Internal::Type::Enum

        PENDING: :PENDING
        VOIDED: :VOIDED
        SETTLED: :SETTLED
        DECLINED: :DECLINED
        EXPIRED: :EXPIRED

        def self?.values: -> ::Array[Lithic::Models::TransactionListParams::status]
      end
    end
  end
end
