module Lithic
  module Models
    type transaction_simulate_authorization_advice_params =
      { token: String, amount: Integer } & Lithic::request_parameters

    class TransactionSimulateAuthorizationAdviceParams < Lithic::BaseModel
      extend Lithic::RequestParameters::Converter
      include Lithic::RequestParameters

      attr_accessor token: String

      attr_accessor amount: Integer

      def initialize: (
        token: String,
        amount: Integer,
        ?request_options: Lithic::request_opts
      ) -> void

      def to_hash: -> Lithic::Models::transaction_simulate_authorization_advice_params
    end
  end
end
