module Lithic
  module Models
    module Transactions
      type enhanced_commercial_data_retrieve_params =
        {  } & Lithic::Internal::Type::request_parameters

      class EnhancedCommercialDataRetrieveParams < Lithic::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        def initialize: (?request_options: Lithic::request_opts) -> void

        def to_hash: -> Lithic::Models::Transactions::enhanced_commercial_data_retrieve_params
      end
    end
  end
end
