module Lithic
  module Models
    module Transactions
      type enhanced_commercial_data_retrieve_response =
        { data: ::Array[Lithic::Transactions::Events::EnhancedData] }

      class EnhancedCommercialDataRetrieveResponse < Lithic::Internal::Type::BaseModel
        attr_accessor data: ::Array[Lithic::Transactions::Events::EnhancedData]

        def initialize: (
          data: ::Array[Lithic::Transactions::Events::EnhancedData]
        ) -> void
      end
    end
  end
end
