module Lithic
  module Resources
    class Transactions
      class EnhancedCommercialData
        def retrieve: (
          String transaction_token,
          ?request_options: Lithic::request_opts
        ) -> Lithic::Models::Transactions::EnhancedCommercialDataRetrieveResponse

        def initialize: (client: Lithic::Client) -> void
      end
    end
  end
end
