module Lithic
  module Models
    class AuthRule = AuthRules::AuthRule

    module AuthRules
      type auth_rule =
        {
          token: String,
          account_tokens: ::Array[String],
          business_account_tokens: ::Array[String],
          card_tokens: ::Array[String],
          current_version: Lithic::AuthRules::AuthRule::CurrentVersion?,
          draft_version: Lithic::AuthRules::AuthRule::DraftVersion?,
          event_stream: Lithic::Models::AuthRules::event_stream,
          lithic_managed: bool,
          name: String?,
          program_level: bool,
          state: Lithic::Models::AuthRules::AuthRule::state,
          type: Lithic::Models::AuthRules::AuthRule::type_,
          excluded_card_tokens: ::Array[String]
        }

      class AuthRule < Lithic::Internal::Type::BaseModel
        attr_accessor token: String

        attr_accessor account_tokens: ::Array[String]

        attr_accessor business_account_tokens: ::Array[String]

        attr_accessor card_tokens: ::Array[String]

        attr_accessor current_version: Lithic::AuthRules::AuthRule::CurrentVersion?

        attr_accessor draft_version: Lithic::AuthRules::AuthRule::DraftVersion?

        attr_accessor event_stream: Lithic::Models::AuthRules::event_stream

        attr_accessor lithic_managed: bool

        attr_accessor name: String?

        attr_accessor program_level: bool

        attr_accessor state: Lithic::Models::AuthRules::AuthRule::state

        attr_accessor type: Lithic::Models::AuthRules::AuthRule::type_

        attr_reader excluded_card_tokens: ::Array[String]?

        def excluded_card_tokens=: (::Array[String]) -> ::Array[String]

        def initialize: (
          token: String,
          account_tokens: ::Array[String],
          business_account_tokens: ::Array[String],
          card_tokens: ::Array[String],
          current_version: Lithic::AuthRules::AuthRule::CurrentVersion?,
          draft_version: Lithic::AuthRules::AuthRule::DraftVersion?,
          event_stream: Lithic::Models::AuthRules::event_stream,
          lithic_managed: bool,
          name: String?,
          program_level: bool,
          state: Lithic::Models::AuthRules::AuthRule::state,
          type: Lithic::Models::AuthRules::AuthRule::type_,
          ?excluded_card_tokens: ::Array[String]
        ) -> void

        def to_hash: -> {
          token: String,
          account_tokens: ::Array[String],
          business_account_tokens: ::Array[String],
          card_tokens: ::Array[String],
          current_version: Lithic::AuthRules::AuthRule::CurrentVersion?,
          draft_version: Lithic::AuthRules::AuthRule::DraftVersion?,
          event_stream: Lithic::Models::AuthRules::event_stream,
          lithic_managed: bool,
          name: String?,
          program_level: bool,
          state: Lithic::Models::AuthRules::AuthRule::state,
          type: Lithic::Models::AuthRules::AuthRule::type_,
          excluded_card_tokens: ::Array[String]
        }

        type current_version =
          {
            parameters: Lithic::Models::AuthRules::AuthRule::CurrentVersion::parameters,
            version: Integer
          }

        class CurrentVersion < Lithic::Internal::Type::BaseModel
          attr_accessor parameters: Lithic::Models::AuthRules::AuthRule::CurrentVersion::parameters

          attr_accessor version: Integer

          def initialize: (
            parameters: Lithic::Models::AuthRules::AuthRule::CurrentVersion::parameters,
            version: Integer
          ) -> void

          def to_hash: -> {
            parameters: Lithic::Models::AuthRules::AuthRule::CurrentVersion::parameters,
            version: Integer
          }

          type parameters =
            Lithic::AuthRules::ConditionalBlockParameters
            | Lithic::AuthRules::VelocityLimitParams
            | Lithic::AuthRules::MerchantLockParameters
            | Lithic::AuthRules::Conditional3DSActionParameters
            | Lithic::AuthRules::ConditionalAuthorizationActionParameters
            | Lithic::AuthRules::ConditionalACHActionParameters
            | Lithic::AuthRules::ConditionalTokenizationActionParameters

          module Parameters
            extend Lithic::Internal::Type::Union

            def self?.variants: -> ::Array[Lithic::Models::AuthRules::AuthRule::CurrentVersion::parameters]
          end
        end

        type draft_version =
          {
            parameters: Lithic::Models::AuthRules::AuthRule::DraftVersion::parameters,
            version: Integer
          }

        class DraftVersion < Lithic::Internal::Type::BaseModel
          attr_accessor parameters: Lithic::Models::AuthRules::AuthRule::DraftVersion::parameters

          attr_accessor version: Integer

          def initialize: (
            parameters: Lithic::Models::AuthRules::AuthRule::DraftVersion::parameters,
            version: Integer
          ) -> void

          def to_hash: -> {
            parameters: Lithic::Models::AuthRules::AuthRule::DraftVersion::parameters,
            version: Integer
          }

          type parameters =
            Lithic::AuthRules::ConditionalBlockParameters
            | Lithic::AuthRules::VelocityLimitParams
            | Lithic::AuthRules::MerchantLockParameters
            | Lithic::AuthRules::Conditional3DSActionParameters
            | Lithic::AuthRules::ConditionalAuthorizationActionParameters
            | Lithic::AuthRules::ConditionalACHActionParameters
            | Lithic::AuthRules::ConditionalTokenizationActionParameters

          module Parameters
            extend Lithic::Internal::Type::Union

            def self?.variants: -> ::Array[Lithic::Models::AuthRules::AuthRule::DraftVersion::parameters]
          end
        end

        type state = :ACTIVE | :INACTIVE

        module State
          extend Lithic::Internal::Type::Enum

          ACTIVE: :ACTIVE
          INACTIVE: :INACTIVE

          def self?.values: -> ::Array[Lithic::Models::AuthRules::AuthRule::state]
        end

        type type_ =
          :CONDITIONAL_BLOCK
          | :VELOCITY_LIMIT
          | :MERCHANT_LOCK
          | :CONDITIONAL_ACTION

        module Type
          extend Lithic::Internal::Type::Enum

          CONDITIONAL_BLOCK: :CONDITIONAL_BLOCK
          VELOCITY_LIMIT: :VELOCITY_LIMIT
          MERCHANT_LOCK: :MERCHANT_LOCK
          CONDITIONAL_ACTION: :CONDITIONAL_ACTION

          def self?.values: -> ::Array[Lithic::Models::AuthRules::AuthRule::type_]
        end
      end
    end
  end
end
