module Lithic
  module Models
    class AuthRuleVersion = AuthRules::AuthRuleVersion

    module AuthRules
      type auth_rule_version =
        {
          created: Time,
          parameters: Lithic::Models::AuthRules::AuthRuleVersion::parameters,
          state: Lithic::Models::AuthRules::AuthRuleVersion::state,
          version: Integer
        }

      class AuthRuleVersion < Lithic::Internal::Type::BaseModel
        attr_accessor created: Time

        attr_accessor parameters: Lithic::Models::AuthRules::AuthRuleVersion::parameters

        attr_accessor state: Lithic::Models::AuthRules::AuthRuleVersion::state

        attr_accessor version: Integer

        def initialize: (
          created: Time,
          parameters: Lithic::Models::AuthRules::AuthRuleVersion::parameters,
          state: Lithic::Models::AuthRules::AuthRuleVersion::state,
          version: Integer
        ) -> void

        def to_hash: -> {
          created: Time,
          parameters: Lithic::Models::AuthRules::AuthRuleVersion::parameters,
          state: Lithic::Models::AuthRules::AuthRuleVersion::state,
          version: Integer
        }

        type parameters =
          Lithic::AuthRules::ConditionalBlockParameters
          | Lithic::AuthRules::VelocityLimitParams
          | Lithic::AuthRules::MerchantLockParameters
          | Lithic::AuthRules::Conditional3DSActionParameters
          | Lithic::AuthRules::ConditionalAuthorizationActionParameters
          | Lithic::AuthRules::ConditionalACHActionParameters
          | Lithic::AuthRules::ConditionalTokenizationActionParameters
          | Lithic::AuthRules::TypescriptCodeParameters

        module Parameters
          extend Lithic::Internal::Type::Union

          def self?.variants: -> ::Array[Lithic::Models::AuthRules::AuthRuleVersion::parameters]
        end

        type state = :ACTIVE | :SHADOW | :INACTIVE

        module State
          extend Lithic::Internal::Type::Enum

          ACTIVE: :ACTIVE
          SHADOW: :SHADOW
          INACTIVE: :INACTIVE

          def self?.values: -> ::Array[Lithic::Models::AuthRules::AuthRuleVersion::state]
        end
      end
    end
  end
end
