module Lithic
  module Models
    module AuthRules
      type conditional_operation =
        :IS_ONE_OF
        | :IS_NOT_ONE_OF
        | :MATCHES
        | :DOES_NOT_MATCH
        | :IS_EQUAL_TO
        | :IS_NOT_EQUAL_TO
        | :IS_GREATER_THAN
        | :IS_GREATER_THAN_OR_EQUAL_TO
        | :IS_LESS_THAN
        | :IS_LESS_THAN_OR_EQUAL_TO
        | :CONTAINS_ANY
        | :CONTAINS_ALL
        | :CONTAINS_NONE

      module ConditionalOperation
        extend Lithic::Internal::Type::Enum

        IS_ONE_OF: :IS_ONE_OF
        IS_NOT_ONE_OF: :IS_NOT_ONE_OF
        MATCHES: :MATCHES
        DOES_NOT_MATCH: :DOES_NOT_MATCH
        IS_EQUAL_TO: :IS_EQUAL_TO
        IS_NOT_EQUAL_TO: :IS_NOT_EQUAL_TO
        IS_GREATER_THAN: :IS_GREATER_THAN
        IS_GREATER_THAN_OR_EQUAL_TO: :IS_GREATER_THAN_OR_EQUAL_TO
        IS_LESS_THAN: :IS_LESS_THAN
        IS_LESS_THAN_OR_EQUAL_TO: :IS_LESS_THAN_OR_EQUAL_TO
        CONTAINS_ANY: :CONTAINS_ANY
        CONTAINS_ALL: :CONTAINS_ALL
        CONTAINS_NONE: :CONTAINS_NONE

        def self?.values: -> ::Array[Lithic::Models::AuthRules::conditional_operation]
      end
    end
  end
end
