module Lithic
  module Models
    module AuthRules
      type conditional_block_parameters =
        { conditions: ::Array[Lithic::AuthRules::AuthRuleCondition] }

      class ConditionalBlockParameters < Lithic::Internal::Type::BaseModel
        attr_accessor conditions: ::Array[Lithic::AuthRules::AuthRuleCondition]

        def initialize: (
          conditions: ::Array[Lithic::AuthRules::AuthRuleCondition]
        ) -> void

        def to_hash: -> {
          conditions: ::Array[Lithic::AuthRules::AuthRuleCondition]
        }
      end
    end
  end
end
