module Lithic
  module Models
    module AuthRules
      type conditional_authorization_action_parameters =
        {
          action: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::action,
          conditions: ::Array[Lithic::AuthRules::AuthRuleCondition]
        }

      class ConditionalAuthorizationActionParameters < Lithic::Internal::Type::BaseModel
        attr_accessor action: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::action

        attr_accessor conditions: ::Array[Lithic::AuthRules::AuthRuleCondition]

        def initialize: (
          action: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::action,
          conditions: ::Array[Lithic::AuthRules::AuthRuleCondition]
        ) -> void

        def to_hash: -> {
          action: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::action,
          conditions: ::Array[Lithic::AuthRules::AuthRuleCondition]
        }

        type action = :DECLINE | :CHALLENGE

        module Action
          extend Lithic::Internal::Type::Enum

          DECLINE: :DECLINE
          CHALLENGE: :CHALLENGE

          def self?.values: -> ::Array[Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::action]
        end
      end
    end
  end
end
