module Lithic
  module Models
    module AuthRules
      type conditional_authorization_action_parameters =
        {
          action: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::action,
          conditions: ::Array[Lithic::AuthRules::ConditionalAuthorizationActionParameters::Condition]
        }

      class ConditionalAuthorizationActionParameters < Lithic::Internal::Type::BaseModel
        attr_accessor action: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::action

        attr_accessor conditions: ::Array[Lithic::AuthRules::ConditionalAuthorizationActionParameters::Condition]

        def initialize: (
          action: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::action,
          conditions: ::Array[Lithic::AuthRules::ConditionalAuthorizationActionParameters::Condition]
        ) -> void

        def to_hash: -> {
          action: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::action,
          conditions: ::Array[Lithic::AuthRules::ConditionalAuthorizationActionParameters::Condition]
        }

        type action = :DECLINE | :CHALLENGE

        module Action
          extend Lithic::Internal::Type::Enum

          DECLINE: :DECLINE
          CHALLENGE: :CHALLENGE

          def self?.values: -> ::Array[Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::action]
        end

        type condition =
          {
            attribute: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::attribute,
            operation: Lithic::Models::AuthRules::conditional_operation,
            value: Lithic::Models::AuthRules::conditional_value,
            parameters: Lithic::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters
          }

        class Condition < Lithic::Internal::Type::BaseModel
          attr_accessor attribute: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::attribute

          attr_accessor operation: Lithic::Models::AuthRules::conditional_operation

          attr_accessor value: Lithic::Models::AuthRules::conditional_value

          attr_reader parameters: Lithic::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters?

          def parameters=: (
            Lithic::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters
          ) -> Lithic::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters

          def initialize: (
            attribute: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::attribute,
            operation: Lithic::Models::AuthRules::conditional_operation,
            value: Lithic::Models::AuthRules::conditional_value,
            ?parameters: Lithic::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters
          ) -> void

          def to_hash: -> {
            attribute: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::attribute,
            operation: Lithic::Models::AuthRules::conditional_operation,
            value: Lithic::Models::AuthRules::conditional_value,
            parameters: Lithic::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters
          }

          type attribute =
            :MCC
            | :COUNTRY
            | :CURRENCY
            | :MERCHANT_ID
            | :DESCRIPTOR
            | :LIABILITY_SHIFT
            | :PAN_ENTRY_MODE
            | :TRANSACTION_AMOUNT
            | :CASH_AMOUNT
            | :RISK_SCORE
            | :CARD_TRANSACTION_COUNT_15M
            | :CARD_TRANSACTION_COUNT_1H
            | :CARD_TRANSACTION_COUNT_24H
            | :CARD_DECLINE_COUNT_15M
            | :CARD_DECLINE_COUNT_1H
            | :CARD_DECLINE_COUNT_24H
            | :CARD_STATE
            | :PIN_ENTERED
            | :PIN_STATUS
            | :WALLET_TYPE
            | :TRANSACTION_INITIATOR
            | :ADDRESS_MATCH
            | :SERVICE_LOCATION_STATE
            | :SERVICE_LOCATION_POSTAL_CODE
            | :CARD_AGE
            | :ACCOUNT_AGE
            | :AMOUNT_Z_SCORE
            | :AVG_TRANSACTION_AMOUNT
            | :STDEV_TRANSACTION_AMOUNT
            | :IS_NEW_COUNTRY
            | :IS_NEW_MCC
            | :IS_FIRST_TRANSACTION
            | :CONSECUTIVE_DECLINES
            | :TIME_SINCE_LAST_TRANSACTION
            | :DISTINCT_COUNTRY_COUNT
            | :IS_NEW_MERCHANT
            | :THREE_DS_SUCCESS_RATE
            | :TRAVEL_SPEED
            | :DISTANCE_FROM_LAST_TRANSACTION

          module Attribute
            extend Lithic::Internal::Type::Enum

            MCC: :MCC
            COUNTRY: :COUNTRY
            CURRENCY: :CURRENCY
            MERCHANT_ID: :MERCHANT_ID
            DESCRIPTOR: :DESCRIPTOR
            LIABILITY_SHIFT: :LIABILITY_SHIFT
            PAN_ENTRY_MODE: :PAN_ENTRY_MODE
            TRANSACTION_AMOUNT: :TRANSACTION_AMOUNT
            CASH_AMOUNT: :CASH_AMOUNT
            RISK_SCORE: :RISK_SCORE
            CARD_TRANSACTION_COUNT_15_M: :CARD_TRANSACTION_COUNT_15M
            CARD_TRANSACTION_COUNT_1_H: :CARD_TRANSACTION_COUNT_1H
            CARD_TRANSACTION_COUNT_24_H: :CARD_TRANSACTION_COUNT_24H
            CARD_DECLINE_COUNT_15_M: :CARD_DECLINE_COUNT_15M
            CARD_DECLINE_COUNT_1_H: :CARD_DECLINE_COUNT_1H
            CARD_DECLINE_COUNT_24_H: :CARD_DECLINE_COUNT_24H
            CARD_STATE: :CARD_STATE
            PIN_ENTERED: :PIN_ENTERED
            PIN_STATUS: :PIN_STATUS
            WALLET_TYPE: :WALLET_TYPE
            TRANSACTION_INITIATOR: :TRANSACTION_INITIATOR
            ADDRESS_MATCH: :ADDRESS_MATCH
            SERVICE_LOCATION_STATE: :SERVICE_LOCATION_STATE
            SERVICE_LOCATION_POSTAL_CODE: :SERVICE_LOCATION_POSTAL_CODE
            CARD_AGE: :CARD_AGE
            ACCOUNT_AGE: :ACCOUNT_AGE
            AMOUNT_Z_SCORE: :AMOUNT_Z_SCORE
            AVG_TRANSACTION_AMOUNT: :AVG_TRANSACTION_AMOUNT
            STDEV_TRANSACTION_AMOUNT: :STDEV_TRANSACTION_AMOUNT
            IS_NEW_COUNTRY: :IS_NEW_COUNTRY
            IS_NEW_MCC: :IS_NEW_MCC
            IS_FIRST_TRANSACTION: :IS_FIRST_TRANSACTION
            CONSECUTIVE_DECLINES: :CONSECUTIVE_DECLINES
            TIME_SINCE_LAST_TRANSACTION: :TIME_SINCE_LAST_TRANSACTION
            DISTINCT_COUNTRY_COUNT: :DISTINCT_COUNTRY_COUNT
            IS_NEW_MERCHANT: :IS_NEW_MERCHANT
            THREE_DS_SUCCESS_RATE: :THREE_DS_SUCCESS_RATE
            TRAVEL_SPEED: :TRAVEL_SPEED
            DISTANCE_FROM_LAST_TRANSACTION: :DISTANCE_FROM_LAST_TRANSACTION

            def self?.values: -> ::Array[Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::attribute]
          end

          type parameters =
            {
              interval: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::interval,
              scope: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::scope,
              unit: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::unit
            }

          class Parameters < Lithic::Internal::Type::BaseModel
            attr_reader interval: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::interval?

            def interval=: (
              Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::interval
            ) -> Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::interval

            attr_reader scope: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::scope?

            def scope=: (
              Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::scope
            ) -> Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::scope

            attr_reader unit: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::unit?

            def unit=: (
              Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::unit
            ) -> Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::unit

            def initialize: (
              ?interval: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::interval,
              ?scope: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::scope,
              ?unit: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::unit
            ) -> void

            def to_hash: -> {
              interval: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::interval,
              scope: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::scope,
              unit: Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::unit
            }

            type interval = :LIFETIME | :"7D" | :"30D" | :"90D"

            module Interval
              extend Lithic::Internal::Type::Enum

              LIFETIME: :LIFETIME
              INTERVAL_7_D: :"7D"
              INTERVAL_30_D: :"30D"
              INTERVAL_90_D: :"90D"

              def self?.values: -> ::Array[Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::interval]
            end

            type scope = :CARD | :ACCOUNT | :BUSINESS_ACCOUNT

            module Scope
              extend Lithic::Internal::Type::Enum

              CARD: :CARD
              ACCOUNT: :ACCOUNT
              BUSINESS_ACCOUNT: :BUSINESS_ACCOUNT

              def self?.values: -> ::Array[Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::scope]
            end

            type unit = :MPH | :KPH | :MILES | :KILOMETERS

            module Unit
              extend Lithic::Internal::Type::Enum

              MPH: :MPH
              KPH: :KPH
              MILES: :MILES
              KILOMETERS: :KILOMETERS

              def self?.values: -> ::Array[Lithic::Models::AuthRules::ConditionalAuthorizationActionParameters::Condition::Parameters::unit]
            end
          end
        end
      end
    end
  end
end
