module Lithic
  module Models
    module AuthRules
      type conditional_block_parameters =
        { conditions: ::Array[Lithic::Models::AuthRules::AuthRuleCondition] }

      class ConditionalBlockParameters < Lithic::BaseModel
        attr_accessor conditions: ::Array[Lithic::Models::AuthRules::AuthRuleCondition]

        def initialize: (
          conditions: ::Array[Lithic::Models::AuthRules::AuthRuleCondition]
        ) -> void

        def to_hash: -> Lithic::Models::AuthRules::conditional_block_parameters
      end
    end
  end
end
