module Lithic
  module Models
    module AuthRules
      type spend_velocity_filters =
        {
          exclude_tags: ::Hash[Symbol, String]?,
          include_tags: ::Hash[Symbol, String]?
        }

      class SpendVelocityFilters < Lithic::Models::AuthRules::VelocityLimitFilters
        def exclude_tags: -> ::Hash[Symbol, String]?

        def exclude_tags=: (
          ::Hash[Symbol, String]? _
        ) -> ::Hash[Symbol, String]?

        def include_tags: -> ::Hash[Symbol, String]?

        def include_tags=: (
          ::Hash[Symbol, String]? _
        ) -> ::Hash[Symbol, String]?

        def initialize: (
          ?exclude_tags: ::Hash[Symbol, String]?,
          ?include_tags: ::Hash[Symbol, String]?
        ) -> void

        def to_hash: -> {
          exclude_tags: ::Hash[Symbol, String]?,
          include_tags: ::Hash[Symbol, String]?
        }
      end
    end
  end
end
