module Lithic
  module Models
    module AuthRules
      type v2_delete_params = {  } & Lithic::Internal::Type::request_parameters

      class V2DeleteParams < Lithic::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        def initialize: (?request_options: Lithic::request_opts) -> void

        def to_hash: -> Lithic::Models::AuthRules::v2_delete_params
      end
    end
  end
end
