module Lithic
  module Models
    module AuthRules
      type v2_delete_params =
        { auth_rule_token: String } & Lithic::Internal::Type::request_parameters

      class V2DeleteParams < Lithic::Internal::Type::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        attr_accessor auth_rule_token: String

        def initialize: (
          auth_rule_token: String,
          ?request_options: Lithic::request_opts
        ) -> void

        def to_hash: -> {
          auth_rule_token: String,
          request_options: Lithic::RequestOptions
        }
      end
    end
  end
end
