module Lithic
  module Models
    module AuthRules
      type v2_list_versions_response =
        { data: ::Array[Lithic::AuthRules::AuthRuleVersion] }

      class V2ListVersionsResponse < Lithic::Internal::Type::BaseModel
        attr_accessor data: ::Array[Lithic::AuthRules::AuthRuleVersion]

        def initialize: (
          data: ::Array[Lithic::AuthRules::AuthRuleVersion]
        ) -> void

        def to_hash: -> { data: ::Array[Lithic::AuthRules::AuthRuleVersion] }
      end
    end
  end
end
