module Lithic
  module Models
    module AuthRules
      type v2_report_response = { report_token: String }

      class V2ReportResponse < Lithic::Internal::Type::BaseModel
        attr_reader report_token: String?

        def report_token=: (String) -> String

        def initialize: (?report_token: String) -> void
      end
    end
  end
end
