module Lithic
  module Models
    module AuthRules
      type v2_report_params = {  } & Lithic::request_parameters

      class V2ReportParams < Lithic::BaseModel
        extend Lithic::Type::RequestParameters::Converter
        include Lithic::RequestParameters

        def initialize: (?request_options: Lithic::request_opts) -> void

        def to_hash: -> Lithic::Models::AuthRules::v2_report_params
      end
    end
  end
end
