module Lithic
  module Models
    module AuthRules
      type v2_retrieve_report_params =
        { begin_: Date, end_: Date }
        & Lithic::Internal::Type::request_parameters

      class V2RetrieveReportParams < Lithic::Internal::Type::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        attr_accessor begin_: Date

        attr_accessor end_: Date

        def initialize: (
          begin_: Date,
          end_: Date,
          ?request_options: Lithic::request_opts
        ) -> void

        def to_hash: -> {
          begin_: Date,
          end_: Date,
          request_options: Lithic::RequestOptions
        }
      end
    end
  end
end
