module Lithic
  module Models
    module AuthRules
      type v2_retrieve_features_response =
        {
          evaluated: Time,
          features: ::Array[Lithic::Models::AuthRules::V2RetrieveFeaturesResponse::Feature]
        }

      class V2RetrieveFeaturesResponse < Lithic::Internal::Type::BaseModel
        attr_accessor evaluated: Time

        attr_accessor features: ::Array[Lithic::Models::AuthRules::V2RetrieveFeaturesResponse::Feature]

        def initialize: (
          evaluated: Time,
          features: ::Array[Lithic::Models::AuthRules::V2RetrieveFeaturesResponse::Feature]
        ) -> void

        def to_hash: -> {
          evaluated: Time,
          features: ::Array[Lithic::Models::AuthRules::V2RetrieveFeaturesResponse::Feature]
        }

        type feature =
          {
            filters: Lithic::AuthRules::VelocityLimitFilters,
            period: Lithic::Models::AuthRules::velocity_limit_period,
            scope: Lithic::Models::AuthRules::V2RetrieveFeaturesResponse::Feature::scope,
            value: Lithic::Models::AuthRules::V2RetrieveFeaturesResponse::Feature::Value
          }

        class Feature < Lithic::Internal::Type::BaseModel
          attr_accessor filters: Lithic::AuthRules::VelocityLimitFilters

          attr_accessor period: Lithic::Models::AuthRules::velocity_limit_period

          attr_accessor scope: Lithic::Models::AuthRules::V2RetrieveFeaturesResponse::Feature::scope

          attr_accessor value: Lithic::Models::AuthRules::V2RetrieveFeaturesResponse::Feature::Value

          def initialize: (
            filters: Lithic::AuthRules::VelocityLimitFilters,
            period: Lithic::Models::AuthRules::velocity_limit_period,
            scope: Lithic::Models::AuthRules::V2RetrieveFeaturesResponse::Feature::scope,
            value: Lithic::Models::AuthRules::V2RetrieveFeaturesResponse::Feature::Value
          ) -> void

          def to_hash: -> {
            filters: Lithic::AuthRules::VelocityLimitFilters,
            period: Lithic::Models::AuthRules::velocity_limit_period,
            scope: Lithic::Models::AuthRules::V2RetrieveFeaturesResponse::Feature::scope,
            value: Lithic::Models::AuthRules::V2RetrieveFeaturesResponse::Feature::Value
          }

          type scope = :CARD | :ACCOUNT

          module Scope
            extend Lithic::Internal::Type::Enum

            CARD: :CARD
            ACCOUNT: :ACCOUNT

            def self?.values: -> ::Array[Lithic::Models::AuthRules::V2RetrieveFeaturesResponse::Feature::scope]
          end

          type value = { amount: Integer, count: Integer }

          class Value < Lithic::Internal::Type::BaseModel
            attr_accessor amount: Integer

            attr_accessor count: Integer

            def initialize: (amount: Integer, count: Integer) -> void

            def to_hash: -> { amount: Integer, count: Integer }
          end
        end
      end
    end
  end
end
