module Lithic
  module Models
    module AuthRules
      type velocity_limit_params_period_window =
        Lithic::AuthRules::VelocityLimitParamsPeriodWindow::TrailingWindowObject
        | Lithic::AuthRules::VelocityLimitParamsPeriodWindow::FixedWindowDay
        | Lithic::AuthRules::VelocityLimitParamsPeriodWindow::FixedWindowWeek
        | Lithic::AuthRules::VelocityLimitParamsPeriodWindow::FixedWindowMonth
        | Lithic::AuthRules::VelocityLimitParamsPeriodWindow::FixedWindowYear

      module VelocityLimitParamsPeriodWindow
        extend Lithic::Internal::Type::Union

        type trailing_window_object = { duration: Integer, type: :CUSTOM }

        class TrailingWindowObject < Lithic::Internal::Type::BaseModel
          attr_accessor duration: Integer

          attr_accessor type: :CUSTOM

          def initialize: (duration: Integer, ?type: :CUSTOM) -> void

          def to_hash: -> { duration: Integer, type: :CUSTOM }
        end

        type fixed_window_day = { type: :DAY }

        class FixedWindowDay < Lithic::Internal::Type::BaseModel
          attr_accessor type: :DAY

          def initialize: (?type: :DAY) -> void

          def to_hash: -> { type: :DAY }
        end

        type fixed_window_week = { type: :WEEK, day_of_week: Integer }

        class FixedWindowWeek < Lithic::Internal::Type::BaseModel
          attr_accessor type: :WEEK

          attr_reader day_of_week: Integer?

          def day_of_week=: (Integer) -> Integer

          def initialize: (?day_of_week: Integer, ?type: :WEEK) -> void

          def to_hash: -> { type: :WEEK, day_of_week: Integer }
        end

        type fixed_window_month = { type: :MONTH, day_of_month: Integer }

        class FixedWindowMonth < Lithic::Internal::Type::BaseModel
          attr_accessor type: :MONTH

          attr_reader day_of_month: Integer?

          def day_of_month=: (Integer) -> Integer

          def initialize: (?day_of_month: Integer, ?type: :MONTH) -> void

          def to_hash: -> { type: :MONTH, day_of_month: Integer }
        end

        type fixed_window_year =
          { type: :YEAR, day_of_month: Integer, month: Integer }

        class FixedWindowYear < Lithic::Internal::Type::BaseModel
          attr_accessor type: :YEAR

          attr_reader day_of_month: Integer?

          def day_of_month=: (Integer) -> Integer

          attr_reader month: Integer?

          def month=: (Integer) -> Integer

          def initialize: (
            ?day_of_month: Integer,
            ?month: Integer,
            ?type: :YEAR
          ) -> void

          def to_hash: -> { type: :YEAR, day_of_month: Integer, month: Integer }
        end

        def self?.variants: -> ::Array[Lithic::Models::AuthRules::velocity_limit_params_period_window]
      end
    end
  end
end
