module Lithic
  module Models
    module AuthRules
      type velocity_limit_params =
        {
          period: Lithic::Models::AuthRules::velocity_limit_period,
          scope: Lithic::Models::AuthRules::VelocityLimitParams::scope,
          filters: Lithic::AuthRules::VelocityLimitFilters,
          limit_amount: Integer?,
          limit_count: Integer?
        }

      class VelocityLimitParams < Lithic::Internal::Type::BaseModel
        attr_accessor period: Lithic::Models::AuthRules::velocity_limit_period

        attr_accessor scope: Lithic::Models::AuthRules::VelocityLimitParams::scope

        attr_reader filters: Lithic::AuthRules::VelocityLimitFilters?

        def filters=: (
          Lithic::AuthRules::VelocityLimitFilters
        ) -> Lithic::AuthRules::VelocityLimitFilters

        attr_accessor limit_amount: Integer?

        attr_accessor limit_count: Integer?

        def initialize: (
          period: Lithic::Models::AuthRules::velocity_limit_period,
          scope: Lithic::Models::AuthRules::VelocityLimitParams::scope,
          ?filters: Lithic::AuthRules::VelocityLimitFilters,
          ?limit_amount: Integer?,
          ?limit_count: Integer?
        ) -> void

        def to_hash: -> {
          period: Lithic::Models::AuthRules::velocity_limit_period,
          scope: Lithic::Models::AuthRules::VelocityLimitParams::scope,
          filters: Lithic::AuthRules::VelocityLimitFilters,
          limit_amount: Integer?,
          limit_count: Integer?
        }

        type scope = :CARD | :ACCOUNT

        module Scope
          extend Lithic::Internal::Type::Enum

          CARD: :CARD
          ACCOUNT: :ACCOUNT

          def self?.values: -> ::Array[Lithic::Models::AuthRules::VelocityLimitParams::scope]
        end
      end
    end
  end
end
