module Lithic
  module Models
    module TransactionMonitoring
      type case_retrieve_params =
        { case_token: String } & Lithic::Internal::Type::request_parameters

      class CaseRetrieveParams < Lithic::Internal::Type::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        attr_accessor case_token: String

        def initialize: (
          case_token: String,
          ?request_options: Lithic::request_opts
        ) -> void

        def to_hash: -> {
          case_token: String,
          request_options: Lithic::RequestOptions
        }
      end
    end
  end
end
