module Lithic
  module Models
    module TransactionMonitoring
      type queue_update_params =
        { queue_token: String, description: String?, name: String }
        & Lithic::Internal::Type::request_parameters

      class QueueUpdateParams < Lithic::Internal::Type::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        attr_accessor queue_token: String

        attr_accessor description: String?

        attr_reader name: String?

        def name=: (String) -> String

        def initialize: (
          queue_token: String,
          ?description: String?,
          ?name: String,
          ?request_options: Lithic::request_opts
        ) -> void

        def to_hash: -> {
          queue_token: String,
          description: String?,
          name: String,
          request_options: Lithic::RequestOptions
        }
      end
    end
  end
end
