module Lithic
  module Internal
    module Type
      module Converter
        type input = Lithic::Internal::Type::Converter | Class

        type coerce_state =
          {
            strictness: bool | :strong,
            exactness: { yes: Integer, no: Integer, maybe: Integer },
            branched: Integer
          }

        type dump_state = { can_retry: bool }

        def coerce: (
          top value,
          state: Lithic::Internal::Type::Converter::coerce_state
        ) -> top

        def dump: (
          top value,
          state: Lithic::Internal::Type::Converter::dump_state
        ) -> top

        def self.type_info: (
          {
            const: (nil | bool | Integer | Float | Symbol)?,
            enum: ^-> Lithic::Internal::Type::Converter::input?,
            union: ^-> Lithic::Internal::Type::Converter::input?
          }
          | ^-> Lithic::Internal::Type::Converter::input
          | Lithic::Internal::Type::Converter::input spec
        ) -> (^-> top)

        def self.coerce: (
          Lithic::Internal::Type::Converter::input target,
          top value,
          ?state: Lithic::Internal::Type::Converter::coerce_state
        ) -> top

        def self.dump: (
          Lithic::Internal::Type::Converter::input target,
          top value,
          ?state: Lithic::Internal::Type::Converter::dump_state
        ) -> top
      end
    end
  end
end
