module Lithic
  module Internal
    module Type
      module Union
        include Lithic::Internal::Type::Converter

        private def self.known_variants: -> ::Array[[Symbol?, (^-> Lithic::Internal::Type::Converter::input)]]

        def self.derefed_variants: -> ::Array[[Symbol?, top]]

        def self.variants: -> ::Array[top]

        private def self.discriminator: (Symbol property) -> void

        private def self.variant: (
          Symbol
          | ::Hash[Symbol, top]
          | ^-> Lithic::Internal::Type::Converter::input
          | Lithic::Internal::Type::Converter::input key,
          ?::Hash[Symbol, top]
          | ^-> Lithic::Internal::Type::Converter::input
          | Lithic::Internal::Type::Converter::input spec
        ) -> void

        private def self.resolve_variant: (
          top value
        ) -> Lithic::Internal::Type::Converter::input?

        def ===: (top other) -> bool

        def ==: (top other) -> bool

        def coerce: (
          top value,
          state: Lithic::Internal::Type::Converter::coerce_state
        ) -> top

        def dump: (
          top value,
          state: Lithic::Internal::Type::Converter::dump_state
        ) -> top

        def inspect: (?depth: Integer) -> String
      end
    end
  end
end
