module Lithic
  module Models
    module ThreeDS
      type authentication_simulate_response = { token: String }

      class AuthenticationSimulateResponse < Lithic::Internal::Type::BaseModel
        attr_reader token: String?

        def token=: (String) -> String

        def initialize: (?token: String) -> void

        def to_hash: -> { token: String }
      end
    end
  end
end
