module Lithic
  module Models
    module ThreeDS
      type authentication_simulate_otp_entry_params =
        { token: String, otp: String }
        & Lithic::Internal::Type::request_parameters

      class AuthenticationSimulateOtpEntryParams < Lithic::Internal::Type::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        attr_accessor token: String

        attr_accessor otp: String

        def initialize: (
          token: String,
          otp: String,
          ?request_options: Lithic::request_opts
        ) -> void

        def to_hash: -> Lithic::Models::ThreeDS::authentication_simulate_otp_entry_params
      end
    end
  end
end
