module Lithic
  module Models
    module ThreeDS
      type challenge_response =
        {
          token: String,
          challenge_response: Lithic::Models::ThreeDS::challenge_result
        }

      class ChallengeResponse < Lithic::Internal::Type::BaseModel
        attr_accessor token: String

        attr_accessor challenge_response: Lithic::Models::ThreeDS::challenge_result

        def initialize: (
          token: String,
          challenge_response: Lithic::Models::ThreeDS::challenge_result
        ) -> void

        def to_hash: -> {
          token: String,
          challenge_response: Lithic::Models::ThreeDS::challenge_result
        }
      end
    end
  end
end
