module Lithic
  module Models
    module ThreeDS
      type decisioning_retrieve_secret_response = { secret: String }

      class DecisioningRetrieveSecretResponse < Lithic::Internal::Type::BaseModel
        attr_reader secret: String?

        def secret=: (String) -> String

        def initialize: (?secret: String) -> void
      end
    end
  end
end
