module Lithic
  module Models
    module ThreeDS
      type decisioning_retrieve_secret_params =
        {  } & Lithic::request_parameters

      class DecisioningRetrieveSecretParams < Lithic::BaseModel
        extend Lithic::Type::RequestParameters::Converter
        include Lithic::RequestParameters

        def initialize: (?request_options: Lithic::request_opts) -> void

        def to_hash: -> Lithic::Models::ThreeDS::decisioning_retrieve_secret_params
      end
    end
  end
end
