module Lithic
  module Models
    module ThreeDS
      type decisioning_retrieve_secret_params =
        {  } & Lithic::Internal::Type::request_parameters

      class DecisioningRetrieveSecretParams < Lithic::Internal::Type::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        def initialize: (?request_options: Lithic::request_opts) -> void

        def to_hash: -> Lithic::Models::ThreeDS::decisioning_retrieve_secret_params
      end
    end
  end
end
