module Lithic
  module Models
    module ThreeDS
      type decisioning_rotate_secret_params = {  } & Lithic::request_parameters

      class DecisioningRotateSecretParams < Lithic::BaseModel
        extend Lithic::RequestParameters::Converter
        include Lithic::RequestParameters

        def initialize: (?request_options: Lithic::request_opts) -> void

        def to_hash: -> Lithic::Models::ThreeDS::decisioning_rotate_secret_params
      end
    end
  end
end
