module Lithic
  module Models
    module ThreeDS
      type decisioning_challenge_response_params =
        {  } & Lithic::Internal::Type::request_parameters

      class DecisioningChallengeResponseParams < Lithic::Models::ThreeDS::ChallengeResponse
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        def initialize: (?request_options: Lithic::request_opts) -> void

        def to_hash: -> { request_options: Lithic::RequestOptions }
      end
    end
  end
end
