module Lithic
  module Models
    module AuthRules
      module V2
        type backtest_retrieve_params =
          { auth_rule_token: String }
          & Lithic::Internal::Type::request_parameters

        class BacktestRetrieveParams < Lithic::Internal::Type::BaseModel
          extend Lithic::Internal::Type::RequestParameters::Converter
          include Lithic::Internal::Type::RequestParameters

          attr_accessor auth_rule_token: String

          def initialize: (
            auth_rule_token: String,
            ?request_options: Lithic::request_opts
          ) -> void

          def to_hash: -> Lithic::Models::AuthRules::V2::backtest_retrieve_params
        end
      end
    end
  end
end
