module Lithic
  module Models
    module AuthRules
      module V2
        type backtest_create_response = { backtest_token: String }

        class BacktestCreateResponse < Lithic::Internal::Type::BaseModel
          attr_reader backtest_token: String?

          def backtest_token=: (String) -> String

          def initialize: (?backtest_token: String) -> void
        end
      end
    end
  end
end
