module Lithic
  module Models
    module Reports
      type settlement_list_details_params =
        { ending_before: String, page_size: Integer, starting_after: String }
        & Lithic::Internal::Type::request_parameters

      class SettlementListDetailsParams < Lithic::Internal::Type::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        attr_reader ending_before: String?

        def ending_before=: (String) -> String

        attr_reader page_size: Integer?

        def page_size=: (Integer) -> Integer

        attr_reader starting_after: String?

        def starting_after=: (String) -> String

        def initialize: (
          ?ending_before: String,
          ?page_size: Integer,
          ?starting_after: String,
          ?request_options: Lithic::request_opts
        ) -> void
      end
    end
  end
end
