module Lithic
  module Models
    module Reports
      type settlement_summary_params =
        {  } & Lithic::Internal::Type::request_parameters

      class SettlementSummaryParams < Lithic::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        def initialize: (?request_options: Lithic::request_opts) -> void

        def to_hash: -> Lithic::Models::Reports::settlement_summary_params
      end
    end
  end
end
