module Lithic
  module Models
    module Transactions
      module Events
        type enhanced_commercial_data_retrieve_params =
          {  } & Lithic::Internal::Type::request_parameters

        class EnhancedCommercialDataRetrieveParams < Lithic::Internal::Type::BaseModel
          extend Lithic::Internal::Type::RequestParameters::Converter
          include Lithic::Internal::Type::RequestParameters

          def initialize: (?request_options: Lithic::request_opts) -> void

          def to_hash: -> { request_options: Lithic::RequestOptions }
        end
      end
    end
  end
end
