module Lithic
  module Resources
    class Reports
      class Settlement
        class NetworkTotals
          def retrieve: (
            String token,
            ?request_options: Lithic::request_opts
          ) -> Lithic::NetworkTotal

          def list: (
            ?begin_: Time,
            ?end_: Time,
            ?ending_before: String,
            ?institution_id: String,
            ?network: Lithic::Models::Reports::Settlement::NetworkTotalListParams::network,
            ?page_size: Integer,
            ?report_date: Date,
            ?report_date_begin: Date,
            ?report_date_end: Date,
            ?settlement_institution_id: String,
            ?starting_after: String,
            ?request_options: Lithic::request_opts
          ) -> Lithic::Internal::CursorPage[Lithic::NetworkTotal]

          def initialize: (client: Lithic::Client) -> void
        end
      end
    end
  end
end
