module Lithic
  module Models
    module FinancialAccounts
      type credit_configuration_retrieve_params =
        {  } & Lithic::Internal::Type::request_parameters

      class CreditConfigurationRetrieveParams < Lithic::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        def initialize: (?request_options: Lithic::request_opts) -> void

        def to_hash: -> Lithic::Models::FinancialAccounts::credit_configuration_retrieve_params
      end
    end
  end
end
