module Lithic
  module Models
    module FinancialAccounts
      type financial_transaction_retrieve_params =
        { financial_account_token: String }
        & Lithic::Internal::Type::request_parameters

      class FinancialTransactionRetrieveParams < Lithic::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        attr_accessor financial_account_token: String

        def initialize: (
          financial_account_token: String,
          ?request_options: Lithic::request_opts
        ) -> void

        def to_hash: -> Lithic::Models::FinancialAccounts::financial_transaction_retrieve_params
      end
    end
  end
end
