module Lithic
  module Models
    class FinancialAccountCreditConfig = FinancialAccounts::FinancialAccountCreditConfig

    module FinancialAccounts
      type financial_account_credit_config =
        {
          account_token: String,
          auto_collection_configuration: Lithic::FinancialAccounts::FinancialAccountCreditConfig::AutoCollectionConfiguration,
          credit_limit: Integer?,
          credit_product_token: String?,
          external_bank_account_token: String?,
          tier: String?,
          charged_off_reason: Lithic::Models::FinancialAccounts::FinancialAccountCreditConfig::charged_off_reason?,
          financial_account_state: Lithic::Models::FinancialAccounts::FinancialAccountCreditConfig::financial_account_state,
          is_spend_blocked: bool
        }

      class FinancialAccountCreditConfig < Lithic::Internal::Type::BaseModel
        attr_accessor account_token: String

        attr_accessor auto_collection_configuration: Lithic::FinancialAccounts::FinancialAccountCreditConfig::AutoCollectionConfiguration

        attr_accessor credit_limit: Integer?

        attr_accessor credit_product_token: String?

        attr_accessor external_bank_account_token: String?

        attr_accessor tier: String?

        attr_accessor charged_off_reason: Lithic::Models::FinancialAccounts::FinancialAccountCreditConfig::charged_off_reason?

        attr_reader financial_account_state: Lithic::Models::FinancialAccounts::FinancialAccountCreditConfig::financial_account_state?

        def financial_account_state=: (
          Lithic::Models::FinancialAccounts::FinancialAccountCreditConfig::financial_account_state
        ) -> Lithic::Models::FinancialAccounts::FinancialAccountCreditConfig::financial_account_state

        attr_reader is_spend_blocked: bool?

        def is_spend_blocked=: (bool) -> bool

        def initialize: (
          account_token: String,
          auto_collection_configuration: Lithic::FinancialAccounts::FinancialAccountCreditConfig::AutoCollectionConfiguration,
          credit_limit: Integer?,
          credit_product_token: String?,
          external_bank_account_token: String?,
          tier: String?,
          ?charged_off_reason: Lithic::Models::FinancialAccounts::FinancialAccountCreditConfig::charged_off_reason?,
          ?financial_account_state: Lithic::Models::FinancialAccounts::FinancialAccountCreditConfig::financial_account_state,
          ?is_spend_blocked: bool
        ) -> void

        def to_hash: -> {
          account_token: String,
          auto_collection_configuration: Lithic::FinancialAccounts::FinancialAccountCreditConfig::AutoCollectionConfiguration,
          credit_limit: Integer?,
          credit_product_token: String?,
          external_bank_account_token: String?,
          tier: String?,
          charged_off_reason: Lithic::Models::FinancialAccounts::FinancialAccountCreditConfig::charged_off_reason?,
          financial_account_state: Lithic::Models::FinancialAccounts::FinancialAccountCreditConfig::financial_account_state,
          is_spend_blocked: bool
        }

        type auto_collection_configuration = { auto_collection_enabled: bool }

        class AutoCollectionConfiguration < Lithic::Internal::Type::BaseModel
          attr_accessor auto_collection_enabled: bool

          def initialize: (auto_collection_enabled: bool) -> void

          def to_hash: -> { auto_collection_enabled: bool }
        end

        type charged_off_reason = :DELINQUENT | :FRAUD

        module ChargedOffReason
          extend Lithic::Internal::Type::Enum

          DELINQUENT: :DELINQUENT
          FRAUD: :FRAUD

          def self?.values: -> ::Array[Lithic::Models::FinancialAccounts::FinancialAccountCreditConfig::charged_off_reason]
        end

        type financial_account_state =
          :PENDING | :CURRENT | :DELINQUENT | :CHARGED_OFF

        module FinancialAccountState
          extend Lithic::Internal::Type::Enum

          PENDING: :PENDING
          CURRENT: :CURRENT
          DELINQUENT: :DELINQUENT
          CHARGED_OFF: :CHARGED_OFF

          def self?.values: -> ::Array[Lithic::Models::FinancialAccounts::FinancialAccountCreditConfig::financial_account_state]
        end
      end
    end
  end
end
