module Lithic
  module Models
    module FinancialAccounts
      type financial_accounts_interest_tier_schedule =
        {
          credit_product_token: String,
          effective_date: Date,
          tier_name: String,
          tier_rates: top
        }

      class FinancialAccountsInterestTierSchedule < Lithic::Internal::Type::BaseModel
        attr_accessor credit_product_token: String

        attr_accessor effective_date: Date

        attr_reader tier_name: String?

        def tier_name=: (String) -> String

        attr_reader tier_rates: top?

        def tier_rates=: (top) -> top

        def initialize: (
          credit_product_token: String,
          effective_date: Date,
          ?tier_name: String,
          ?tier_rates: top
        ) -> void

        def to_hash: -> {
          credit_product_token: String,
          effective_date: Date,
          tier_name: String,
          tier_rates: top
        }
      end
    end
  end
end
