module Lithic
  module Models
    module FinancialAccounts
      type interest_tier_schedule_create_params =
        {  } & Lithic::Internal::Type::request_parameters

      class InterestTierScheduleCreateParams < Lithic::Models::FinancialAccounts::FinancialAccountsInterestTierSchedule
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        def initialize: (?request_options: Lithic::request_opts) -> void

        def to_hash: -> { request_options: Lithic::RequestOptions }
      end
    end
  end
end
