module Lithic
  module Models
    module FinancialAccounts
      type interest_tier_schedule_retrieve_params =
        { financial_account_token: String, effective_date: Date }
        & Lithic::Internal::Type::request_parameters

      class InterestTierScheduleRetrieveParams < Lithic::Internal::Type::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        attr_accessor financial_account_token: String

        attr_accessor effective_date: Date

        def initialize: (
          financial_account_token: String,
          effective_date: Date,
          ?request_options: Lithic::request_opts
        ) -> void

        def to_hash: -> {
          financial_account_token: String,
          effective_date: Date,
          request_options: Lithic::RequestOptions
        }
      end
    end
  end
end
