module Lithic
  module Models
    module FinancialAccounts
      type loan_tape_retrieve_params =
        { financial_account_token: String }
        & Lithic::Internal::Type::request_parameters

      class LoanTapeRetrieveParams < Lithic::Internal::Type::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        attr_accessor financial_account_token: String

        def initialize: (
          financial_account_token: String,
          ?request_options: Lithic::request_opts
        ) -> void
      end
    end
  end
end
