module Lithic
  module Models
    module FinancialAccounts
      type statement =
        {
          token: String,
          account_standing: Lithic::FinancialAccounts::Statement::AccountStanding,
          amount_due: Lithic::FinancialAccounts::Statement::AmountDue,
          available_credit: Integer,
          created: Time,
          credit_limit: Integer,
          credit_product_token: String,
          days_in_billing_cycle: Integer,
          ending_balance: Integer,
          financial_account_token: String,
          payment_due_date: Date?,
          period_totals: Lithic::StatementTotals,
          starting_balance: Integer,
          statement_end_date: Date,
          statement_start_date: Date,
          statement_type: Lithic::Models::FinancialAccounts::Statement::statement_type,
          updated: Time,
          ytd_totals: Lithic::StatementTotals,
          interest_details: Lithic::FinancialAccounts::Statement::InterestDetails?,
          next_payment_due_date: Date,
          next_statement_end_date: Date,
          payoff_details: Lithic::FinancialAccounts::Statement::PayoffDetails?
        }

      class Statement < Lithic::Internal::Type::BaseModel
        attr_accessor token: String

        attr_accessor account_standing: Lithic::FinancialAccounts::Statement::AccountStanding

        attr_accessor amount_due: Lithic::FinancialAccounts::Statement::AmountDue

        attr_accessor available_credit: Integer

        attr_accessor created: Time

        attr_accessor credit_limit: Integer

        attr_accessor credit_product_token: String

        attr_accessor days_in_billing_cycle: Integer

        attr_accessor ending_balance: Integer

        attr_accessor financial_account_token: String

        attr_accessor payment_due_date: Date?

        attr_accessor period_totals: Lithic::StatementTotals

        attr_accessor starting_balance: Integer

        attr_accessor statement_end_date: Date

        attr_accessor statement_start_date: Date

        attr_accessor statement_type: Lithic::Models::FinancialAccounts::Statement::statement_type

        attr_accessor updated: Time

        attr_accessor ytd_totals: Lithic::StatementTotals

        attr_accessor interest_details: Lithic::FinancialAccounts::Statement::InterestDetails?

        attr_reader next_payment_due_date: Date?

        def next_payment_due_date=: (Date) -> Date

        attr_reader next_statement_end_date: Date?

        def next_statement_end_date=: (Date) -> Date

        attr_accessor payoff_details: Lithic::FinancialAccounts::Statement::PayoffDetails?

        def initialize: (
          token: String,
          account_standing: Lithic::FinancialAccounts::Statement::AccountStanding,
          amount_due: Lithic::FinancialAccounts::Statement::AmountDue,
          available_credit: Integer,
          created: Time,
          credit_limit: Integer,
          credit_product_token: String,
          days_in_billing_cycle: Integer,
          ending_balance: Integer,
          financial_account_token: String,
          payment_due_date: Date?,
          period_totals: Lithic::StatementTotals,
          starting_balance: Integer,
          statement_end_date: Date,
          statement_start_date: Date,
          statement_type: Lithic::Models::FinancialAccounts::Statement::statement_type,
          updated: Time,
          ytd_totals: Lithic::StatementTotals,
          ?interest_details: Lithic::FinancialAccounts::Statement::InterestDetails?,
          ?next_payment_due_date: Date,
          ?next_statement_end_date: Date,
          ?payoff_details: Lithic::FinancialAccounts::Statement::PayoffDetails?
        ) -> void

        def to_hash: -> {
          token: String,
          account_standing: Lithic::FinancialAccounts::Statement::AccountStanding,
          amount_due: Lithic::FinancialAccounts::Statement::AmountDue,
          available_credit: Integer,
          created: Time,
          credit_limit: Integer,
          credit_product_token: String,
          days_in_billing_cycle: Integer,
          ending_balance: Integer,
          financial_account_token: String,
          payment_due_date: Date?,
          period_totals: Lithic::StatementTotals,
          starting_balance: Integer,
          statement_end_date: Date,
          statement_start_date: Date,
          statement_type: Lithic::Models::FinancialAccounts::Statement::statement_type,
          updated: Time,
          ytd_totals: Lithic::StatementTotals,
          interest_details: Lithic::FinancialAccounts::Statement::InterestDetails?,
          next_payment_due_date: Date,
          next_statement_end_date: Date,
          payoff_details: Lithic::FinancialAccounts::Statement::PayoffDetails?
        }

        type account_standing =
          {
            consecutive_full_payments_made: Integer,
            consecutive_minimum_payments_made: Integer,
            consecutive_minimum_payments_missed: Integer,
            days_past_due: Integer,
            financial_account_state: Lithic::FinancialAccounts::Statement::AccountStanding::FinancialAccountState,
            has_grace: bool,
            period_number: Integer,
            period_state: Lithic::Models::FinancialAccounts::Statement::AccountStanding::period_state
          }

        class AccountStanding < Lithic::Internal::Type::BaseModel
          attr_accessor consecutive_full_payments_made: Integer

          attr_accessor consecutive_minimum_payments_made: Integer

          attr_accessor consecutive_minimum_payments_missed: Integer

          attr_accessor days_past_due: Integer

          attr_accessor financial_account_state: Lithic::FinancialAccounts::Statement::AccountStanding::FinancialAccountState

          attr_accessor has_grace: bool

          attr_accessor period_number: Integer

          attr_accessor period_state: Lithic::Models::FinancialAccounts::Statement::AccountStanding::period_state

          def initialize: (
            consecutive_full_payments_made: Integer,
            consecutive_minimum_payments_made: Integer,
            consecutive_minimum_payments_missed: Integer,
            days_past_due: Integer,
            financial_account_state: Lithic::FinancialAccounts::Statement::AccountStanding::FinancialAccountState,
            has_grace: bool,
            period_number: Integer,
            period_state: Lithic::Models::FinancialAccounts::Statement::AccountStanding::period_state
          ) -> void

          def to_hash: -> {
            consecutive_full_payments_made: Integer,
            consecutive_minimum_payments_made: Integer,
            consecutive_minimum_payments_missed: Integer,
            days_past_due: Integer,
            financial_account_state: Lithic::FinancialAccounts::Statement::AccountStanding::FinancialAccountState,
            has_grace: bool,
            period_number: Integer,
            period_state: Lithic::Models::FinancialAccounts::Statement::AccountStanding::period_state
          }

          type financial_account_state =
            {
              status: Lithic::Models::FinancialAccounts::Statement::AccountStanding::FinancialAccountState::status,
              substatus: Lithic::Models::FinancialAccounts::Statement::AccountStanding::FinancialAccountState::substatus?
            }

          class FinancialAccountState < Lithic::Internal::Type::BaseModel
            attr_accessor status: Lithic::Models::FinancialAccounts::Statement::AccountStanding::FinancialAccountState::status

            attr_accessor substatus: Lithic::Models::FinancialAccounts::Statement::AccountStanding::FinancialAccountState::substatus?

            def initialize: (
              status: Lithic::Models::FinancialAccounts::Statement::AccountStanding::FinancialAccountState::status,
              ?substatus: Lithic::Models::FinancialAccounts::Statement::AccountStanding::FinancialAccountState::substatus?
            ) -> void

            def to_hash: -> {
              status: Lithic::Models::FinancialAccounts::Statement::AccountStanding::FinancialAccountState::status,
              substatus: Lithic::Models::FinancialAccounts::Statement::AccountStanding::FinancialAccountState::substatus?
            }

            type status = :OPEN | :CLOSED | :SUSPENDED | :PENDING

            module Status
              extend Lithic::Internal::Type::Enum

              OPEN: :OPEN
              CLOSED: :CLOSED
              SUSPENDED: :SUSPENDED
              PENDING: :PENDING

              def self?.values: -> ::Array[Lithic::Models::FinancialAccounts::Statement::AccountStanding::FinancialAccountState::status]
            end

            type substatus =
              :CHARGED_OFF_DELINQUENT
              | :CHARGED_OFF_FRAUD
              | :END_USER_REQUEST
              | :BANK_REQUEST
              | :DELINQUENT

            module Substatus
              extend Lithic::Internal::Type::Enum

              CHARGED_OFF_DELINQUENT: :CHARGED_OFF_DELINQUENT
              CHARGED_OFF_FRAUD: :CHARGED_OFF_FRAUD
              END_USER_REQUEST: :END_USER_REQUEST
              BANK_REQUEST: :BANK_REQUEST
              DELINQUENT: :DELINQUENT

              def self?.values: -> ::Array[Lithic::Models::FinancialAccounts::Statement::AccountStanding::FinancialAccountState::substatus]
            end
          end

          type period_state = :STANDARD | :PROMO | :PENALTY

          module PeriodState
            extend Lithic::Internal::Type::Enum

            STANDARD: :STANDARD
            PROMO: :PROMO
            PENALTY: :PENALTY

            def self?.values: -> ::Array[Lithic::Models::FinancialAccounts::Statement::AccountStanding::period_state]
          end
        end

        type amount_due = { amount: Integer, past_due: Integer }

        class AmountDue < Lithic::Internal::Type::BaseModel
          attr_accessor amount: Integer

          attr_accessor past_due: Integer

          def initialize: (amount: Integer, past_due: Integer) -> void

          def to_hash: -> { amount: Integer, past_due: Integer }
        end

        type statement_type = :INITIAL | :PERIOD_END | :FINAL

        module StatementType
          extend Lithic::Internal::Type::Enum

          INITIAL: :INITIAL
          PERIOD_END: :PERIOD_END
          FINAL: :FINAL

          def self?.values: -> ::Array[Lithic::Models::FinancialAccounts::Statement::statement_type]
        end

        type interest_details =
          {
            actual_interest_charged: Integer?,
            daily_balance_amounts: Lithic::CategoryDetails,
            effective_apr: Lithic::CategoryDetails,
            interest_calculation_method: Lithic::Models::FinancialAccounts::Statement::InterestDetails::interest_calculation_method,
            interest_for_period: Lithic::CategoryDetails,
            prime_rate: String?,
            minimum_interest_charged: Integer?
          }

        class InterestDetails < Lithic::Internal::Type::BaseModel
          attr_accessor actual_interest_charged: Integer?

          attr_accessor daily_balance_amounts: Lithic::CategoryDetails

          attr_accessor effective_apr: Lithic::CategoryDetails

          attr_accessor interest_calculation_method: Lithic::Models::FinancialAccounts::Statement::InterestDetails::interest_calculation_method

          attr_accessor interest_for_period: Lithic::CategoryDetails

          attr_accessor prime_rate: String?

          attr_accessor minimum_interest_charged: Integer?

          def initialize: (
            actual_interest_charged: Integer?,
            daily_balance_amounts: Lithic::CategoryDetails,
            effective_apr: Lithic::CategoryDetails,
            interest_calculation_method: Lithic::Models::FinancialAccounts::Statement::InterestDetails::interest_calculation_method,
            interest_for_period: Lithic::CategoryDetails,
            prime_rate: String?,
            ?minimum_interest_charged: Integer?
          ) -> void

          def to_hash: -> {
            actual_interest_charged: Integer?,
            daily_balance_amounts: Lithic::CategoryDetails,
            effective_apr: Lithic::CategoryDetails,
            interest_calculation_method: Lithic::Models::FinancialAccounts::Statement::InterestDetails::interest_calculation_method,
            interest_for_period: Lithic::CategoryDetails,
            prime_rate: String?,
            minimum_interest_charged: Integer?
          }

          type interest_calculation_method = :DAILY | :AVERAGE_DAILY

          module InterestCalculationMethod
            extend Lithic::Internal::Type::Enum

            DAILY: :DAILY
            AVERAGE_DAILY: :AVERAGE_DAILY

            def self?.values: -> ::Array[Lithic::Models::FinancialAccounts::Statement::InterestDetails::interest_calculation_method]
          end
        end

        type payoff_details =
          {
            minimum_payment_months: String,
            minimum_payment_total: String,
            payoff_period_length_months: Integer?,
            payoff_period_monthly_payment_amount: Integer?,
            payoff_period_payment_total: Integer?
          }

        class PayoffDetails < Lithic::Internal::Type::BaseModel
          attr_accessor minimum_payment_months: String

          attr_accessor minimum_payment_total: String

          attr_accessor payoff_period_length_months: Integer?

          attr_accessor payoff_period_monthly_payment_amount: Integer?

          attr_accessor payoff_period_payment_total: Integer?

          def initialize: (
            minimum_payment_months: String,
            minimum_payment_total: String,
            payoff_period_length_months: Integer?,
            payoff_period_monthly_payment_amount: Integer?,
            payoff_period_payment_total: Integer?
          ) -> void

          def to_hash: -> {
            minimum_payment_months: String,
            minimum_payment_total: String,
            payoff_period_length_months: Integer?,
            payoff_period_monthly_payment_amount: Integer?,
            payoff_period_payment_total: Integer?
          }
        end
      end
    end
  end
end
