module Lithic
  module Models
    module FinancialAccounts
      type financial_accounts_statements =
        { data: ::Array[Lithic::FinancialAccounts::Statement], has_more: bool }

      class FinancialAccountsStatements < Lithic::Internal::Type::BaseModel
        attr_accessor data: ::Array[Lithic::FinancialAccounts::Statement]

        attr_accessor has_more: bool

        def initialize: (
          data: ::Array[Lithic::FinancialAccounts::Statement],
          has_more: bool
        ) -> void
      end
    end
  end
end
