module Lithic
  module Models
    module FinancialAccounts
      type statement_list_params =
        {
          begin_: Date,
          end_: Date,
          ending_before: String,
          include_initial_statements: bool,
          page_size: Integer,
          starting_after: String
        }
        & Lithic::Internal::Type::request_parameters

      class StatementListParams < Lithic::Internal::Type::BaseModel
        extend Lithic::Internal::Type::RequestParameters::Converter
        include Lithic::Internal::Type::RequestParameters

        attr_reader begin_: Date?

        def begin_=: (Date) -> Date

        attr_reader end_: Date?

        def end_=: (Date) -> Date

        attr_reader ending_before: String?

        def ending_before=: (String) -> String

        attr_reader include_initial_statements: bool?

        def include_initial_statements=: (bool) -> bool

        attr_reader page_size: Integer?

        def page_size=: (Integer) -> Integer

        attr_reader starting_after: String?

        def starting_after=: (String) -> String

        def initialize: (
          ?begin_: Date,
          ?end_: Date,
          ?ending_before: String,
          ?include_initial_statements: bool,
          ?page_size: Integer,
          ?starting_after: String,
          ?request_options: Lithic::request_opts
        ) -> void
      end
    end
  end
end
